### ISSUE TITLE
இந்தி பொது மொழியா?

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#1]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0471.html

**Comment by tshrinivasan** [comment]
![hindi](https://user-images.githubusercontent.com/1268536/38497953-77597f50-3c20-11e8-94d0-e4c08902ca40.jpg)

**Comment by rajiinperth** [comment]
need artist name

**Comment by tshrinivasan** [comment]
its me

**Comment by rajiinperth** [comment]
okay

**Comment by rajiinperth** [comment]
https://archive.org/details/CommonHindiA4

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/is_hindi_a_common_language/

released here
