### ISSUE TITLE
எதிர்விடு சிறுகதைத் தொகுப்பு

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#101]

**Comment by tshrinivasan** [comment]
![ethirveedu](https://user-images.githubusercontent.com/1268536/39084224-5d76fa7c-458f-11e8-8692-c6a5795cdda2.jpg)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/ethir_vedu

**Comment by tshrinivasan** [comment]
There are no space between paragraphs in PDF and epub.

can you rework on this @dna80 ?

open the a4 odt.
select all (crtl a)
Format->paragraph
spacing -> below paragraph = 0.5cm

This will add a line below all paras.

then, readd TOC.

**Comment by tkdhanasekar** [comment]
ok will rework the book ethir vedu




regards,

T.Dhanasekar

**Comment by tshrinivasan** [comment]
can you work on this?

author is asking.

**Comment by tkdhanasekar** [comment]
space below paragaph fixed 0.50 cm
it seems big space between paragraphs
is it ok or to fix space 0.40 , and for 6 inch odt
any changes needed ?
give me suggestion to proceed further. see attachment
fixed with 0.5 cm



regards,

T.Dhanasekar

**Comment by tshrinivasan** [comment]
0.5 cm is fine for paras.

Do the same for both PDF files.

ஞாயி., 27 மே, 2018, முற்பகல் 8:55க்கு, dna80 <notifications@github.com>
எழுதியது:

**Comment by tshrinivasan** [comment]
https://archive.org/details/ethir_vedu_201806

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/ethir_vedu/

released here
