### ISSUE TITLE
புத்தகத்தில் புலம்புகிறேன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#102]
cover, contents sent in mail  to @dna80

**Comment by tshrinivasan** [comment]
![puthagathil-pulambukiren-2](https://user-images.githubusercontent.com/1268536/45688214-6cbe2f00-bb6e-11e8-8d02-dfc0f4f90ae9.jpg)
![puthagathil-pulambukiren-1](https://user-images.githubusercontent.com/1268536/45688216-6d56c580-bb6e-11e8-9875-f0efc70294ac.jpg)
![img-20170111-wa0002](https://user-images.githubusercontent.com/1268536/45688218-6d56c580-bb6e-11e8-8513-25e4a7474dbf.jpg)
[புத்தகத்தில் புலம்புகிறேன்(1).docx](https://github.com/KaniyamFoundation/Ebooks/files/2392670/1.docx)
[அணிந்துரை.docx](https://github.com/KaniyamFoundation/Ebooks/files/2392671/default.docx)

**Comment by rajiinperth** [comment]
Need artist name

**Comment by tshrinivasan** [comment]
we dont know the artist name.

leave artist name and email as empty

**Comment by rajiinperth** [comment]
okay

**Comment by rajiinperth** [comment]
https://archive.org/details/PuthakathilPulambukiren6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Puthakathil_Pulambukiren
