### ISSUE TITLE
மாற்றம் ஏமாற்றமில்லை (கட்டுரைத்தொகுப்பு) - நிர்மலா ராகவன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#104]
[மாற்றம் ஏமாற்றமல்ல தொகுப்பு.docx](https://github.com/KaniyamFoundation/Ebooks/files/1934511/default.docx)

**Comment by gurulenin** [comment]
![maatram](https://user-images.githubusercontent.com/15311390/39092073-896846b2-4621-11e8-920f-f1afa6636902.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Maatram_Yematramillai-2018-04-22-21-57-42

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/maatram_yematramillai/

இங்கே வெளியிட்டுள்ளோம்
