### ISSUE TITLE
கர்வமும் காலணியும் (கட்டுரைகள்) - நிர்மலா ராகவன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#105]
[கர்வமும் காலணியும் (2).docx](https://github.com/KaniyamFoundation/Ebooks/files/1934512/2.docx)

**Comment by tshrinivasan** [comment]
![default](https://user-images.githubusercontent.com/1268536/50397946-dc5d3f00-0799-11e9-88a6-0a715ec540e9.jpg)

அட்டைப்படம் -
பெயர் - எம்.ரிஷான் ஷெரீப்  
மின்னஞ்சல் முகவரி - mrishansha@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/KarvamumKalaniyum

**Comment by gurulenin** [comment]
released..

http://freetamilebooks.com/ebooks/karvamum_kaalanium
