### ISSUE TITLE
இம்மையில் இன்பம் சூழ (கட்டுரைத்தொகுப்பு) - நிர்மலா ராகவன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#106]
[இம்மையில் இன்பம் சூழ.docx](https://github.com/KaniyamFoundation/Ebooks/files/1934513/default.docx)

**Comment by gurulenin** [comment]
![immai](https://user-images.githubusercontent.com/15311390/39086713-da34bd78-45b3-11e8-816a-a6501986e440.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Immaiyil_Inbam_Soozha-2018-04-22-22-03-44

**Comment by tshrinivasan** [comment]
there is no line breaks for paragraphs in pdf and epub.

We have to rework on this book.

**Comment by gurulenin** [comment]
https://archive.org/details/Immaiyil_Inbam_Soozha-2018-04-25-08-05-38

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/immaiyil_inbam_soozha/

இங்கே வெளியிட்டுள்ளோம்
