### ISSUE TITLE
தூறல் துளிகள் - கவிதைத்தொகுப்பு

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#107]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/freetamilebooksforum/SKbk7po3Mkw/h-I5vMKPAgAJ

cover, content is here

**Comment by gurulenin** [comment]
https://archive.org/details/Thooral_Thuligal-2019-01-11-09-11-40

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/thooral_thuligal

இங்கே வெளியிட்டுள்ளோம்.

நன்றி
