### ISSUE TITLE
 கலிங்கராணி - அறிஞர் அண்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#109]
http://www.annavinpadaippugal.info/navalgal/kalingarani_1.htm

**Comment by balaaagi** [comment]
![selection_054](https://user-images.githubusercontent.com/2221784/39085472-5ee3d90a-45a0-11e8-9258-bf55feb35059.png)

**Comment by tshrinivasan** [comment]
![default](https://user-images.githubusercontent.com/1268536/52323579-8d92fe00-2a03-11e9-9336-e69cb0ce7b75.jpg)

அட்டைப்படம்
பெயர் - எம்.ரிஷான் ஷெரீப்  
மின்னஞ்சல் முகவரி - mrishansha@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/KalingaRani6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/KalingaRani
