### ISSUE TITLE
பார்வதி பி.ஏ. - அறிஞர் அண்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#110]
http://www.annavinpadaippugal.info/navalgal/parvathi_ba_1.htm

**Comment by balaaagi** [comment]
![selection_053](https://user-images.githubusercontent.com/2221784/39085437-e8e8d3b8-459f-11e8-9969-b786b3715960.png)

**Comment by tshrinivasan** [comment]
![-](https://user-images.githubusercontent.com/1268536/51074778-2060a700-16a9-11e9-9e9c-0306481990bb.jpg)


பெயர் - எம்.ரிஷான் ஷெரீப்  
மின்னஞ்சல் முகவரி - mrishansha@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/Parvathi.B.A6Inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/parvathi_b_a

வெளியிடப்பட்டது.
