### ISSUE TITLE
தசாவதாரம் - அறிஞர் அண்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#111]
http://www.annavinpadaippugal.info/navalgal/dhasavatharam_1.htm

**Comment by balaaagi** [comment]
![selection_052](https://user-images.githubusercontent.com/2221784/39085427-a9c20484-459f-11e8-80a8-12555029fd3a.png)

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/dasavatharam/
