### ISSUE TITLE
எளியோருக்கான  சட்டங்கள்.!

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#113]
content sent to @dna80

**Comment by gurulenin** [comment]
![rules](https://user-images.githubusercontent.com/15311390/39084571-c26335e4-4595-11e8-9ed8-655d9694a6a2.jpg)

**Comment by tshrinivasan** [comment]
ராசா. துரியோதனன் M.A., B.L.,
வழக்கறிஞர்

add this in cover image

**Comment by gurulenin** [comment]
![rules](https://user-images.githubusercontent.com/15311390/39084832-51182ac2-4598-11e8-897e-ad2892ab278f.jpg)

**Comment by rajiinperth** [comment]
Can I get the content ?

**Comment by tshrinivasan** [comment]
[நீதியைத்தேடி 7 final 2.docx](https://github.com/KaniyamFoundation/Ebooks/files/3186757/7.final.2.docx)

change the book name as எளியோருக்கான சட்டங்கள்

**Comment by rajiinperth** [comment]
okay shrini

**Comment by rajiinperth** [comment]
https://archive.org/details/EliyorkanaSattangal6Inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/eliyorkkaana_sattangal


வெளியிடப்பட்டது.
