### ISSUE TITLE
 சிலப்பதிகாரமும் சந்திரமுகியும் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#114]
content, cover image is here
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!category-topic/freetamilebooksforum/X223WPpsMFg

**Comment by rajiinperth** [comment]
I think this book is done...http://freetamilebooks.com/ebooks/silapathigaram-and-chandramuki-dramas/

Please check
