### ISSUE TITLE
தைத்திரீய உபநிஷத் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#116]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!category-topic/freetamilebooksforum/a9SMdLlWAYU

content, cover is here

**Comment by rajiinperth** [comment]
https://archive.org/details/ThaithreyaUpanisth6Inch_201810

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/thaithreya-upanisth/
