### ISSUE TITLE
பகவத்கீதை பன்முக குரல்கள் - ஆர். பட்டாபிராமன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#117]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!category-topic/freetamilebooksforum/C_pMjlP0phE

content is here

**Comment by balaaagi** [comment]
![selection_051](https://user-images.githubusercontent.com/2221784/39085350-bdc75606-459e-11e8-96bb-feec2889756c.png)

**Comment by balaaagi** [comment]
https://www.scribd.com/document/344230897/GITA-MULTIPLE-ECHOES-%E0%AE%AA%E0%AE%95%E0%AE%B5%E0%AE%A4-%E0%AE%95%E0%AF%80%E0%AE%A4%E0%AF%88-%E0%AE%AA%E0%AE%A9-%E0%AE%AE%E0%AF%81%E0%AE%95-%E0%AE%95%E0%AF%81%E0%AE%B0%E0%AE%B2-%E0%AE%95%E0%AE%B3  Found the ebook here

**Comment by tshrinivasan** [comment]
Thanks @balaaagi

Cover image should reflect the content or topic.
it should have author name.

Will nice if an image related to geetha is used as cover image.

Will create new images soon.

**Comment by gurulenin** [comment]
![bagawad](https://user-images.githubusercontent.com/15311390/39086501-d30fca00-45af-11e8-97de-5724a2335a8a.jpg)

**Comment by gurulenin** [comment]
பகவத்கீதை பன்முக குரல்கள் or பகவத்கீதை பன்முகக் குரல்கள்

**Comment by tshrinivasan** [comment]
பகவத்கீதை -  பன்முகக் குரல்கள்

**Comment by gurulenin** [comment]
![bagawad](https://user-images.githubusercontent.com/15311390/39086676-02bef2d2-45b3-11e8-9ec9-6d3519d35b2a.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/GITA_MULTIPLE_ECHOES-2018-06-16-09-18-48

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/gita_multiple_echoes/

released here
