### ISSUE TITLE
பூப்பதெல்லாம் -  சிறுகதைகள் - விமலன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#118]
contents sent to @dna80 in mail

**Comment by tshrinivasan** [comment]
![poopathellam](https://user-images.githubusercontent.com/1268536/39126262-81476964-471f-11e8-95fd-40a9ecd7269f.jpg)

**Comment by tshrinivasan** [comment]
sent mail to @rajiinperth

**Comment by rajiinperth** [comment]
Please send me the content

**Comment by rajiinperth** [comment]
Need artist name

**Comment by tshrinivasan** [comment]
Dont know. Leave artist info.

-- 
Regards,
T.Shrinivasan


My Life with GNU/Linux : http://goinggnu.wordpress.com
Free E-Magazine on Free Open Source Software in Tamil : http://kaniyam.com

Get Free Tamil Ebooks for Android, iOS, Kindle, Computer :
http://FreeTamilEbooks.com

**Comment by rajiinperth** [comment]
ok

**Comment by rajiinperth** [comment]
https://archive.org/details/Poopthellam6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Poopethellam-short-stories
