### ISSUE TITLE
﻿நித்திலவல்லி - நா. பார்த்தசாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#121]
https://ta.wikisource.org/s/1tl

**Comment by rishanshareef** [comment]
பெயர் - எம்.ரிஷான் ஷெரீப்  
மின்னஞ்சல் முகவரி - mrishansha@gmail.com

**Comment by tshrinivasan** [comment]
![default](https://user-images.githubusercontent.com/1268536/50397971-18909f80-079a-11e9-8012-839d9d5de7a5.jpg)

அட்டைப்படம் -
பெயர் - எம்.ரிஷான் ஷெரீப்
மின்னஞ்சல் முகவரி - mrishansha@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/Nithilavalli6Inch

**Comment by gurulenin** [comment]
released here..

http://freetamilebooks.com/ebooks/Nithilavalli
