### ISSUE TITLE
கிரேக்க நாட்டுப் பழமைப் பண்புகள் - பாலூர் கண்ணப்ப முதலியார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#123]
https://ta.wikisource.org/s/8xe9

**Comment by gurulenin** [comment]
![greek](https://user-images.githubusercontent.com/15311390/46270766-e4289100-c566-11e8-9ce2-d2fcd4795c0d.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/grekka_naattu_pazhamaippanpugal-2018-11-13-23-01-17
