### ISSUE TITLE
சிலம்பின் கதை -  டாக்டர். ரா. சீனிவாசன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#124]
https://ta.wikisource.org/s/8xiy

**Comment by gurulenin** [comment]
![silambu](https://user-images.githubusercontent.com/15311390/46275051-48545080-c579-11e8-8f78-8331060cda49.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Silambin_Kadhai-2019-01-10-09-11-29

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/silambin_kathai

இங்கே வெளியிட்டுள்ளோம்
