### ISSUE TITLE
ஊருக்குள் ஒரு புரட்சி - சு. சமுத்திரம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#125]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0620.html

**Comment by gurulenin** [comment]
![revolution](https://user-images.githubusercontent.com/15311390/48668228-8b10be80-eb0e-11e8-8703-4135662c2d47.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/oorukkul_oru_puratchi-2018-11-18-09-22-33

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/oorukkul_oru_puratchi
