### ISSUE TITLE
சேற்றில் மனிதர்கள் - ராஜம் கிருஷ்ணன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#126]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0619.html

**Comment by gurulenin** [comment]
![farmer](https://user-images.githubusercontent.com/15311390/48669069-db454c00-eb21-11e8-8ad7-15e705bda160.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/chaettril_manithargal-2018-11-18-11-03-50

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/setril_manithargal
