### ISSUE TITLE
கடவுள் வழிபாட்டு வரலாறு - பேரா. சுந்தரசண்முகனார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#132]
https://ta.wikisource.org/s/8xoi

license : public domain - CC0

**Comment by gurulenin** [comment]
![prayer-history](https://user-images.githubusercontent.com/15311390/47267039-d5c50800-d55b-11e8-906f-abdb10bf0410.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/kadavul_vazhipaattu_varalaru-2018-11-24-08-11-10

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/kadavul_vazhibattu_varalaru
released here
