### ISSUE TITLE
ஆர்க்டிக் பெருங்கடல் - பேரா. அ. கி. மூர்த்தி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#133]
https://ta.wikisource.org/s/8xp0

License : Public Domain - CC0

**Comment by gurulenin** [comment]
![arctic](https://user-images.githubusercontent.com/15311390/47978296-eb513a80-e0e2-11e8-9196-8e23e393b837.jpg)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : லெனின் குருசாமி

guruleninn@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/ArcticOcean6Inch

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/arctic_ocean
இங்கே வெளியிட்டுள்ளோம்
