### ISSUE TITLE
பட்டுக்கோட்டை கல்யாணசுந்தரம் பாடல்கள்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#139]
http://projectmadurai.org/pm_etexts/utf8/pmuni0161.html

License - Public Domain - CC0

**Comment by tshrinivasan** [comment]
![pattukottai](https://user-images.githubusercontent.com/1268536/48044058-e9a17880-e1af-11e8-9a96-90fbb1b70846.jpg)

cover image by - த.சீனிவாசன் tshrinivasan@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/pkkssongs6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/PKKSSongs
