### ISSUE TITLE
ஷோபாசக்தி நேர்காணல்கள்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#141]
http://www.shobasakthi.com/shobasakthi/category/நேர்காணல்கள்/

**Comment by tshrinivasan** [comment]
![shoba-sakthi-interviews](https://user-images.githubusercontent.com/1268536/48042623-692b4980-e1a8-11e8-8d84-55dbcdfc2468.jpg)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் - த.சீனிவாசன் tshrinivasan@gmail.com
உரிமை - Creative Commons Attribution-Non-commercial-No Derivatives 4.0 International License.

**Comment by tshrinivasan** [comment]
Got below mail from author.
====

Shoba sakthi <shobasakthi@hotmail.com> 
வணக்கம் அய்யா.


சிறுகதைகள் தவிர்த்து மற்றைய ஆக்கங்கங்களை வெளியிடுங்கள்.


வாழ்த்துகளுடன்

ஷோபா

**Comment by rajiinperth** [comment]
okay

**Comment by rajiinperth** [comment]
https://archive.org/details/Shobhasakthi6Inch

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/interviews_of_shobasakthi/
இங்கே வெளியிட்டுள்ளோம்.
