### ISSUE TITLE
தமிழின் எதிர்காலமும் தகவல் தொழில்நுட்பமும்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#149]
http://www.kaniyam.com/category/information-technology/

ஆசிரியர் - இரா. அசோகன் ashokramach@gmail.com

உரிமை - Creative Commons Attribution-ShareAlike CC BY-SA

**Comment by gurulenin** [comment]
![tamil-tech](https://user-images.githubusercontent.com/15311390/48525956-e55e1500-e8ab-11e8-98f5-c6b236dbc9e9.jpg)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : லெனின் குருசாமி

guruleninn@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/ThamilEthirkalam6Inch

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம்
http://freetamilebooks.com/ebooks/Future_of_Tamil_and_Information_technology
