### ISSUE TITLE
தந்தை பெரியார் சிந்தனைகள் -  ந. சுப்புரெட்டியார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#151]
https://ta.wikisource.org/s/8r23

Public domain - CC0

**Comment by tshrinivasan** [comment]
அட்டைப்படம்

பெயர் - எம்.ரிஷான் ஷெரீப்  
மின்னஞ்சல் முகவரி - mrishansha@gmail.com
![default](https://user-images.githubusercontent.com/1268536/51821277-aa8e4980-22fe-11e9-8e57-1cc233178ab4.jpg)

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/periyar_thoughts/

வெளியிடப்பட்டது.
