### ISSUE TITLE
நபிகள் நாயகம்-கி. ஆ. பெ. விசுவநாதம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#152]
https://ta.wikisource.org/s/8xs4

Public Domain - CC0

**Comment by rishanshareef** [comment]
பெயர் - எம்.ரிஷான் ஷெரீப் 
மின்னஞ்சல் - mrishansha@gmail.com
![default](https://user-images.githubusercontent.com/45729603/49695201-6c9b6180-fba8-11e8-8847-1ca864d614d1.jpg)

**Comment by tshrinivasan** [comment]
closing this as duplicate of #167
