### ISSUE TITLE
ஆரியர்க்கு முற்பட்ட தமிழ்ப்பண்பாடு - கா. கோவிந்தன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#153]
https://ta.wikisource.org/s/8xq9

Public Domain - CC0

**Comment by gkpriya246** [comment]
![cover2](https://user-images.githubusercontent.com/38214999/57233036-821f9500-703b-11e9-8033-7068295bd0ba.jpg)
அட்டைப்படம் : க சாந்திபிரியா
மின்னஞ்சல் : gkpriya246@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/TamilpanpaduA4

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/aariyarkuku_murpatta_tamizhpanbaadu

வெளியிடப்பட்டது.
