### ISSUE TITLE
எழுத்தாளர் சோபாசக்தி இணையதளம் மின் நூல் உருவாக்கு

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#158]
எழுத்தாளர் சோபா சக்தி அவர்களின் இணையதள கட்டுரைக்ள,கதைகள் எந்தவித காப்புரிமை இல்லாமல் கிடைக்கிறது மின் நூல் உறுவாக்கவும் 

இணைப்பு ; http://www.shobasakthi.com/shobasakthi/

![image](https://user-images.githubusercontent.com/38220354/48846719-cbe62d00-edc5-11e8-9dee-a32e14596aa7.png)

**Comment by tshrinivasan** [comment]
already working on a book

see here
https://github.com/KaniyamFoundation/Ebooks/issues/141
