### ISSUE TITLE
இந்திய சமுதாய வரலாற்றில் பெண்மை - ராஜம் கிருஷ்ணன் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#165]
https://ta.wikisource.org/s/8xvf

license - public domain - cc0

**Comment by rishanshareef** [comment]
Front Cover
![front cover](https://user-images.githubusercontent.com/45729603/49717997-d3348400-fc69-11e8-9161-53fcfe1d8a02.jpg)

பெயர் - எம்.ரிஷான் ஷெரீப்
மின்னஞ்சல் - mrishansha@gmail.com

**Comment by rishanshareef** [comment]
Back Cover

பெயர் - எம்.ரிஷான் ஷெரீப்
மின்னஞ்சல் - mrishansha@gmail.com
![back cover](https://user-images.githubusercontent.com/45729603/49718029-ee06f880-fc69-11e8-9c97-405544283c53.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/IndSocietyPenmai6Inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/feminism-in-indian-social-history/
