### ISSUE TITLE
நபிகள் நாயகம்-கி. ஆ. பெ. விசுவநாதம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#167]
https://ta.wikisource.org/s/8xs4

license : public domain - cc0

**Comment by rishanshareef** [comment]
![default](https://user-images.githubusercontent.com/45729603/49695164-c3546b80-fba7-11e8-91ba-8e944732cb82.jpg)

Cover page 
பெயர் - எம்.ரிஷான் ஷெரீப் 
மின்னஞ்சல் - mrishansha@gmail.com

**Comment by tshrinivasan** [comment]
அருமையான படத்துக்கு நன்றி ரிஷான்.

**Comment by rajiinperth** [comment]
https://archive.org/details/Nabikalnayagam6Inch

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/NabikalNayagam
இங்கே வெளியிட்டுள்ளோம்
