### ISSUE TITLE
நீதிதேவன் மயக்கம் (நாடகம்) அறிஞர் அண்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#170]
https://www.projectmadurai.org/pm_etexts/utf8/pmuni0649.html

உரிமை - Public Domain - CC0

**Comment by gkpriya246** [comment]
![cover4](https://user-images.githubusercontent.com/38214999/57237351-a59b0d80-7044-11e9-81df-aa5fb838f144.jpg)
அட்டைப்படம் : க சாந்திபிரியா
மின்னஞ்சல் : gkpriya246@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/NethithevanMayakkam6Inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/neethidevan_mayakkam

வெளியிடப்பட்டது.
