### ISSUE TITLE
”பௌத்தமும் தமிழும்”  - மயிலை சீனி. வேங்கடசாமி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#171]
https://www.projectmadurai.org/pm_etexts/utf8/pmuni0648.html

உரிமை - Public Domain - CC0

**Comment by tshrinivasan** [comment]
![default](https://user-images.githubusercontent.com/1268536/50472439-cf7d5d00-09de-11e9-85d8-88453f72b33c.jpg)

அட்டைப்படம்
பெயர் - எம்.ரிஷான் ஷெரீப்  
மின்னஞ்சல் முகவரி - mrishansha@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/pauttamumtamizum6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/pauttamum_tamizum/
