### ISSUE TITLE
விசிறி வாழை (நாவல்) - சாவி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#172]
https://www.projectmadurai.org/pm_etexts/utf8/pmuni0643.html

உரிமை - Public Domain - CC0

**Comment by gurulenin** [comment]
![visiri-vaazhai](https://user-images.githubusercontent.com/15311390/51087813-d72e5700-177d-11e9-9fc6-86932a2f0342.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/VisiriVazhai6Inch

**Comment by gurulenin** [comment]
released here

http://freetamilebooks.com/ebooks/visiri-vazhai/
