### ISSUE TITLE
இலக்கிய இன்பம் - ஆராய்ச்சிக் கட்டுரைகள் - நாமக்கல் கவிஞர் இராமலிங்கம் பிள்ளை

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#173]
https://www.projectmadurai.org/pm_etexts/utf8/pmuni0642.html

உரிமை - Public Domain - CC0

**Comment by gurulenin** [comment]
![ilakiya-inbam](https://user-images.githubusercontent.com/15311390/51085843-cd4c2a00-1764-11e9-9975-f8bd632f6c8b.jpg)

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/ilakiya_inbam

வெளியிடப்பட்டத்து.
