### ISSUE TITLE
சந்திரமோகன் - நாடகம் - அறிஞர் அண்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#174]
https://www.projectmadurai.org/pm_etexts/utf8/pmuni0641.html

உரிமை - Public Domain - CC0

**Comment by gkpriya246** [comment]
![cover6](https://user-images.githubusercontent.com/38214999/57389282-736de500-71d7-11e9-9d97-7779e25a4128.jpg)
அட்டைப்படம் : க சாந்திபிரியா
மின்னஞ்சல் : gkpriya246@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/chandramohan_A4

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/chandramohan

published..
