### ISSUE TITLE
குமாஸ்தாவின் பெண் - நாவல் - அறிஞர் அண்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#175]
https://www.projectmadurai.org/pm_etexts/utf8/pmuni0629.html

உரிமை - Public Domain - CC0

**Comment by tshrinivasan** [comment]
அட்டைப்படம்

பெயர் - எம்.ரிஷான் ஷெரீப்  
மின்னஞ்சல் முகவரி - mrishansha@gmail.com

![Uploading குமாஸ்தாவின் பெண்.jpg…]()

**Comment by tshrinivasan** [comment]
![default](https://user-images.githubusercontent.com/1268536/51821392-02c54b80-22ff-11e9-9bb6-496f925fd2a5.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/KumastavinPenn6Inch

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/kumasthavin_penn/

released here
