### ISSUE TITLE
'ஈழம்' தமிழப்பனார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#177]
https://www.vikatan.com/news/tamilnadu/144314-84-years-old-tamilpanaars-love-towards-tamil-books.html

https://timesofindia.indiatimes.com/city/coimbatore/this-retired-revenue-official-is-on-a-mission-to-digitize-rare-tamil-books/articleshow/65848982.cms

இவரைத் தொடர்பு கொண்டு, அவரிடம் உள்ள அரிய பழைய நூல்களை மின்னூலாக்கம் செய்ய வேண்டும்.

@gnuanwar அவரைத் தொடர்பு கொள்ள முயற்சி செய்க.

**Comment by gnuanwar** [comment]
தொடர்புகொள்கிறேன்

**Comment by tshrinivasan** [comment]
https://www.bbc.com/tamil/india-46786921

இவர் பற்றி bbcயில்.

**Comment by tshrinivasan** [comment]
https://www.youtube.com/watch?v=BzSYosCbuG0

news18 செய்தியில்

**Comment by tshrinivasan** [comment]
Got his contact number via malaigal.com sibichelvan.

Spoke to him. He is ready to give his books for scanning.

CIS-A2k is ready to give scanner and a person for scanning.

Wikisource Balaji is in coimbatore now. asked him to meet tamilappan and get more details about his collections.

Will plan after the reports from balaji.

**Comment by gnuanwar** [comment]
Ok

**Comment by balajijagadesh** [comment]
Yesterday met and spoke to Dr. Tamilappan. 

- He has authored 25 books (small books about grammar, poem, etc). He is ready to release them in CCBYSA license. They are to be scanned. 

- Then he has around 25 tamil dictionaries and other books. They are to be scanned using Over Head Scanner(OHS). flatbed wont be used. But these 25 books are subject to copyright. 

- Then around 25 very old books are there to be scanned. Those pages are brittle. They need to be scanned with scanned with utmost care using OHS or so. 

- There are many literary magazines of varying sizes. Some can be scanned by normal scanners. some are of different sizes. Again the magazine might be subject to copyright. All these magazines are from India.

- He has already scanned around 5000 books. Those books he is ready to give if a site is created with the name "உலகத் தமிழ் நூலகம்". He needs help in setting up such a site. Out of 5000 books around 500 books may be out of copyright. Then around 50 books may be related to Srilanka.
![img-20190126-wa0009](https://user-images.githubusercontent.com/19164100/51781919-e16d2f80-2145-11e9-9b78-6c9781d851aa.jpg)
![img-20190126-wa0008](https://user-images.githubusercontent.com/19164100/51781920-e16d2f80-2145-11e9-996e-8f1d887fe638.jpg)
![img-20190126-wa0007](https://user-images.githubusercontent.com/19164100/51781921-e205c600-2145-11e9-9112-71708436f806.jpg)
![img-20190126-wa0006](https://user-images.githubusercontent.com/19164100/51781922-e29e5c80-2145-11e9-9f17-5d7964846e25.jpg)
![img-20190126-wa0005](https://user-images.githubusercontent.com/19164100/51781923-e336f300-2145-11e9-91ac-d796ddf37b79.jpg)
![img-20190126-wa0004](https://user-images.githubusercontent.com/19164100/51781926-e3cf8980-2145-11e9-8cff-64a0e0ae9ec8.jpg)
![img-20190126-wa0003](https://user-images.githubusercontent.com/19164100/51781927-e4682000-2145-11e9-86ea-a0683ae1148b.jpg)
![img-20190126-wa0002](https://user-images.githubusercontent.com/19164100/51781928-e500b680-2145-11e9-8c24-cdc0941cec1e.jpg)

**Comment by tshrinivasan** [comment]
wikisource, CIS, kaniyam wont do works for copyrighted works.
But we need to archive them somewhere.
Not sure we can use archive.org for storing copyrighted works.

He asks for a website named உலகத் தமிழ் நூலகம், to give his already
scanned works.

Checking if it is possible for noolaham foundation to host these copyrighted works
for archival purpose.

If possible, we can send the books to nooaham server and make a
website as he asks.

**Comment by gnuanwar** [comment]
Can list out the titles if some book copyright to publisher's it not print
they may give copyright in cc

**Comment by Natkeeran** [comment]
வணக்கம்,

காப்புரிமைக்கு உட்பட்ட நூற்களை அனுமதி இல்லாமல் நூலகம் வெளியிடுவதில்லை.  மேலும், இலங்கை தொடர்பில்லா நூற்கள் மற்றும் படைப்புகள் எமது செயற்பரப்புக்குள் வரா. காப்புரிமைக்கு உட்பட்ட நூற்களை அனுமதி இன்றி முழுமையாக அணுக்கம் வழங்குவது பொருத்தம் இல்லை.  எனவே அவற்றின் மீதரவினை வெளியிட்டு, கட்டுப்படுத்தப்பட்ட ஆய்வு அணுக்கம் மட்டும் வழங்குவது பொருத்தமானது. அதாவது ஆய்வு காரணமாக ஒருவர் தொடர்பு கொண்டால், அந்தக் குறிப்பான நூலை அவரது ஆய்வுக்கு தனிப்பட்ட முறையில் வழங்குவது. இதை அவருக்கும் விளங்க வைப்பது அவசியம் ஆகிறது என்று கருதுகிறேன்.  

எம்மால் அத்தகைய ஒரு தளத்தை உருவாக்க வழங்கி வழங்கி உதவ முடியும்.  வழங்கி தொடர்பான தேவைகளை குறிப்பிட்டல் தெளிவான ஒரு பதிலை வழங்க முடியும்.  மேலும், க.அ மின்வருடப்பட்ட/மின்வருடப்படும் நூற்களை அவரது அனுமதியுடன் எண்ணிமப் பாதுகாப்புக்கு ஏற்றுக் கொள்ள வேண்டும் என்பது என் பரிந்துரை.  பாலாஜி குறிப்பிட்டது போன்று அவற்றின் ஒரு சிறு பகுதிக்காகவது அனுமதி எடுப்பது சாத்தியமாகலாம்.

மின்வருடப்பட்டவை என்ன தரத்தில் மின்வருடப்பட்டுள்ள என்று அறிய முடியுமா?  
அவற்றுக்கு மீதரவு உருவாக்கப்பட்டுள்ளவா?
தற்போது எத்தனை காப்புப்படிகள் எடுக்கப்பட்டுள்ளன?
இன்னும் மொத்தமாக எத்தனை மின்வருடப்பட வேண்டும் (இதழ்கள் உட்பட்டதாக)?

காப்புரிமை இல்லாத நூற்களை archive.org, wikisource, south asian open archives உட்பட்ட தளங்களில் பதிவேற்ற முடியும். அவற்றை கிட்கப்பில் கூட மொத்தமாக பகிர முடியும்.

இலங்கை தொடர்பான நூற்களை, ஆவணங்களை பெற்று பாதுகாப்பதில் வழமை போன்று நூ.நி சிறப்பான ஆர்வம் உண்டு.  எம்மால் நிச்சியம் அதைச் செய்ய முடியும்.

**Comment by tshrinivasan** [comment]
http://www.kaniyam.com/podcast/balaji_interview_with_tamilappan_books_collector/

Here is the audio recording of the discussion with tamilappan by balaji.

**Comment by gnuanwar** [comment]
16/02/19 அன்று அய்யா தமிழ் அப்பன் சந்தித்து அவர் தன் வசம் உள்ள தமிழ் நூல்களை ஒளி வருடல் செய்ld [archive.org](url) இணையதளத்தில் பதிவேற்றம் செய்ய ஒப்புதல் தந்தார் முதல் கட்டமாக அவர் ஒளிவருடல் செய்த ஆயிரத்திற்க்கு மேற்பட்ட தமிழ் நூல் கோப்புகளை பதிவேற்றம் செய்த பின்பு ஏனைய நூல்களை நணப்ர் Carl Malamud, அவர்கள் தரும் ஒளிவருடல் கருவி மூலம் மூலம் வருடி அவற்றையும் இணையதளத்தில் பதிவேற்றம் செய்யபட்டு 'உலகத் தமிழ்  நூலகம்' அறக்கட்டளை (world Tamil library trust) இணையளத்தில்  நூல்களின் பட்டியல் மற்றும் வகைகள் என வகைபடுத்தபடும் என தமிழ் அப்பன் அவல்களுக்கு விளக்கம் கொடுக்கபட்டது.மேலும் தான் எழுதிய நூல்களை எந்த காப்புரிமையை விட்டு உறுதி அளித்தார் கணியம் அவருடன் இணைந்து செயல்படும் கோவையில் எழுத்தாளர் கோவை ஞானியின் நூல்களை மின் அனுமதி பற்றி பேச பட்டது தமிழ் அப்பன் அவர்களுக்கு  எழுத்தாளருடன் நல்ல தொடர்பு உள்ளதால் அலைபேசியில் தமிழ் அப்பன் தொடர்பு கொண்டு அதுபற்றி பேசி தானும் நூல் அனுமதி பெற என்னுடன் வர உள்ளதாக சொன்னார் அதன் ஒலி கோப்பு அனைவரின் செவிகளுக்கு



https://bit.ly/2Ii9dDh

**Comment by tshrinivasan** [comment]
அன்வர் தமிழப்பனாரை கோவைக்கு சென்று சந்தித்தார்.

தமிழப்பனார் நூல்களை இணையத்தில் மட்டுமே படிக்கும் வகையிலான ஒரு மின்னூலகம் அமைக்குமாறு கோருகிறார்.  யாரும் பதிவிறக்கம் செய்யக் கூடாது என்கிறார்.
இது ஒரு வகை Full DRM ஆகும்.

கணியம் அறக்கட்டளை DRM க்கு எதிரானது.

ஆகையினால் இத்திட்டத்தைக் கைவிடுகிறோம்.
