### ISSUE TITLE
புதிய தமிழகம் - மா. இராசமாணிக்கனார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#18]
http://projectmadurai.org/pm_etexts/utf8/pmuni0590.html

**Comment by prasannaUDPM** [comment]
I take this...

**Comment by gurulenin** [comment]
![new-tamil-rasamanickanaar](https://user-images.githubusercontent.com/15311390/51579000-6d345100-1ee5-11e9-891c-703b4bc6927a.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Pudhiya_Thamizhagam-2019-01-24-08-00-19

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/Pudhiya_Thamizhagam

released here.
