### ISSUE TITLE
“கொழும்பு வழியே ஒரு பயணம்..”

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#191]
“கொழும்பு வழியே ஒரு பயணம்..” மின் நூல் உருவாக்கவும்   

உரிமை ; CC BY-NC-ND 

[K - கொழும்பு வழியே ஒரு பயணம் (தொடர்கதை).docx](https://github.com/KaniyamFoundation/Ebooks/files/2872869/K.-.docx)
[kozhumbu vazhiye payanam - என்னுரை!.docx](https://github.com/KaniyamFoundation/Ebooks/files/2872870/kozhumbu.vazhiye.payanam.-.docx)

[KOZHUMBU VALIYE PAYANAM(1).pdf](https://github.com/KaniyamFoundation/Ebooks/files/2872865/KOZHUMBU.VALIYE.PAYANAM.1.pdf)

![front](https://user-images.githubusercontent.com/38220354/52911990-4ba26b80-32d1-11e9-92d7-a09df9bd2416.jpeg)
![bk](https://user-images.githubusercontent.com/38220354/52911991-4c3b0200-32d1-11e9-8ae4-04652f54bfe5.jpeg)

**Comment by rajiinperth** [comment]
https://archive.org/details/kozhumbu_vazhiye_payanam_6_inch

**Comment by gnuanwar** [comment]
@rajiinperth உரிமை CC BY-NC-SA 4.0  மாற்றவும் எழுத்து பிழைகளை சரி செய்யவும் @gurulenin @tshrinivasan புத்தகத்தை வெளியிடவேண்டாம்

**Comment by tshrinivasan** [comment]
எழுத்துப்பிழைகள் எவ்வளவு உள்ளன? அவற்றை நாம் சரி செய்வதில்லை. நூல் ஆசிரியர் தருவதை அப்படியே தான் வெளியிடுவோம்.

**Comment by gnuanwar** [comment]
@rajiinperth புத்தக முயற்ச்சி  gnu அன்வர் மின் அஞ்சல் gnuanwar@gmail.com என்பதை நூலில் சேர்க்கவும்

**Comment by rajiinperth** [comment]
@gnuanwar : மாற்றம் செய்து விட்டேன்.  சரிபார்க்கவும்
https://archive.org/details/backcover_201905

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/kozhumbu_vazhiyae_oru_payanam

இங்கே வெளியிட்டுள்ளோம்.
