### ISSUE TITLE
தமிழ் நாடக வரலாறும் சங்கரதாச சுவாமிகளும் - கட்டுரைகள் - அ. ச. ஞானசம்பந்தன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#195]
https://ta.wikisource.org/s/8ydb

உரிமை - Public Domain - CC0

**Comment by gurulenin** [comment]
![ssankar-dass](https://user-images.githubusercontent.com/15311390/57577092-10a57380-748d-11e9-8a95-421faa04d921.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/tamilnadagam6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/tamil_naadaga_varalarum_sankara_daasa_swamigalum

வெளியுட்டோம்.
