### ISSUE TITLE
வெற்றி முழக்கம் - நாவல் - நா. பார்த்தசாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#196]
https://ta.wikisource.org/s/8y1k

உரிமை - public domain - cc0

**Comment by rajiinperth** [comment]
Contents are organised for this book...Can anyone provide cover image ?

**Comment by gurulenin** [comment]
![vetri-muzhakkam](https://user-images.githubusercontent.com/15311390/57395098-db76f800-71e4-11e9-80a7-9e428e35353b.jpg)

**Comment by rajiinperth** [comment]
@gurulenin : நன்றி

**Comment by rajiinperth** [comment]
https://archive.org/details/VetriMulakkam6Inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/vetri_muzhakkam/


released here
