### ISSUE TITLE
அந்தமான் அழகு - ஏற்காடு இளங்கோ- அறிவியல் கட்டுரைகள்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#198]
[அந்தமான் அழகு.docx](https://github.com/KaniyamFoundation/Ebooks/files/3039436/default.docx)

ஆசிரியர் - ஏற்காடு இளங்கோ - yercaudelango@gmail.com

உரிமை : Creative Commons Attribution-NonCommercial-ShareAlike

**Comment by gkpriya246** [comment]
![andhaman_azhagu](https://user-images.githubusercontent.com/38214999/57179698-1b18a980-6e9e-11e9-83cc-5ec3563ac4da.jpg)

**Comment by gkpriya246** [comment]
http://freetamilebooks.com/ebooks/andaman_azhagu
Released here
