### ISSUE TITLE
நாட்டை உலுக்கும் ரபேல் பேர ஊழல் | எஸ். விஜயன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#199]
https://bookday.co.in/naatai-ulukkum-rafale-pera-oozhal-s-vijayan/

Get this book in CC-BY-NC or relevant license.

**Comment by tshrinivasan** [comment]
Added a request in bookday.co.in contact page to release this in CC license, 20 days ago.

**Comment by rbalogic** [comment]
@tshrinivasan I've talked the Author and the Publisher. Soon, will be adding the **CC-BY-SA** License to the book and we can release it under the Commons.

**Comment by rbalogic** [comment]
@tshrinivasan Attaching the PDF of the Book
[நாட்டை_உலுக்கும்_ரபேல்_பேர_ஊழல்.pdf](https://github.com/KaniyamFoundation/Ebooks/files/3121169/_._._._.pdf)

We need to add the License content to the PDF. Is that fine?

**Comment by tshrinivasan** [comment]
yes

**Comment by rbalogic** [comment]
@tshrinivasan Attaching the PDF with the Creative Commons License. The Books is ready to be released in Commons.

PDF here - [Rafale-Scam.pdf](https://github.com/KaniyamFoundation/Ebooks/files/3268516/Rafale-Scam.pdf)

**Comment by tshrinivasan** [comment]
@gurulenin இதை மின்னூலாக்கி வெளியிடுக.

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/naattai_ulukkum_rafale_pera_oozhal


வெளியிடப்பட்டது.
