### ISSUE TITLE
செல்வக் களஞ்சியமே - பாகம் 2

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#2]
https://drive.google.com/file/d/0ByVVWpATsHCaVFl1VUNPQmVBWUY5Z2tfWXV5WVZVQUdlT2k4/view

ரஞ்சனி நாராயணன்
ranjanidoraiswamy@gmail.com

**Comment by tshrinivasan** [comment]
![selva-kalanjiyame-2](https://user-images.githubusercontent.com/1268536/39084108-7f7220fe-458d-11e8-854a-9c77bdcec7da.jpg)

**Comment by rajiinperth** [comment]
kindly provide artist details

**Comment by tshrinivasan** [comment]
அட்டைப்படம் - த. சீனிவாசன் tshrinivasan@gmail.com

**Comment by rajiinperth** [comment]
okay shrini

**Comment by rajiinperth** [comment]
https://archive.org/details/SelvaKalanjiyamae6Inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/selva_kalanjiyamae_part_2


வெளியிடப்பட்டது..
