### ISSUE TITLE
ஸ்பீனிக்ஸ் பெண்கள் - கட்டுரைகள் - கார்த்திகா சுந்தர்ராஜ்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#203]
ஸ்பீனிக்ஸ் பெண்கள்
கார்த்திகா சுந்தர்ராஜ் 
karthikapandian2221997@gmail.com

உரிமை : Creative Commons Attribution-NonCommercial 4.0 International

உரிமை – கிரியேட்டிவ் காமன்ஸ். எல்லாரும் படிக்கலாம், பகிரலாம்.
[ஸ்பீனிக்ஸ் பெண்கள்.docx](https://github.com/KaniyamFoundation/Ebooks/files/3084127/default.docx)

**Comment by gkpriya246** [comment]
![COVER6](https://user-images.githubusercontent.com/38214999/57387131-5fc07f80-71d3-11e9-8413-6fa5336582e8.jpg)
அட்டைப்படம் : க சாந்திபிரியா
மின்னஞ்சல் : gkpriya246@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/phoenixpengal_6_inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/phoenix_pengal

published here.
