### ISSUE TITLE
தமிழியல் ஆய்வுகள்  தமிழ்நேயத்தின் பார்வை  -மின்நூல்

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#205]
தமிழியல் ஆய்வுகள்  தமிழ்நேயத்தின் பார்வை 

ஆசிரியர்; இர.ஜோதிமீனா 

உரிமை ; CC BY-SA 4.0

author correspondence & acquisition of creations gnuanwar

மின் அஞ்சல் gnuanwar@gmail.com
[முன்னுரை.docx](https://github.com/KaniyamFoundation/Ebooks/files/3100943/default.docx)

**Comment by gurulenin** [comment]
![tamil-literature](https://user-images.githubusercontent.com/15311390/58142769-04c46900-7c66-11e9-914a-017939da5d9e.jpg)

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/tamizhiyal_aaivugal_tamizhneyathin_paarvai/

வெளியிடப்பட்டது.
