### ISSUE TITLE
மர்பி விதிகள் - நகைச்சுவை - சுப. இரத்தினகிரி 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#208]
ஆசிரியர் - சுப. இரத்தினகிரி
srathinagiri@gmail.com

உரிமை - Creative Commons Attribution 4.0 International License

[மர்பி விதிகள்.docx](https://github.com/KaniyamFoundation/Ebooks/files/3177257/default.docx)

**Comment by thesathyan** [comment]
![மர்பி விதிகள் - நகைச்சுவை - சுப](https://user-images.githubusercontent.com/3577373/63693819-a85b8180-c832-11e9-9c20-6927fbc60da5.jpg)

Sathya
experimentsofme@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/murphysvithigal6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/murphysvithigal/
