### ISSUE TITLE
கடற்கரைச் சுவடுகள் - கவிதைகள் – நவீன் ராஜ் தங்கவேல்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#211]
மின்னூல் 4 வடிவங்களில் இங்கே உள்ளது.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/freetamilebooksforum/dnrLk3O-S5w/zRv5ih51AQAJ

நூலின் பெயர் - கடற்கரைச் சுவடுகள்
உரிமை - Creative Commons Attribution-ShareAlike 4.0 International License

அட்டைப்படம், மின்னூலாக்கம் - 
நவீன் ராஜ் தங்கவேல் –naveenrajthangavel@gmail.com

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/kadarkarai_suvadugal

published
