### ISSUE TITLE
புலவர் ஞானசம்பந்தம் புத்தகங்கள் வலைபூ கி.கா உரிமை அறிவித்தல்

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#212]
புதுவை lug அமைப்பின் தன்ஆர்வலர் ராகுல்,பிரசாந்த் இருவரும் புலவர் ஞானசம்பந்தம் அவர்கள்ஐ இன்று அவரது இல்லத்தில் சந்தித்து creative commons,freetamilebooks.com,கணியம் அறக்ட்டளை நோக்கம்,பணிகள் செய்ல்பாடுகள்  பற்றிய விரிவான விளக்கம் கொடுக்கபட்டு அவரின்வலை பூ [](http://sgnanasambandan.blogspot.com/?m=0 ) கி.கா உரிமையில் ஒப்புதல் கொடுத்தார் 

1. தமிழைதிருத்தமாக எழுதுவது 
2. மாப்பசான் சிறு கதைகள்
3. மறைந்த நாகரிகங்கள்
4. பிரஞ்சு இலக்கிய வரலாறு
5. லத்தீன் இலக்கியவரலாறு
6. மறைந்த நாகரிகங்கள்

ஆகியநூல்களை நமது freetamilebooks.com மின் நூலாக வெளியிட அனுமதி அளித்தார்

**Comment by tshrinivasan** [comment]
Here is a note about this.
https://connect.fshm.in/notice/9j1b50tbPK5K14a9ce

**Comment by tshrinivasan** [comment]
@gnuanwar close this issue and create a new issue for this here
https://github.com/KaniyamFoundation/CreativeCommonsAnnouncements/issues
