### ISSUE TITLE
மார்கழித் திங்கள் மதி நிறைந்த நன்னாள் - கீதா சாம்பசிவம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#213]
கீதா சாம்பசிவம்
geethasmbsvm6@gmail.com

கோலங்கள் - C.M. உதயன் udhayan.chn@gmail.com 

creative commons attribution Non Commercial 4.0 international license

**Comment by tshrinivasan** [comment]
[மார்கழித் திங்கள் மதி நிறைந்த நன்னாள்.docx](https://github.com/KaniyamFoundation/Ebooks/files/3213447/default.docx)

**Comment by gurulenin** [comment]
![margali](https://user-images.githubusercontent.com/15311390/60399287-efedc600-9b7f-11e9-9c0e-7c783b483b6a.jpg)

**Comment by tshrinivasan** [comment]
@gurulenin please release this soon.

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/margazhi_thingal_mathi_niraindha_nannaal/

released here
