### ISSUE TITLE
மாவீரன் சிவாஜி காவித் தலைவன் அல்ல காவியத் தலைவன்

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#215]
ஆசிரியர்         : ஆங்கிலம் வழி தமிழில்செ. நடேசன்

உரிமை            : CC BY-NC-SA 4.0

பிழை திருத்தம் :   சிவந்தன் 
                            மின் அஞ்சல் sivanthanv@gmail.com

Author Correspondence & Acquisition of Creations Gnu Anwar
![image](https://user-images.githubusercontent.com/38220354/58813860-41b73500-8642-11e9-8371-700dcc52b197.png)

gnuanwar@gmail.com

ஆசிரியர் படம் 

![image](https://user-images.githubusercontent.com/38220354/58813719-fac93f80-8641-11e9-8ce7-8c22f657a0db.png)

அட்டை படம்

![image](https://user-images.githubusercontent.com/38220354/58813899-55fb3200-8642-11e9-9cef-0a6cad3b1e84.png)

**Comment by tshrinivasan** [comment]
>
> நூலின் ஆவணத்தை இணைக்கவும்.


நன்றி


>
>
>

**Comment by gnuanwar** [comment]
ஆவணத்தில் ஆசிரியர் குறிப்பு கிடைத்தவுடன் இணைக்கபடும்

**Comment by gnuanwar** [comment]
[மாவீரன் சிவாஜி காவித்தலைவன் அல்ல காவியத்தலைவன்.docx](https://github.com/KaniyamFoundation/Ebooks/files/3256355/default.docx)
@rajiinperth மின்நூலாக்கவும்

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/sivaji_kaaviya_thalaivan


வெளியிடப்பட்டது.
