### ISSUE TITLE
மக்கள் சட்டம் இணையதளம்- மின் நூல் உருவாக்கம்

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#217]
http://makkal-sattam.blogspot.com/

காப்புரிமை 

உரிமை துறப்பு
மக்கள் பிரதி / COPY LEFT

![image](https://user-images.githubusercontent.com/38220354/59195233-0b7d3680-8ba9-11e9-9820-d7aabf8d00b4.png)

பதிப்பாளரிடமோ, ஆசிரியரிடமோ எந்தவித முன் அனுமதியும் இன்றி யாரும் இத்தொகுப்பின் பகுதிகளை பயன்படுத்தலாம். பிரதி எடுக்கலாம். மறுபதிப்புச் செய்யலாம். இது அனைவருக்குமான பிரதி.

(அவ்வாறு பயன்படுத்துவோர், ஆசிரியர் மற்றும் பதிப்பாளரின் பெயரை குறிப்பிடுவதும், அது குறித்து தகவல் தெரிவிப்பதும் மேலும்  பதிவுகளை உள்ளிட பயன்படும்)

COPYLEFT OPENSOURCE TEXT. ANYONE CAN REPUBLISH, DISTRIBUTE WITHOUT PRIOR PERMISSION FROM THE AUTHOR & PUBLISHER.

(ACKNOWLEDGING & NOTICING THE AUTHOR AND PUBLISHER WILL BE APPRECIATED. IT WILL HELP US TO PUT MORE USEFUL ARTICLES)

"ALL RIGHTS REVERSED!"

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/makkal_sattam_1
