### ISSUE TITLE
மார்க்சியமும் தமிழ் இலக்கியமும் - கோவை ஞானி 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#218]
ஆசிரியர் கோவை ஞானி

உரிமை CC-BY-SA 4.0

Author correspondence & acquisition of Creations Gnuஅன்வர்

மெய்ப்பு @Tharagavaskar 

ஒளிவருடல் குரு லெனின்

![marx-tamil-literature](https://user-images.githubusercontent.com/38220354/59450238-696a8200-8e26-11e9-8c26-9370a9f579e1.jpg)

https://github.com/KaniyamFoundation/Proofread-Works/files/3285803/marx-tamil-literature.docx

**Comment by gurulenin** [comment]
![marx-tamil](https://user-images.githubusercontent.com/15311390/59481022-4c629d00-8e80-11e9-91e5-43f91e28b265.jpg)

**Comment by gurulenin** [comment]
![marx-tamil](https://user-images.githubusercontent.com/15311390/59481138-c135d700-8e80-11e9-8dfa-638fd7647c1b.jpg)

**Comment by tshrinivasan** [comment]
>
>
>
> ஆசிரியர் பெயர்


கோவை ஞானி

என்றே அட்டைப்படத்தில் சேர்க்கவும்.

நன்றி

**Comment by gnuanwar** [comment]
@tshrinivasan convert this book to mp3 to send author

**Comment by gurulenin** [comment]
![marx-tamil](https://user-images.githubusercontent.com/15311390/59525029-e7945a80-8ef2-11e9-9895-de3bac8174c3.jpg)

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/marx_and_tamil_literature

வெளியிடப்பட்டது..
