### ISSUE TITLE
இன்றைய கண்ணாடியும் நாளைய முகங்களும்-களந்தை பீர்முகமது

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#220]
ஆசிரியர் களந்தை பீர்முகமது

தலைப்பு இன்றைய கண்ணாடியும் நாளைய முகங்களும்

உரிமை  ; BY-NC-ND international 4.0

Author correspondence & acquisition of Creations Gnuஅன்வர்

**Comment by thesathyan** [comment]
![இன்றைய கண்ணாடியும் நாளைய முகங்களும்-களந்தை பீர்முகமது](https://user-images.githubusercontent.com/3577373/63693738-764a1f80-c832-11e9-9e77-c1cba38e3ec1.jpg)

Sathya
experimentsofme@gmail.com

**Comment by gnuanwar** [comment]
@gnuanwar remove கணியம் வெளீயிடு

**Comment by tshrinivasan** [comment]
https://freetamilebooks.com/ebooks/kannadiyummugangalum/
released here
