### ISSUE TITLE
பிறைக்கூத்து-களந்தை பீர்முகமது

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#221]
ஆசிரியர் களந்தை பீர்முகமது

தலைப்பு பிறைக்கூத்து

உரிமை  ; BY-NC-ND international 4.0

Author correspondence & acquisition of Creations Gnu அன்வர்

**Comment by thesathyan** [comment]
![பிறைக்கூத்து-களந்தை பீர்முகமது](https://user-images.githubusercontent.com/3577373/63693660-4dc22580-c832-11e9-8bed-718c018c62e5.jpg)

Sathya
experimentsofme@gmail.com

**Comment by gnuanwar** [comment]
@gurulenin remove கணியம் வெளீயிடு

**Comment by gnuanwar** [comment]
@gurulenin remove கணியம் வெளீயிடு

**Comment by alauvdheen** [comment]
#255 duplicate thread
@gnuanwar 
@tshrinivasan
