### ISSUE TITLE
சுழல்-களந்தை பீர் முகமது

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#222]
ஆசிரியர் களந்தை பீர்முகமது

தலைப்பு சுழல்

உரிமை  ; BY-NC-ND international 4.0

Author correspondence & acquisition of Creations Gnuஅன்வர்

**Comment by thesathyan** [comment]
![சுழல்-களந்தை பீர் முகமது](https://user-images.githubusercontent.com/3577373/63694141-61ba5700-c833-11e9-9cfc-30a80f7d9c36.jpg)

Sathya
experimentsofme@gmail.com

**Comment by alauvdheen** [comment]
thread is closed
@tshrinivasan

**Comment by tshrinivasan** [comment]
duplicate of #270
