### ISSUE TITLE
சலாம் இஸ்லாம்-களந்தை பீர் முகமது

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#224]
தொகுப்பு ஆசிரியர் களந்தை பீர்முகமது

தலைப்பு சலாம் இஸ்லாம்

உரிமை  ; BY-NC-ND international 4.0

Author correspondence & acquisition of Creations Gnuஅன்வர்

**Comment by alauvdheen** [comment]
#264 same thread
@gnuanwar 
@tshrinivasan
