### ISSUE TITLE
புற்று நோயை வெற்றிகொள்ள-செ.நடேசன்

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#225]
புற்று நோயை வெற்றிகொள்ள

ஆசிரியர் செ.நடேசன்

உரிமை -CC-BY-NC-ND international 4.0

Author correspondence & acquisition of Creations Gnuஅன்வர்

[புற்று நோயை வெற்றிகொள்ள...docx](https://github.com/KaniyamFoundation/Ebooks/files/3294370/default.docx)

![image](https://user-images.githubusercontent.com/38220354/59562419-1ffa7c80-904a-11e9-8fa3-1e5b6b5d1f94.png)

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/putru_noyai_vetri_kolla


வெளியிட்டோம்..

**Comment by gnuanwar** [comment]
நன்றி
