### ISSUE TITLE
ஆதிவாசி மறைந்த வரலாறு

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#229]
http://tamildigitallibrary.in/book-detail.php?id=jZY9lup2kZl6TuXGlZQdjZt8kux0&tag=%E0%AE%86%E0%AE%A4%E0%AE%BF%E0%AE%B5%E0%AE%BE%E0%AE%9A%E0%AE%BF%E0%AE%95%E0%AE%B3%E0%AE%BF%E0%AE%A9%E0%AF%8D%20%E0%AE%AE%E0%AE%B1%E0%AF%88%E0%AE%A8%E0%AF%8D%E0%AE%A4%20%E0%AE%B5%E0%AE%B0%E0%AE%B2%E0%AE%BE%E0%AE%B1%E0%AF%81#book1/

https://github.com/KaniyamFoundation/Proofread-Works/files/3295269/new.advasigalin.maraithavaralaru.proofing.current.docx

**Comment by tshrinivasan** [comment]
பின்வரும் விவரங்களை மின்னூலில் சேர்த்து வெளியிடுக.

உரிமை - CC-BY
Creative Commons Attribution


மின்னூல் பெறுகை - அன்வர் - gnuanwar@gmail.com

Scan - லெனின் குருசாமி - guruleninn@gmail.com

OCR - எழுத்துணரி - அன்வர் - gnuanwar@gmail.com

மெய்ப்பு பார்த்தல் - தாரா - thara.nakshatraa@gmail.com

அட்டைப்படம் - பெயர் - மின்னஞ்சல்

மின்னூலாக்கம் - பெயர் - மின்னஞ்சல்

**Comment by gurulenin** [comment]
![adivasi-extinction](https://user-images.githubusercontent.com/15311390/59610959-118a8e80-9138-11e9-83cf-9d0489e6098c.jpg)

**Comment by gnuanwar** [comment]
அட்டை படத்தை இந்த விக்கி கமண்சில் உள்ள படத்தை எடுத்து ஒரு புதிய படத்தை கருப்பு வெள்ளையில் வரைந்து தரவும் https://commons.wikimedia.org/wiki/File:Photograph_of_two_men_and_two_women_of_the_Malaiyali_tribe_in_the_Shevaroy_Hills_in_Tamil_Nadu_-_1860.jpg

**Comment by tshrinivasan** [comment]
@gnuanwar Please add these kind of custom requirement for cover images,
when uploading the book info itself.
so that the efforts wont be wasted.

**Comment by gnuanwar** [comment]
ok

**Comment by tshrinivasan** [comment]
Will work on this later after fixing the issues with word doc file.
