### ISSUE TITLE
ரூபி நண்பன் - கணினி அறிவியல் - டக் ரைட், ஆடம் ஸ்டார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#232]
ODT file
https://drive.google.com/file/d/1P5TfZDbDXEHhx7JzjyiqAcYlIaPWtSlf/view?usp=sharing

PDF file
https://drive.google.com/file/d/1MNKhm4IzsvTHWmIlR_-Gqoy3G4gV4zFa/view?usp=sharing

உரிமை - CC-By-NC

ஆங்கில மூலம் - 

https://leanpub.com/rubykin

http://rubykin.com/

**Comment by gurulenin** [comment]
![ruby](https://user-images.githubusercontent.com/15311390/60286133-bf621e00-992c-11e9-82b4-e3793889e250.jpg)

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/ruby_nanban


released
