### ISSUE TITLE
இலங்கையில் ஏற்பட்டுள்ளது அரசியல் மாற்றமல்ல.. - நேர்காணல்கள் - அ.தமிழ்ச்செல்வன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#236]
https://docs.google.com/viewer?a=v&pid=forums&srcid=MTAwODYwNjQ2MTUzNjY0NDE5MDIBMDk5MDc2NzcxOTE3MjU0NDg2NDgBM1EzZlMwS2RBQUFKATAuMQEBdjI&authuser=0

அ.தமிழ்ச்செல்வன்
மின்னஞ்சல் -a.tamilselvan42@gmail,com
வகை- நேர்காணல்
உரிமை -Creative Commons Attribution-NonCommercial (CC-BY-NC)

**Comment by meena-sundaram** [comment]
![Ilangai Arasiyal](https://user-images.githubusercontent.com/44741122/63638713-81be0f00-c6a9-11e9-9ac9-6e8df5b46186.jpg)



அட்டைப்படம் - B. மீனா meenabalasundaram@gmail.com

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/ilangaiyul_yerpatulathu_arasiyal_maatramalla
