### ISSUE TITLE
ஆரியப்பார்ப்பனரின் அளவிறந்த கொட்டங்கள் - பாவலரேறு பெருஞ்சித்திரனார்

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#237]
https://ta.wikisource.org/s/8yz7

**Comment by gurulenin** [comment]
![arya](https://user-images.githubusercontent.com/15311390/79128151-aabe1c00-7dc0-11ea-9ce0-9cce9f66691d.jpg)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/aryapaarpanarin_alavirantha_kottangal
