### ISSUE TITLE
சேதுபதி மன்னர் வரலாறு - எஸ். எம். கமால்

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#239]
https://ta.wikisource.org/s/8yyw

**Comment by thesathyan** [comment]
![சேதுபதி மன்னர் வரலாறு - எஸ்](https://user-images.githubusercontent.com/3577373/63693595-1d7a8700-c832-11e9-8d83-a7e655658e97.jpg)

Sathya
experimentsofme@gmail.com

**Comment by thesathyan** [comment]
![சேதுபதி மன்னர் வரலாறு - எஸ்](https://user-images.githubusercontent.com/3577373/63694570-5f0c3180-c834-11e9-86da-dc6b354d9f54.jpg)

Sathya
experimentsofme@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/sethupathimannar6inch

**Comment by nithyadurai87** [comment]
released here
http://freetamilebooks.com/ebooks/sethupathimannar/
