### ISSUE TITLE
வல்லிக்கண்ணன் கதைகள் (இரு பாகங்களாக) - வல்லிக்கண்ணன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#24]
http://projectmadurai.org/pm_etexts/utf8/pmuni0579_01.html http://projectmadurai.org/pm_etexts/utf8/pmuni0579_02.html

**Comment by gurulenin** [comment]
![vallikkannan](https://user-images.githubusercontent.com/15311390/39080626-08b06684-4550-11e8-9cad-cbce1eaccb17.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Vallikkannan_Stories-2018-10-01-08-22-27

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Vallikkannan_Stories
