### ISSUE TITLE
மிஸ்டர் விக்கிரமாதித்தன் கதைகள் - விந்தன்

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#240]
https://ta.wikisource.org/s/8zqm

**Comment by thesathyan** [comment]
![மிஸ்டர் விக்கிரமாதித்தன் கதைகள் - விந்தன்](https://user-images.githubusercontent.com/3577373/63693528-f754e700-c831-11e9-857d-eac8a2c916a2.jpg)

Sathya
experimentsofme@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/vikramathithankathaigal6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/VikramathithanKathaigal
