### ISSUE TITLE
சீர்மிகு சிவகங்கைச் சீமை - எஸ். எம். கமால்

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#241]
https://ta.wikisource.org/s/911d

**Comment by thesathyan** [comment]
![சீர்மிகு சிவகங்கைச் சீமை - எஸ்](https://user-images.githubusercontent.com/3577373/63693490-d7252800-c831-11e9-8174-ce781055b3d1.jpg)

Sathya
experimentsofme@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/sivagangaiseemai

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/SivagangaiSeemai
