### ISSUE TITLE
இந்தியப் பெருங்கடல் - பேரா. அ. கி. மூர்த்தி

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#242]
https://ta.wikisource.org/s/8yt4

**Comment by meena-sundaram** [comment]
![Indiya Perumgadal](https://user-images.githubusercontent.com/44741122/63635676-9c30c200-c682-11e9-9408-8bc5af5a02f1.jpg)

அட்டைப்படம் - மீனா meenabalasundaram@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/indianocean6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/indian_ocean
