### ISSUE TITLE
யார் இந்த நாடோடிகள் - பிலோ இருதயநாத்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#244]
PDF
https://archive.org/download/philo_irudhayanath_books_scanned/yaar_intha_nadodigal.pdf

**Comment by gnuanwar** [comment]
@gurulenin அட்டை படத்தில் உள்ள பெண் முகம் வேண்டும் அதனை வைத்து புதிய படத்தை தரவும்

![yaar_intha_nadodigal_cover](https://user-images.githubusercontent.com/38220354/61127678-95ccf900-a4cd-11e9-8616-60e870e9e446.jpg)

**Comment by gurulenin** [comment]
![nadodigal](https://user-images.githubusercontent.com/15311390/61394332-7c1e1e00-a8e0-11e9-9869-ea8553e0c797.jpg)

**Comment by gnuanwar** [comment]
@gurulenin copy the source background color and girl photo surrounding 

title will like this                                 யார் இந்த
                                                         நாடோடிகள்?

**Comment by tshrinivasan** [comment]
@gnuanwar I think the given image is fine. 

Let us not add more requirements for the free cover images.

**Comment by gnuanwar** [comment]
@tshrinivasan @gurulenin @Tharagavaskar பிலோவின் அனைத்து நூல்களுக்கும் எந்த பணியையும் செய்ய வேண்டாம்

**Comment by tshrinivasan** [comment]
https://github.com/KaniyamFoundation/CreativeCommonsAnnouncements/issues/16#issuecomment-513234321

Check here.

Their family member is fine to release in CC-BY-NC ie non commercial.

But we require in CC-BY-SA so that we can do all the scan,OCR,proofread works.

We have to wait for some more time and discuss with them.

Hence, we pause the proofread works for philo books.

-- 
Regards,
T.Shrinivasan


My Life with GNU/Linux : http://goinggnu.wordpress.com
Free E-Magazine on Free Open Source Software in Tamil : http://kaniyam.com

Get Free Tamil Ebooks for Android, iOS, Kindle, Computer :
http://FreeTamilEbooks.com

**Comment by gnuanwar** [comment]
IAM only suggesting re arrange title and backround

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
07/21/19,
10:27:10 PM
