### ISSUE TITLE
ஆதி மருத்துவர் சவர தொழிலாராக்கபட்ட வரலாறு-கோ ரகுபதி

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#246]
[adimar Copy.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3358723/adimar.Copy.pdf)

[ahhimar.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3355108/ahhimar.docx)

**Comment by gnuanwar** [comment]
![image](https://user-images.githubusercontent.com/38220354/61621623-e93f0400-ac90-11e9-9d8d-12f813fcf651.png)

print book cover image remix or recreate the cover image according to the e book title

**Comment by AzharAchuu** [comment]
how can i submit my cover page for (ஆதி மருத்துவர் சவர தொழிலாராக்கபட்ட வரலாறு)

**Comment by AzharAchuu** [comment]
![Image1](https://user-images.githubusercontent.com/53699309/62795808-2e6a8f00-baf5-11e9-9924-b70ff7f35506.jpg)

**Comment by AzharAchuu** [comment]
![Image2](https://user-images.githubusercontent.com/53699309/62795846-480bd680-baf5-11e9-98f4-f201d3322328.jpg)

**Comment by AzharAchuu** [comment]
![Image3](https://user-images.githubusercontent.com/53699309/62795872-58bc4c80-baf5-11e9-936d-9cdfa3609a51.jpg)

**Comment by AzharAchuu** [comment]
![Image4](https://user-images.githubusercontent.com/53699309/62795894-68d42c00-baf5-11e9-8966-0278c79bbb0e.jpg)

**Comment by AzharAchuu** [comment]
![Image5](https://user-images.githubusercontent.com/53699309/62795927-7b4e6580-baf5-11e9-9038-71f78ed36794.jpg)

**Comment by AzharAchuu** [comment]
hai i am azhar 
i am a editor for these 5 pics

**Comment by tshrinivasan** [comment]
Thanks @AzharAchuu Picked one suitable image.

Contribute to other books too.

One cover image is fine. No need to add more then one cover image.

Thanks.

**Comment by gnuanwar** [comment]
![IMAGE 2(1)](https://user-images.githubusercontent.com/38220354/62834666-53820d80-bc6d-11e9-94ad-96bacece52d0.jpg)

நூலின் ஆசிரியர் இந்த படத்தை போட வேண்டும் விருப்பம் தெறிவித்துள்ளார் 

படத்தை வரைந்தவர் அசார்
மின் அஞ்சல் azarudeena163@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/aathimaruthuvar

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/AathiMaruthuvar
