### ISSUE TITLE
அகிம்சா மூர்த்தி அமேரிக்கா

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#248]
[compressedagimsamoorthy-america_full.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3266838/compressedagimsamoorthy-america_full.docx)

[aimsa muthy america.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3295940/aimsa.muthy.america.pdf)

licence CC-BY-SA
@Tharagavaskar do proof reading

**Comment by Tharagavaskar** [comment]
படங்கள் சேர்க்கப்பட்டுள்ளது.
[அகிம்சாமூர்த்தி.docx](https://github.com/KaniyamFoundation/Ebooks/files/3432008/default.docx)

**Comment by thesathyan** [comment]
@tshrinivasan @gnuanwar Author name?

**Comment by gnuanwar** [comment]
பாமரன்

**Comment by thesathyan** [comment]
![அகிம்சா மூர்த்தி அமேரிக்கா - பாமரன்](https://user-images.githubusercontent.com/3577373/64002172-0d5ef200-cb27-11e9-9dc9-3b9127470bc8.jpg)

Sathya
experimentsofme@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/ahimsamamerica6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/akimsamoorthy_america
