### ISSUE TITLE
ராணி மங்கம்மாள் - தீபம் நா. பார்த்தசாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#25]
http://projectmadurai.org/pm_etexts/utf8/pmuni0576.html

**Comment by gurulenin** [comment]
![rani-mangammal](https://user-images.githubusercontent.com/15311390/38919552-855e4f32-430e-11e8-976d-98b361677dc6.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Raani_Mangammal-2018-06-24-19-21-37

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/raani_mangammal/

released here
