### ISSUE TITLE
வாழ்வும் பவுத்தமும்

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#252]
https://archive.org/download/vaazhvum_bowthamum/vaazhvum_bowthamum.pdf

**Comment by gnuanwar** [comment]
@Tharagavaskar have finished proof reading

**Comment by gurulenin** [comment]
![buddha](https://user-images.githubusercontent.com/15311390/62846255-40625280-bcec-11e9-943d-088950e8d5e6.jpg)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/vaazhvum_bowthamum
