### ISSUE TITLE
வள்ளுவரின் அறவியலும் அழகியலும் - கோவை ஞானி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#253]
PDF is here
https://archive.org/download/kovai_gnani_books_scanned/valluvarin-araviyalum-azhakiyalum-gnani.pdf

**Comment by gurulenin** [comment]
![valluvar-gnani](https://user-images.githubusercontent.com/15311390/62845987-40f9e980-bcea-11e9-83f2-7ae286c87a88.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/valluvarariviyal6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/valluvarin_araviyalum_azhagiyalum
