### ISSUE TITLE
எழுத்து நாடகம் சினிமா சோதனைகளும் சாதனைகளும்   ஒரு வரலாற்றுப் பதிவு - எஸ். சுவாமிநாதன் 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#254]
காப்புரிமை CC BY SA

[all_text_for_TM34734.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3489907/all_text_for_TM34734.pdf.txt)
[TM34734.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3489908/TM34734.pdf)

**Comment by gnuanwar** [comment]
@gurulenin take pdf cover image  and crop the image

**Comment by thesathyan** [comment]
![எழுத்து நாடகம் சினிமா சோதனைகளும் சாதனைகளும் ஒரு வரலாற்றுப் பதிவு - எஸ்](https://user-images.githubusercontent.com/3577373/63693383-8dd4d880-c831-11e9-95b1-26b7a5c29be0.jpg)

Sathya
experimentsofme@gmail.com

**Comment by gnuanwar** [comment]
@gurulenin remove கணியம் வெளீயிடு

**Comment by rajiinperth** [comment]
https://archive.org/details/eluthunadagamcinema6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/EluthuNadagamCinema
