### ISSUE TITLE
தமிழக இஸ்லாமிய ஃபக்கீர்கள்-முனைவர் தே ஆக்னஸ் ஷர்மிலி 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#256]
உரிமை CC BY SA 
[tamil Agnes_Sharmeeli_phd_Thesis.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3439373/tamil.Agnes_Sharmeeli_phd_Thesis.pdf)

@Tharagavaskar i will upload the OCR output tomorrow

**Comment by thesathyan** [comment]
![தமிழக இஸ்லாமிய ஃபக்கீர்கள்-முனைவர் தே ஆக்னஸ் ஷர்மிலி](https://user-images.githubusercontent.com/3577373/63636297-0a798280-c68b-11e9-9291-544b3d095f2e.jpg)

Sathya
experimentsofme@gmail.com

**Comment by alauvdheen** [comment]
assign me sir for make a ebook
@tshrinivasan

**Comment by tshrinivasan** [comment]
I think you can assign yourself.

Check and reply here

**Comment by alauvdheen** [comment]
can't assign me sir @tshrinivasan

**Comment by alauvdheen** [comment]
https://archive.org/details/Tamil_islamiya_Fakirkal-2020-03-25-22-17-44
@tshrinivasan 
Completed sir

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - http://freetamilebooks.com/ebooks/Tamil_islamiya_Fakirkal
