### ISSUE TITLE
மார்க்ஸியமும்_புரட்சி_எழுச்சியும்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#257]
https://archive.org/download/russia_books_tamil/%E0%AE%AE%E0%AE%BE%E0%AE%B0%E0%AF%8D%E0%AE%95%E0%AF%8D%E0%AE%B8%E0%AE%BF%E0%AE%AF%E0%AE%AE%E0%AF%81%E0%AE%AE%E0%AF%8D_%E0%AE%AA%E0%AF%81%E0%AE%B0%E0%AE%9F%E0%AF%8D%E0%AE%9A%E0%AE%BF_%E0%AE%8E%E0%AE%B4%E0%AF%81%E0%AE%9A%E0%AF%8D%E0%AE%9A%E0%AE%BF%E0%AE%AF%E0%AF%81%E0%AE%AE%E0%AF%8D.pdf

**Comment by gurulenin** [comment]
![marx-revolution](https://user-images.githubusercontent.com/15311390/63316767-bccce500-c32d-11e9-9f01-8acfe1e215ba.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/markshiyam6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/marxiamum_puratchi-ezhuchiyum
