### ISSUE TITLE
முகம் காட்டச் சொல்லாதீர் - கவிதைகள் - வெங்கட் நாகராஜ்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#258]
https://drive.google.com/open?id=12p1yx8VdkjICQ0OHWDJDSumiFwEgmnpn

முகம் காட்டச் சொல்லாதீர்
[புகைப்படக் கவிதைகள் தொகுப்பு]

வெங்கட் நாகராஜ்
venkatnagaraj@gmail.com

மின்னூல் வெளியீடு
www.freetamilebooks.com

மின்னூலாக்கம் மற்றும் அட்டைப்படம்:

வெங்கட் நாகராஜ்
venkatnagaraj@gmail.com

உரிமை : Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 
கிரியேட்டிவ் காமன்ஸ். எல்லாரும் படிக்கலாம், பகிரலாம்.

**Comment by rajiinperth** [comment]
https://archive.org/details/mugamkaatacholladheer6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/MugamKaataCholladheer
