### ISSUE TITLE
கலைஞரின் சரித்திரம் - வாழ்க்கை வரலாறு - கொல்லால் எச். ஜோஸ்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#259]
கலைஞரின் சரித்திரம்

கொல்லால் எச். ஜோஸ்

மின்னஞ்சல் -joseharichandran@gmail.com

வகை – வரலாறு

அட்டைப்படம் – முஹம்மது நயீம் (வேட்டை மின்னிதழ்)

மின்னஞ்சல் – vettai007@yahoo.com

உரிமை  Creative Commons Attribution Non Commerical No derivatives

[கலைஞரின் சரித்திரம் மின்நூல்.docx](https://github.com/KaniyamFoundation/Ebooks/files/3514467/default.docx)

**Comment by tshrinivasan** [comment]
![WhatsApp Image 2019-08-16 at 10 17 48 PM](https://user-images.githubusercontent.com/1268536/63243132-4372bb00-c277-11e9-83c7-70ce0bf12088.jpeg)

**Comment by rajiinperth** [comment]
https://archive.org/details/kalaignarsarithram6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/kalaingarin_charithiram
