### ISSUE TITLE
ஒரு மாமரமும் மரங்கொத்திப் பறவைகளும் - சு. சமுத்திரம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#26]
http://projectmadurai.org/pm_etexts/utf8/pmuni0572.html

**Comment by gurulenin** [comment]
![maamaram](https://user-images.githubusercontent.com/15311390/38919450-3e12ca04-430e-11e8-93ab-2598ace05f29.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Oru_Maamaramum_Marangkothi_Paravaigalum-2018-06-23-06-43-37

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/oru_maamaramum_marangkothi_paravaigalum/

released here
