### ISSUE TITLE
நீட்ச்சி-பா ரவி 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#260]
[TM34735.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3489768/TM34735.pdf)
காப்புரிமை CC-BY-SA 

[all_text_for_TM34735.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3507985/all_text_for_TM34735.pdf.txt)

**Comment by Tharagavaskar** [comment]
[நீட்சி.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3518955/default.docx)
proof read finished

**Comment by thesathyan** [comment]
![நீட்ச்சி-பா ரவி](https://user-images.githubusercontent.com/3577373/63636273-e74ed300-c68a-11e9-83f4-7049b4d8a4ee.jpg)

Sathya
experimentsofme@gmail.com

**Comment by tshrinivasan** [comment]
![neetchi](https://user-images.githubusercontent.com/1268536/69238152-47d3aa80-0bbd-11ea-9f22-14496c48102f.jpg)

use this cover image.

**Comment by tshrinivasan** [comment]
அட்டைப்படம் - கே.ஆர். இளவேனில்

**Comment by rajiinperth** [comment]
https://archive.org/details/Neetchi

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/Neetchi

**Comment by tshrinivasan** [comment]
@rajarethinam0 

The book name is நீட்சி
Not நீட்ச்சி

Can you fix this and recreate ebook?

@gnuanwar Please be careful on giving the correct book names everywhere.

Even a single mistake leads to rework.

**Comment by rajiinperth** [comment]
Okay...Sure

**Comment by rajiinperth** [comment]
https://archive.org/details/Netchi

**Comment by gnuanwar** [comment]
> @rajarethinam0
> 
> The book name is நீட்சி
> Not நீட்ச்சி
> 
> Can you fix this and recreate ebook?
> 
> @gnuanwar Please be careful on giving the correct book names everywhere.
> 
> Even a single mistake leads to rework.

ok

**Comment by gnuanwar** [comment]
@rajiinperth give the licence detail CC BY SA IN archive

**Comment by rajiinperth** [comment]
@gnuanwar : Where i have to give the license details in archive ?
I always give the license information inside the book

**Comment by gnuanwar** [comment]
I wil send the example

**Comment by tshrinivasan** [comment]
>
>
> Wait.


I have to fix this in archive upload script.

Will fix later.

**Comment by rajiinperth** [comment]
okay

**Comment by gnuanwar** [comment]
https://archive.org/details/MLKDream

Check this link in this usage given public domain logo same like this
change cc licence according to book

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/netchi/
