### ISSUE TITLE
தாவிப் பாயும் தங்கக் குதிரை - சிறுவர் கதை - பாவலர் நாரா. நாச்சியப்பன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#261]
https://ta.wikisource.org/s/93om

உரிமை - Public Domain - CC0

**Comment by thesathyan** [comment]
![தாவிப் பாயும் தங்கக் குதிரை - சிறுவர் கதை - பாவலர் நாரா](https://user-images.githubusercontent.com/3577373/63636263-d0a87c00-c68a-11e9-99a7-1a610fe81e59.jpg)

Sathya
experimentsofme@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/thangakuthirai_6_inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/thaavi_paayum_thanga_kuthirai/
