### ISSUE TITLE
ஆறுமுகமான பொருள் - ஆன்மீகம் - தொ. மு. பாஸ்கரத் தொண்டைமான்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#262]
https://ta.wikisource.org/s/91hg

உரிமை - Public Domain - CC0

**Comment by thesathyan** [comment]
![ஆறுமுகமான பொருள் - ஆன்மீகம் - தொ](https://user-images.githubusercontent.com/3577373/63636257-b66e9e00-c68a-11e9-9058-cb0d0be60883.jpg)

Sathya
experimentsofme@gmail.com

**Comment by meena-sundaram** [comment]
![Arumuga Perumal](https://user-images.githubusercontent.com/44741122/63638058-50414580-c6a1-11e9-97d7-e263fa16b9a4.jpg)



அட்டைப்படம் - B. மீனா meenabalasunadarm@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/anmegama4

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/aarumugamana_porul


released here.
