### ISSUE TITLE
﻿கல்விச் சிந்தனையாளர் மால்கம் ஆதிசேஷையா- ஏற்காடு இளங்கோ 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#263]
﻿கல்விச் சிந்தனையாளர் மால்கம் ஆதிசேஷையா
ஆசிரியர் ஏற்காடு இளங்கோ 

உரிமை : CC BY SA
[all_text_for_KSM.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3512768/all_text_for_KSM.pdf.txt)
[KSM.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3512772/KSM.pdf)

@Tharagavaskar PROOF READ THIS

**Comment by thesathyan** [comment]
![கல்விச் சிந்தனையாளர் மால்கம் ஆதிசேஷையா- ஏற்காடு இளங்கோ](https://user-images.githubusercontent.com/3577373/63636248-97700c00-c68a-11e9-8752-a329194819e5.jpg)

Sathya
experimentsofme@gmail.com

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - http://freetamilebooks.com/ebooks/malkam_aathishaeshaiya
