### ISSUE TITLE
சலாம் இஸ்லாம்-களந்தை பீர்முகமது

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#264]
[salam islam.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3293911/salam.islam.pdf)
[salamislam.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3293912/salamislam.docx)

**Comment by Anees987** [comment]
![salam islam](https://user-images.githubusercontent.com/54346035/63635283-aa261900-c669-11e9-86f9-5b376f262e5a.JPG)

Name : Anees Barvin
Mail : anees.it@gmail.com

**Comment by thesathyan** [comment]
![சலாம் இஸ்லாம்-களந்தை பீர்முகமது](https://user-images.githubusercontent.com/3577373/63636241-76a7b680-c68a-11e9-9d43-5210bf203da7.jpg)

Sathya
experimentsofme@gmail.com

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/salam_islam
