### ISSUE TITLE
அதிசயத் தாவரங்கள் - அறிவியல் கட்டுரைகள் - ஏற்காடு இளங்கோ

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#265]
ஆசிரியர் - ஏற்காடு இளங்கோ - yercaudelango@gmail.com
ஒருங்குறி மாற்றம் - மு. சிவலிங்கம் - musivalingam@gmail.com

உரிமை - Creative Commons Attribution Non Commercial 4.0 international license

**Comment by tshrinivasan** [comment]
[Athisaya Thavarangal (UNI).docx](https://github.com/KaniyamFoundation/Ebooks/files/3532533/Athisaya.Thavarangal.UNI.docx)

**Comment by thesathyan** [comment]
![அதிசயத் தாவரங்கள் - அறிவியல் கட்டுரைகள் - ஏற்காடு இளங்கோ](https://user-images.githubusercontent.com/3577373/63636234-4f50e980-c68a-11e9-961a-0a397266076e.jpg)

Sathya
experimentsofme@gmail.com

**Comment by tshrinivasan** [comment]
@rajiinperth work on this.

**Comment by rajiinperth** [comment]
Okay done @tshrinivasan

**Comment by rajiinperth** [comment]
https://archive.org/details/athisayathavarangal6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/athisaya_thavarangal
வெளியிட்டோம்..
