### ISSUE TITLE
பாரதி பிறந்தார் - கவிதைகள் - கவிஞர் முருகுசுந்தரம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#266]
https://ta.wikisource.org/s/943u

உரிமை - CC0 - Public Domain

**Comment by thesathyan** [comment]
![பாரதி பிறந்தார் - கவிதைகள் - கவிஞர் முருகுசுந்தரம்](https://user-images.githubusercontent.com/3577373/63636228-36483880-c68a-11e9-90a2-8a9ac723d814.jpg)

Sathya
experimentsofme@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/bharathipiranthaar6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/bharathi_piranthar
