### ISSUE TITLE
சொன்னார்கள் - கவிஞர் சுரதா - பொன்மொழிகள்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#267]
https://ta.wikisource.org/s/920r

உரிமை - CC0 - Public Domain

**Comment by thesathyan** [comment]
![சொன்னார்கள் - கவிஞர் சுரதா - பொன்மொழிகள்](https://user-images.githubusercontent.com/3577373/63636219-1284f280-c68a-11e9-81e3-f4f295c613b3.jpg)

Sathya
experimentsofme@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/sonnargala4

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/sonnaargal

வெளியிட்டோம்.
