### ISSUE TITLE
திண்ணைக் கதைகள் - சிறுகதைகள் - சிறகு இரவிச்சந்திரன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#268]
[sirukathi valayam and other stories from thinnai  jan 2015.docx](https://github.com/KaniyamFoundation/Ebooks/files/3532854/sirukathi.valayam.and.other.stories.from.thinnai.jan.2015.docx)

ஆசிரியர் - tamizhsiragu@gmail.com

உரிமை - Creative Commons Attribution Non Commercial 4.0 international license

Note to ebook maker :
1. remove {posted from fb} string on the story titles
2. remove 0 and replace with new lines.

**Comment by thesathyan** [comment]
![Kaniyam cover default](https://user-images.githubusercontent.com/3577373/63636195-d5206500-c689-11e9-9638-01094483459c.jpg)

Sathya
experimentsofme@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/thinnaikathaikal_6_inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/thinnai_kadhaigal

வெளியிட்டோம்..
