### ISSUE TITLE
சான்றோர் தமிழ்-சமூகவியல்-முனைவர் சி. பாலசுப்பிரமணியன்

### ISSUE THREAD

**Issue by tha-uzhavan** [KaniyamFoundation/Ebooks#269]
சான்றோர் தமிழ் : https://ta.wikisource.org/s/944q
உரிமம் : CC0 (நூலின் இரண்டாம் பக்கத்தில் விளக்கம் உள்ளது)
வகை: தமிழக அரசின் நாட்டுடைமை நூல்களில் ஒன்று.
வேண்டுகோள்: தமிழ் விக்கிமூலம் திட்டத்தில் பல பங்களிப்பாளர்கள் பல மணிநேரம் உழைத்து ஒவ்வொரு நூலும் உருவாக்குகின்றனர். எனவே, அது குறித்த சிறு குறிப்பை, ஒவ்வொரு தமிழ் விக்கிமூல நூல்களிலும் வழங்கினால், அது அத்திட்டத்தினருக்கு ஊக்குவிப்பாக அமையும்.

**Comment by tshrinivasan** [comment]
என்ன குறிப்பு சேர்க்க வேண்டும்?

அதையும் இங்கே ஒவ்வொரு நூலுக்கான பணியுடன் பகிர்க.

**Comment by gurulenin** [comment]
![sandror-tamil](https://user-images.githubusercontent.com/15311390/77503669-36105580-6e84-11ea-9661-65d404211c1d.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/sandrortamil6inch

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/SandrorTamil
