### ISSUE TITLE
சிறந்த கதைகள் பதிமூன்று (இந்திய மொழிகளிலிருந்து) - வல்லிக்கண்ணன் (மொழிபெயர்ப்பு)

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#27]
http://projectmadurai.org/pm_etexts/utf8/pmuni0571.html

**Comment by tshrinivasan** [comment]
![13-best-stories](https://user-images.githubusercontent.com/1268536/38969239-e17612ca-43ac-11e8-8031-a5c26585906f.jpg)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/siranta_kadhaigal_pathimoondru

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/siranta_kadhaigal_pathimoondru/

இங்கே வெளியிட்டுள்ளோம்
