### ISSUE TITLE
இன்றைய கண்ணாடியும் நாளைய முகங்களும்-களந்தை பீர்முகமது

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#271]
[indrayakanadiyumnalayamugangalum.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3292956/indrayakanadiyumnalayamugangalum.pdf)

[206_indraiya_kannadiyum_naalai_mugangalum.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3292959/206_indraiya_kannadiyum_naalai_mugangalum.docx)

@Tharagavaskar proof read as per sequncence

**Comment by gurulenin** [comment]
![mirror](https://user-images.githubusercontent.com/15311390/77504328-09f5d400-6e86-11ea-837b-e4190447eecd.jpg)

**Comment by rajiinperth** [comment]
@tshrinivasan  : Mention the license for this ebook

**Comment by tshrinivasan** [comment]
CC-BY-SA

@rajiinperth

**Comment by rajiinperth** [comment]
https://archive.org/details/kannadiyummugangalum6inch

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/KannadiyumMugangalum
