### ISSUE TITLE
போராளிகளை போற்றுவோம் - கவிதைகள் - சடையன் பெயரன் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#272]
[போராளிகளை-போற்றுவோம்.docx](https://github.com/KaniyamFoundation/Ebooks/files/3559828/-.docx)

Right - Creative Commons Attribution Non Commercial 4.0 international license

**Comment by gurulenin** [comment]
![porali](https://user-images.githubusercontent.com/15311390/74797995-8713b380-52f2-11ea-9bf8-06851660fd05.jpg)

**Comment by alauvdheen** [comment]
https://archive.org/details/poralikalai_potruvom
@tshrinivasan

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/Poralikalai_Potruvom
