### ISSUE TITLE
மார்க்சிஸ்ட் தத்துவார்த்த இதழ் - ஏப்ரல் மாத இதழ்

### ISSUE THREAD

**Issue by khaleeljageer** [KaniyamFoundation/Ebooks#273]

**Comment by aruntamilyazhini** [comment]
![april](https://user-images.githubusercontent.com/52279648/64026149-cfc88c00-cb5b-11e9-8268-5d5f00bb5f94.jpg)

**Comment by aruntamilyazhini** [comment]
https://archive.org/details/marxist_monthly_journal_april-2019-08-30-19-07-20

**Comment by khaleeljageer** [comment]
Issue created for **Education** purpose...
Closing this issue. Original book uploaded later.
