### ISSUE TITLE
தீர்க்க தரிசி-கலீல் ஜிப்ரான்-( தமிழாக்கம் : நலங்கிள்ளி )

### ISSUE THREAD

**Issue by arun8939478** [KaniyamFoundation/Ebooks#275]
[தீர்க்கதரிசி.docx](https://github.com/KaniyamFoundation/Ebooks/files/3601670/default.docx)

**Comment by arun8939478** [comment]
கலில் ஜிப்ரானின் ப்ராஃபெட் தமிழாக்கம் இணைக்கப்பட்டுள்ளது. முன் அட்டைபடம் வேண்டும்.

**Comment by tshrinivasan** [comment]
உரிமை : Creative Commons Attribution-International License.

**Comment by arunvisuals** [comment]
Name: Arunkumar - அருண்குமார்
Mail: visualsarun@gmail.com
![01](https://user-images.githubusercontent.com/55313727/64906078-1ba03700-d6ff-11e9-8454-ef3c5aea5620.jpg)

**Comment by arun8939478** [comment]
தீர்க்கதரிசி-கலீல் ஜிப்ரான்-( தமிழாக்கம் : நலங்கிள்ளி ) --Cover is great, Think தீர்க்கதரிசி must be as a single word. sorry for the initial error.(the inbetween space to be removed)

**Comment by arunvisuals** [comment]
![01](https://user-images.githubusercontent.com/55313727/64906397-cadf0d00-d703-11e9-9c3b-133a6edda0e2.jpg)

Corrected. நன்றி.

**Comment by rajiinperth** [comment]
https://archive.org/details/dheerkadharisi6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/dheerkadharisi
