### ISSUE TITLE
மனம் போல வாழ்வு -வ.உ. சி மொழி பெயர்ப்பு

### ISSUE THREAD

**Issue by arun8939478** [KaniyamFoundation/Ebooks#276]
[மனம்போல வாழ்வு.docx](https://github.com/KaniyamFoundation/Ebooks/files/3601874/default.docx)
![MANAM POL](https://user-images.githubusercontent.com/38608203/64717912-cdaee780-d4e2-11e9-956d-ca90c59ff697.jpg)

**Comment by tshrinivasan** [comment]
உரிமை : CC0 / Public Domain

**Comment by arunvisuals** [comment]
Book Cover Added
Name: Arunkumar - அருண்குமார்
Mail: visualsarun@gmail.com


![02](https://user-images.githubusercontent.com/55313727/64907147-8146f000-d70c-11e9-8c88-81b5cde5fe9f.jpg)

**Comment by arun8939478** [comment]
![MANAM POL](https://user-images.githubusercontent.com/38608203/64908550-6f227d00-d71f-11e9-829f-8793f6d1185c.jpg)

**Comment by arun8939478** [comment]
Hi ArunKumar, Please check attachment. This cover was done by designer Manoj Kumar 2-3 years before but some how this book missed out. This cover is very significant becasue it is showing Oiginal author and Tamil Translator. This book was translated by வ உ சி when he was in Jail in 1909and I guess Tamil will be one of the few languages which made a translation even during the life time of  the author,  James Allen who died in 1912. So in the enclosed cover Please write the names ஜேம்ஸ் ஆலன்-வ உ சி. Thanks. (The cover was enclosed initially, I think  you or Sreeni had not noticed. Thanks)

**Comment by arunvisuals** [comment]
corrected version

![03](https://user-images.githubusercontent.com/55313727/65015837-4d541080-d940-11e9-8166-7c3d2003e8b1.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/manampolavalvu6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/manampolavalvu/
