### ISSUE TITLE
கி.மு. 10,000 தொல் தமிழர் நாகரீகம்-நவீனா அலெக்சாண்டர் 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#279]
கிரியேட்டிவ் காமன்ஸ் உரிமை CC BY SA

![28 10000BC](https://user-images.githubusercontent.com/38220354/65616756-3618c100-dfd9-11e9-8b4c-1f4aeae278bd.jpg)

**Comment by gnuanwar** [comment]
[26. 10000BC (wecompress.com).docx](https://github.com/KaniyamFoundation/Ebooks/files/3653517/26.10000BC.wecompress.com.docx)

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/ki_mu_10000_thol_tamilar_naagareegam/
