### ISSUE TITLE
தமிழர் நாட்டுப்பாடல்கள் - நா.வானமாமலை

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#280]
http://www.tamilvu.org/ta/library-lA420-html-lA420ind-147762

**Comment by Tharagavaskar** [comment]
521 pages copied

**Comment by Tharagavaskar** [comment]
543/543 pages copied
165/543 pages tagged

**Comment by Tharagavaskar** [comment]
[தமிழர் நாட்டுப்பாடல்கள்1.zip](https://github.com/KaniyamFoundation/Ebooks/files/3802891/1.zip)
copied and tagged

**Comment by gurulenin** [comment]
![tamil-songs](https://user-images.githubusercontent.com/15311390/77499196-6dc4d080-6e77-11ea-9042-77a39cbe1bde.jpg)

**Comment by rajiinperth** [comment]
@tshrinivasan : License ?

**Comment by tshrinivasan** [comment]
Public domain

**Comment by rajiinperth** [comment]
https://archive.org/details/tamil-nattu-padalgal-6-inch

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/TamilNattuPadalgal
