### ISSUE TITLE
௭ண்ணங்களின் சிதறல்கள் - பாகம்  2-சிவகுமாரி ஆவுடையப்பன்

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#287]
[எண்ணங்களின் சிதறல்கள் - பாகம் 2.docx](https://github.com/KaniyamFoundation/Ebooks/files/3720209/-.2.docx)

**Comment by gurulenin** [comment]
![ennangal-2](https://user-images.githubusercontent.com/15311390/74799028-6c8f0980-52f5-11ea-821c-e5c950e3f6be.jpg)

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/ennangalin_chitharalgal_part_2/
