### ISSUE TITLE
ஞானியின் கவிதைகள் - ஞானி

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#288]
1.completed word doc file

https://github.com/KaniyamFoundation/Proofread-Works/files/3734627/default.docx

2.source  file

https://archive.org/download/gnaniyin-kavidhaigal/gnaniyin-kavidhaigal.pdf

**Comment by gurulenin** [comment]
![gnani](https://user-images.githubusercontent.com/15311390/77497796-37398680-6e74-11ea-9bf8-7449bb1491a3.jpg)

**Comment by alauvdheen** [comment]
i take this work
@tshrinivasan

**Comment by alauvdheen** [comment]
@tshrinivasan 
https://archive.org/details/content-pdf

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/Gnaniyin_Kavithaikal
