### ISSUE TITLE
கீழடி வைகை நதிக்கரையில் சங்க கால நாகரிகம் - தொல்லியல் துறை

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#289]
1.source file

https://github.com/KaniyamFoundation/Proofread-Works/files/3639277/_._._._.pdf

2.completed doc

https://github.com/KaniyamFoundation/Proofread-Works/files/3739725/default.docx

**Comment by gnuanwar** [comment]
@gurulenin புத்தகத்தின் தொடக்கத்தில் காப்பரிமை அனுமதி கடிதத்தை இணைக்கவும் 

அதன் இணைப்பை காணவும் https://commons.wikimedia.org/wiki/File:GoTN_Tamil_Development_Departments_order_on_creative_commons_cc_by_sa.pdf

தமிழ அரசு அனைத்து வெளியிடுகளுக்கும் இது பொருந்தும்

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/keezhadi
