### ISSUE TITLE
சிறுகதைகள் தொகுப்பு- 3 - புதுமைப்பித்தன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#29]
http://projectmadurai.org/pm_etexts/utf8/pmuni0565.html

**Comment by gurulenin** [comment]
![puthumaipithan-2](https://user-images.githubusercontent.com/15311390/39033968-3b9e342c-4492-11e8-974f-4a7275280383.jpg)

**Comment by manimaran96** [comment]
https://archive.org/details/short_stories_collection_3_of_putumaippittan-2018-04-22-18-38-58

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/short_stories_collection_3_of_putumaippittan/
