### ISSUE TITLE
எளிய தமிழில் சாப்ட்வேர் டெஸ்டிங் - கி.முத்துராமலிங்கம் 

### ISSUE THREAD

**Issue by muthu1809** [KaniyamFoundation/Ebooks#290]

**Comment by muthu1809** [comment]
[எளிய தமிழில் சாப்ட்வேர் டெஸ்டிங்.docx](https://github.com/KaniyamFoundation/Ebooks/files/3793871/default.docx)

**Comment by alauvdheen** [comment]
https://archive.org/details/eliyatamililsoftwaretestinga4

**Comment by muthu1809** [comment]
நன்றி! நெஞ்சார நன்றி!!

**Comment by nithyadurai87** [comment]
need better cover image.

The fonts in A4 are not good.

Do "clear formatting" for all text on the odt file before running the ebook making scripts.

**Comment by gurulenin** [comment]
![software-testing](https://user-images.githubusercontent.com/15311390/76483149-43692100-643c-11ea-9cb4-d62d198ea293.jpg)

**Comment by alauvdheen** [comment]
*ok*

**Comment by alauvdheen** [comment]
https://archive.org/details/eliyatamililsoftwaretestinga4_20200313
@nithyadurai87

**Comment by tshrinivasan** [comment]
Good work

வெள்., 13 மார்., 2020, பிற்பகல் 10:29க்கு, alauvdheen <
notifications@github.com> எழுதியது:

**Comment by alauvdheen** [comment]
Thankyou

**Comment by tshrinivasan** [comment]
Released here - http://freetamilebooks.com/ebooks/eliya_tamilil_software_testing/
