### ISSUE TITLE
ஜுபைதா அல்லது பழிக்குப் பழி - பா. தாவூத்ஷா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#295]
<strong> மின்னூல் பெயர்: </strong>ஜுபைதா அல்லது பழிக்குப் பழி
<strong>ஆசிரியர் பெயர்: </strong>பா. தாவூத்ஷா
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>nooruddinahamed@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1i-nV2Ng_Aaf-Scn9GVUd8ShoifwbUIQK
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=17QEwyh4ecX8VaqjJcsUav1yx7KEjhhnE

**Comment by alauvdheen** [comment]
மின்புத்தகமாக மாற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
sure

**Comment by alauvdheen** [comment]
https://archive.org/details/Zubaida_allathu_Pazhiku_Pazhi-2020-03-09-21-36-16

**Comment by alauvdheen** [comment]
manually uploaded files link 
https://archive.org/details/zubaidaallathupazhikupazhia4

**Comment by nithyadurai87** [comment]
too many empty pages in https://ia601502.us.archive.org/14/items/zubaidaallathupazhikupazhia4/Zubaida_allathu_Pazhiku_Pazhi_a4.pdf

fix the errors before publishing to FTE.

**Comment by alauvdheen** [comment]
empty pages removed file link
https://archive.org/details/zubaidanooruddinahamed 
@nithyadurai87

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Zubaida_allathu_Pazhiku_Pazhi
