### ISSUE TITLE
வஞ்சிமாநகரம் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#3]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0583.html

**Comment by tshrinivasan** [comment]
![vanji-managaram](https://user-images.githubusercontent.com/1268536/38519223-b8a2782c-3c5c-11e8-9d02-a190404a7917.jpg)

**Comment by rajiinperth** [comment]
Please provide artist name

**Comment by tshrinivasan** [comment]
its me

**Comment by rajiinperth** [comment]
okay...super

**Comment by rajiinperth** [comment]
https://archive.org/details/Vanjimanagaram6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Vanjimanagaram
