### ISSUE TITLE
வேரில் பழுத்த பலா - சு. சமுத்திரம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#30]
http://projectmadurai.org/pm_etexts/utf8/pmuni0554.html

**Comment by tshrinivasan** [comment]
![veril-palutha-pala](https://user-images.githubusercontent.com/1268536/38924782-7607ae22-431b-11e8-8d06-2bbec1c21a5f.jpg)

**Comment by rajiinperth** [comment]
artist name details ?

**Comment by tshrinivasan** [comment]
Its me.

-- 
Regards,
T.Shrinivasan


My Life with GNU/Linux : http://goinggnu.wordpress.com
Free E-Magazine on Free Open Source Software in Tamil : http://kaniyam.com

Get Free Tamil Ebooks for Android, iOS, Kindle, Computer :
http://FreeTamilEbooks.com

**Comment by rajiinperth** [comment]
okay

**Comment by rajiinperth** [comment]
https://archive.org/details/VerilPalathaPala6Inch

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/veril_pazhutha_pala/

released here
