### ISSUE TITLE
முதல்தளிர் - கவிதைகள் - கவிமலர்சரண்யா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#302]
<strong> மின்னூல் பெயர்: </strong>முதல்தளிர்
<strong>ஆசிரியர் பெயர்: </strong>கவிமலர்சரண்யா
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>Saransaranya2211@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>கவிமலர்சரண்யா
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>Saransaranya2211@gmail.com
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1hAKmiOdRIbYYHjYfb8OyUddF1RFD3qLA

**Comment by gurulenin** [comment]
![bud](https://user-images.githubusercontent.com/15311390/77290432-2f59d500-6d02-11ea-93e8-fbb7c5181eb3.jpg)

**Comment by alauvdheen** [comment]
https://archive.org/details/Muthal_Thalir-2020-03-24-22-10-01
@tshrinivasan

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - http://freetamilebooks.com/ebooks/Muthal_Thalir
