### ISSUE TITLE
 பெண்ணுக்கு கற்பு வலியுறுத்தப்பட  காரணம் என்ன? -   அ.தமிழ்ச்செல்வன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#303]
<strong> மின்னூல் பெயர்: </strong> பெண்ணுக்கு கற்பு வலியுறுத்தப்பட  காரணம் என்ன?
<strong>ஆசிரியர் பெயர்: </strong>  அ.தமிழ்ச்செல்வன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>a.tamilselvan42@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1lka9IRmoelJ7pfqkrSa62_z3V9ZxA-5j
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1fyoMvFDK-4GxJAV0Bt8v7Nyh_fivnjsn

**Comment by gurulenin** [comment]
https://freetamilebooks.com/ebooks/ilangaiyul_yerpatulathu_arasiyal_maatramalla/


same content ?

**Comment by tshrinivasan** [comment]
Yes.

Same content.

Closing this.
