### ISSUE TITLE
திராவிட வாசிப்பு (அண்ணா சிறப்பிதழ்)  - திராவிட எழுத்தாளர்கள்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#304]
<strong> மின்னூல் பெயர்: </strong>திராவிட வாசிப்பு (அண்ணா சிறப்பிதழ்) 
<strong>ஆசிரியர் பெயர்: </strong>திராவிட எழுத்தாளர்கள்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>dravidavaasippu@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1FLw1zzx2ZMITEd3I1LRx0fvPt38GEdGm
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1bGzd36N1fkDp01EkuAW-5CpMdfkeiScO

**Comment by alauvdheen** [comment]
இந்த புத்தகத்தை நான் இ புத்தகம் மற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
>
> சரி


எடுத்துக் கொள்க.

நன்றி

**Comment by alauvdheen** [comment]
*நன்றி*



*
                         ஷே*

**Comment by alauvdheen** [comment]
[Ebook.zip](https://github.com/KaniyamFoundation/Ebooks/files/4224577/Ebook.zip)

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/diravida_vaasippu_1/
