### ISSUE TITLE
பரிமாணத்தின் அர்த்தங்கள்  - இரா.வெங்கடேஸ் குமார் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#312]
<strong> மின்னூல் பெயர்: </strong>பரிமாணத்தின் அர்த்தங்கள் 
<strong>ஆசிரியர் பெயர்: </strong>இரா.வெங்கடேஸ் குமார் 
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>vengadeshkumar1999@gmail.com 
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>இரா.வெங்கடேஸ் குமார் 
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>vengadeshkumar1999@gmail.com 
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1FFi6AScNYsgALx_81XC_tHypQp7E17Kq
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1QoQfwOZO9ClLXvU1jt6B_jz7F2V8Bq3P

**Comment by gurulenin** [comment]
only 7 pages in attached pdf file

**Comment by Tamileservice290** [comment]
மின்புத்தகமாக மாற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
Too small book.

Closing this.
