### ISSUE TITLE
எளிய தமிழில் Git 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#317]
Get book from muthu payilagam and release in FTE.

**Comment by muthu1809** [comment]
[GitHub in Tamil.docx](https://github.com/KaniyamFoundation/Ebooks/files/4387781/GitHub.in.Tamil.docx)
எளிய தமிழில் கிட் - புத்தகம் சேர்க்கப்பட்டது

**Comment by alauvdheen** [comment]
i take this work
@tshrinivasan

**Comment by alauvdheen** [comment]
https://archive.org/details/Eliya_tamizhil_git-2020-04-11-22-21-20
@tshrinivasan

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/Eliya_tamizhil_git
