### ISSUE TITLE
வஸந்த கோகிலம் - வடுவூர் கே. துரைசாமி ஐயங்கார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#32]
http://projectmadurai.org/pm_etexts/utf8/pmuni0543.html

**Comment by tshrinivasan** [comment]
![default](https://user-images.githubusercontent.com/1268536/51821233-7d419b80-22fe-11e9-9dac-9a636d5878f9.jpg)

அட்டைப்படம்

பெயர் - எம்.ரிஷான் ஷெரீப்  
மின்னஞ்சல் முகவரி - mrishansha@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/VasanthaKokilam6Inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/vasantha_kokilam

released here
