### ISSUE TITLE
காலங்களில் சிவன் வசந்தம் - கா.பிரபாகரன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#321]
<strong> மின்னூல் பெயர்: </strong>காலங்களில் சிவன் வசந்தம்
<strong>ஆசிரியர் பெயர்: </strong>கா.பிரபாகரன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>karan.prabha1978@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=14y3xda3LIqu2yx78b9obLwRfGp5aJmhW
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1AtFMvqpMVTxlusWzzuzApss31f_0fekW

**Comment by rajiinperth** [comment]
@tshrinivasan : Need artist name and email

**Comment by tshrinivasan** [comment]
same author is artist.

**Comment by rajiinperth** [comment]
okay

**Comment by rajiinperth** [comment]
https://archive.org/details/kalangalilsivanvasantham6inch

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/KalangalilSivanVasantham
