### ISSUE TITLE
வைகுந்த வாழ்வளிக்கும் கருடசேவை - கைலாஷி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#322]
<strong> மின்னூல் பெயர்: </strong>வைகுந்த வாழ்வளிக்கும் கருடசேவை
<strong>ஆசிரியர் பெயர்: </strong>கைலாஷி
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>muruganandams@rediffmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1F-DAtlAWbBXDPuJ-Esnk4-HxCb77_ZnW
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1BsCIXPksl4X1Gzxe__ylQqCp6hWSqFDg

**Comment by rajiinperth** [comment]
Is artist name = author name ?

**Comment by tshrinivasan** [comment]
Yes.

புத., 13 மே, 2020, முற்பகல் 10:06க்கு, rajiinperth <notifications@github.com>
எழுதியது:

**Comment by tshrinivasan** [comment]
>
>
>>
அட்டைப்படம்   -  பிரசன்னா udpmprasanna@gmail.com

>

**Comment by rajiinperth** [comment]
okay

**Comment by rajiinperth** [comment]
https://archive.org/details/KarudaSevai-2020-05-15-23-11-03

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/KarudaSevai
