### ISSUE TITLE
வேற்றுகிரகவாசியை சந்தித்தேன்.... - அ.தமிழ்ச்செல்வன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#325]
<strong> மின்னூல் பெயர்: </strong>வேற்றுகிரகவாசியை சந்தித்தேன்....
<strong>ஆசிரியர் பெயர்: </strong>அ.தமிழ்ச்செல்வன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong> a.tamilselvan42@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1ME9QelueB1sR5sOoBNPcPeAxBhjTPqrj
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1NGPLXVOaA-IhbBbJEnM1OfTAg2KA6Kst

**Comment by rajiinperth** [comment]
https://archive.org/details/vetru-kraga-vasi-6-inch

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/VetruKragaVasi
