### ISSUE TITLE
நிமிர்ந்து நில் - அ.இம்ரான் ஹக்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#326]
<strong> மின்னூல் பெயர்: </strong>நிமிர்ந்து நில்
<strong>ஆசிரியர் பெயர்: </strong>அ.இம்ரான் ஹக்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>imranhak78@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=18agRk8gYMjLyiLTDQaG0WobpzY4k6X1O
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1elTBrVbcTJcFBVYmFAroWMfKL4VlhNV0

**Comment by alauvdheen** [comment]
@tshrinivasan 
i take this work

**Comment by alauvdheen** [comment]
https://archive.org/details/nimirndhu-nil
@tshrinivasan 
compleated sir

**Comment by tshrinivasan** [comment]
Hi,

upload using the upload script here
https://github.com/KaniyamFoundation/create_ebooks/blob/master/upload_to_ia.py

and share the new URL.

**Comment by alauvdheen** [comment]
Ok sir

**Comment by alauvdheen** [comment]
https://archive.org/details/Nimirndhu_Nil-2020-04-22-23-03-38

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/Nimirndhu_Nil
