### ISSUE TITLE
திருப்பாத தரிசனம்  (சப்த விடங்க தலங்கள் பத்தியுலா) - கைலாஷி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#328]
<strong> மின்னூல் பெயர்: </strong>திருப்பாத தரிசனம்  (சப்த விடங்க தலங்கள் பத்தியுலா)
<strong>ஆசிரியர் பெயர்: </strong>கைலாஷி
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>muruganandam.subramanian@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1nZ5fSjKu4_RgbBtSoDwHigsJ1qF0S8F4
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1iYtvXe8-Yh77u3J61IS5Uq-E-Y1JFvYw

**Comment by rajiinperth** [comment]
https://archive.org/details/ThirupadhaDharisanam-2020-05-25-10-07-01

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/ThirupadhaDharisanam
