### ISSUE TITLE
என் சரித்திரம் - பாகம் 1-2-3-4-5 - உ.வே.சாமிநாதையரவர்கள்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#33]
http://projectmadurai.org/pm_etexts/utf8/pmuni0544_01.html http://projectmadurai.org/pm_etexts/utf8/pmuni0544_02.html http://projectmadurai.org/pm_etexts/utf8/pmuni0548_01.html http://projectmadurai.org/pm_etexts/utf8/pmuni0548_02.html http://projectmadurai.org/pm_etexts/utf8/pmuni0556.html

**Comment by gurulenin** [comment]
![uvesa](https://user-images.githubusercontent.com/15311390/38946775-23c62c00-4358-11e8-9ad7-ebd137af1ee8.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/En_Sariththiram-2018-08-26-13-24-32

**Comment by tshrinivasan** [comment]
Thanks for the great book and great work on this.

released here
http://freetamilebooks.com/ebooks/en_sariththiram/
