### ISSUE TITLE
கோமளத்தின் கோபம் (சிறுகதைகள்)
அறிஞர் அண்ணா


### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#338]
https://www.projectmadurai.org/pm_etexts/utf8/pmuni0717.html

**Comment by 1234773** [comment]
![anna 6](https://user-images.githubusercontent.com/63628034/82789899-bbb28080-9e88-11ea-9134-07592a84543c.jpg)
 அ.,தமிழ்ச்செல்வன்
a.tamilselvan42@gmail.com

**Comment by 1234773** [comment]
![anna 2](https://user-images.githubusercontent.com/63628034/82790032-fa483b00-9e88-11ea-960a-931adc05ebbd.jpg)

அ.,தமிழ்ச்செல்வன்
a.tamilselvan42@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/KomalattinKopam-2020-06-15-14-25-41

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/KomalattinKopam
