### ISSUE TITLE

எட்டு நாட்கள் (கட்டுரைகள்)
அறிஞர் அண்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#339]
https://www.projectmadurai.org/pm_etexts/utf8/pmuni0716.html

**Comment by 1234773** [comment]
![anna](https://user-images.githubusercontent.com/63628034/82787135-6de74980-9e83-11ea-9f5f-063bfe359fc6.jpg)
 அ.தமிழ்ச்செல்வன்
a.tamilselvan42@gmail.com

**Comment by rajiinperth** [comment]
@tshrinivasan : Is license Public Domain ?

**Comment by rajiinperth** [comment]
@tshrinivasan : Please confirm the license.

**Comment by tshrinivasan** [comment]
All books we take from project madurai and wikisource are public domain .

**Comment by rajiinperth** [comment]
Okay. thanks

**Comment by rajiinperth** [comment]
https://archive.org/details/EttuNatkal-2020-06-06-12-27-56

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/EttuNatkal
