### ISSUE TITLE
திவான் லொடபட சிங் பகதூர் - வடுவூர் கே. துரைசாமி ஐயங்கார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#34]
http://projectmadurai.org/pm_etexts/utf8/pmuni0546.html

**Comment by gnuanwar** [comment]
[திவான்_லொடபட_சிங்_பகதூர்.pdf](https://github.com/KaniyamFoundation/Ebooks/files/2872199/_._._.pdf)

**Comment by gnuanwar** [comment]
![_ _ _](https://user-images.githubusercontent.com/38220354/52902914-8064e300-323d-11e9-99c6-fe414e1a2863.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/dhiwanbagadhur6inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/DhiwanBagadhur
