### ISSUE TITLE
கொரோனா கவிதைகள் -  அ.தமிழ்ச்செல்வன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#340]
<strong> மின்னூல் பெயர்: </strong>கொரோனா கவிதைகள்
<strong>ஆசிரியர் பெயர்: </strong> அ.தமிழ்ச்செல்வன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>a.tamilselvan42@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1wQI5FoTPLdiwPqaqIv_kxz84yQClZdN4
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1LoU_8tUOKer6Ka-wNdLNTkLNIbdjr1JZ

**Comment by 1234773** [comment]
![corona raper](https://user-images.githubusercontent.com/63628034/82790400-9d995000-9e89-11ea-9088-86366b8df4ab.jpg)
அ.,தமிழ்ச்செல்வன்
a.tamilselvan42@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/CoronaKavithaigal-2020-05-29-12-09-35

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/CoronaKavithaigal

**Comment by 1234773** [comment]
மிக்க நன்றி.. நூலின் தேவை கருதி  உடனடியாக வெளியிட்ட மைக்கு நன்றி


புத., 3 ஜூன், 2020, முற்பகல் 9:53 அன்று, Shrinivasan T <
notifications@github.com> எழுதியது:
