### ISSUE TITLE
இரு குரல் - விக்னேஷ்வரன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#342]
<strong> மின்னூல் பெயர்: </strong>இரு குரல்
<strong>ஆசிரியர் பெயர்: </strong>விக்னேஷ்வரன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>vwaran517@gmail.coml
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1szlx_EYlae5lB6R2ZIxEaHLZKMSCQw-l

**Comment by 1234773** [comment]
அ.தமிழ்ச்செல்வன்
a.tamilselvan42@gmail.com
![Uploading 2t two.jpg…]()

**Comment by 1234773** [comment]
![2t two](https://user-images.githubusercontent.com/63628034/84564103-223b0800-ad7e-11ea-9e7d-b0f7c4b9e33b.jpg)
அ.தமிழ்ச்செல்வன்
a.tamilselvan42@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/Irukural-2020-07-08-08-39-04

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/Irukural

**Comment by 1234773** [comment]
நான் உருவாக்கிய அட்டைப்படத்தை பயன்படுத்தியமைக்கு நன்றி

சனி, 5 டிச., 2020, முற்பகல் 8:04 அன்று, Shrinivasan T <
notifications@github.com> எழுதியது:
