### ISSUE TITLE
இந்திய இலக்கியச் சிற்பிகள் : உரைவேந்தர் ஒளவை சு. துரைசாமிபிள்ளை 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#350]
ஆசிரியர்: ச. சாம்பசிவனார்

https://www.projectmadurai.org/pm_etexts/utf8/pmuni0724.html

License: Public Domain

**Comment by 1234773** [comment]
![indian lit copy](https://user-images.githubusercontent.com/63628034/84563985-3d594800-ad7d-11ea-96e7-441a8c18f847.jpg)
 அ.தமிழ்ச்செல்வன்
a.tamilselvan42@gmail.com

**Comment by gurulenin** [comment]
விக்கிமூலத்திலிருந்து இந்தப் புத்தகம் ஏற்கனவே வெளியிடப்பட்டுவிட்டது. 

https://freetamilebooks.com/ebooks/uraivendar_avvai_duraisamypillai/
