### ISSUE TITLE
இந்திய இலக்கியச் சிற்பிகள் : தமிழ்த் தாத்தா (டாக்டர் உ. வே. சாமிநாத ஐயரவர்கள் வாழ்வும் இலக்கியப் பணியும்) 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#351]
ஆசிரியர் - கி.வா. ஜகந்நாதன்

License: Public Domain

https://www.projectmadurai.org/pm_etexts/utf8/pmuni0725.html

**Comment by 1234773** [comment]
![Untitled-3 copy](https://user-images.githubusercontent.com/63628034/84563962-02efab00-ad7d-11ea-975c-3225ad675dee.jpg)
 அ.தமிழ்ச்செல்வன்
a.tamilselvan42@gmail.com

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/indhiya_ilakiya_sirpigal
