### ISSUE TITLE
இந்திய இலக்கியச் சிற்பிகள்: தொல்காப்பியர் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#352]
ஆசிரியர்: தமிழண்ணல்

https://www.projectmadurai.org/pm_etexts/utf8/pmuni0726.html

Licence - Will check and confirm

**Comment by tshrinivasan** [comment]
start working on this book after I confirm the license

**Comment by Tamileservice290** [comment]
மின்புத்தகமாக மாற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
Not sure about the license. Closing this.
