### ISSUE TITLE
என்னை எனக்குப் பிடிக்கும் - கட்டுரைகள் - நிர்மலா ராகவன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#353]
<strong> மின்னூல் பெயர்: </strong>என்னை எனக்குப் பிடிக்கும் - கட்டுரைகள்
<strong>ஆசிரியர் பெயர்: </strong>நிர்மலா ராகவன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>nirurag@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1zQLOwIlUYhXKycbFL7BspECIjk01F5FP

**Comment by gurulenin** [comment]
![love-myself](https://user-images.githubusercontent.com/15311390/86439868-05637600-bd27-11ea-94fb-4337f2e198ea.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/EnnaiEnakkuPidikkum-2020-07-06-08-52-35

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/EnnaiEnakkuPidikkum
