### ISSUE TITLE
குடும்பம் ஒரு தாம்புக்கயிறு - கட்டுரைகள் - நிர்மலா ராகவன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#354]
<strong> மின்னூல் பெயர்: </strong>குடும்பம் ஒரு தாம்புக்கயிறு - கட்டுரைகள்
<strong>ஆசிரியர் பெயர்: </strong>நிர்மலா ராகவன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>nirurag@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1cOetYNNCMm2d_m_vHKm_hnqZ9l5s2ETQ

**Comment by Tamileservice290** [comment]
மின்புத்தகமாக மாற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
சரி

**Comment by gurulenin** [comment]
https://freetamilebooks.com/ebooks/kudumbam_oru_thambukkayiru/
