### ISSUE TITLE
கவிதைச்சாரல் - சு.ஆர்த்திமா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#357]
<strong> மின்னூல் பெயர்: </strong>கவிதைச்சாரல்
<strong>ஆசிரியர் பெயர்: </strong>சு.ஆர்த்திமா
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>aartherajche@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1cjiAJKvkGHH_4kWgb0p-iBaUDxpn-U03

**Comment by gurulenin** [comment]
![kavithai-saral](https://user-images.githubusercontent.com/15311390/104083555-ac404600-5265-11eb-92dd-c8b2642ba582.jpg)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/kavithai_saral
