### ISSUE TITLE
உள்ளே இரு! இப்படிக்கு கொரோனா - ஏற்காடு இளங்கோ

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#359]
<strong> மின்னூல் பெயர்: </strong>உள்ளே இரு! இப்படிக்கு கொரோனா
<strong>ஆசிரியர் பெயர்: </strong>ஏற்காடு இளங்கோ
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>yercaudelango@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1NC8Hgt6mEh3C9fWObzQ9TOkaZLfVYyAj

**Comment by tshrinivasan** [comment]
@gurulenin அட்டைப்படம் தருக

**Comment by gurulenin** [comment]
![corona](https://user-images.githubusercontent.com/15311390/86443707-46f71f80-bd2d-11ea-877b-0476d6d91048.jpg)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/corona
