### ISSUE TITLE
கதைக் கொத்து - சி. சுப்ரமணிய பாரதியார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#36]
http://projectmadurai.org/pm_etexts/utf8/pmuni0536.html

**Comment by gurulenin** [comment]
![kathai](https://user-images.githubusercontent.com/15311390/39092140-14f8da64-4624-11e8-9348-2d44a705e57d.jpg)

**Comment by tshrinivasan** [comment]
artist : லெனின் குருசாமி
artist_email : guruleninn@gmail.com
license : Public Domain - CCO
category : சிறுகதைகள்

**Comment by rajiinperth** [comment]
https://archive.org/details/Kathai_Kothu-2018-07-07-20-55-01

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/Kathai_Kothu
