### ISSUE TITLE
மனம் துடிக்கும் - தம்பலகாமம். த. ஜீவராஜ்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#361]
<strong> மின்னூல் பெயர்: </strong>மனம் துடிக்கும்
<strong>ஆசிரியர் பெயர்: </strong>தம்பலகாமம். த. ஜீவராஜ்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>tjeevaraj78@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1o92oQJFcJuqTUaXIkhEFHPG79IPdH9Tm
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=14ju8kHuTuCTocVEUa6fItgro4u5MRVSG

**Comment by rajiinperth** [comment]
@tshrinivasan : Can you share the artist name ?

**Comment by tshrinivasan** [comment]
Author is artist here

**Comment by rajiinperth** [comment]
Okay. Thanks

**Comment by rajiinperth** [comment]
https://archive.org/details/ManamThudikkum-2020-07-23-10-14-40

**Comment by tshrinivasan** [comment]
released here
https://freetamilebooks.com/ebooks/manamthudikkum/
