### ISSUE TITLE
திருஞானசம்பந்தரின் தமிழ் பக்தி இயக்கத்தில் திருக்கோணேச்சரம்.  (ஆய்வு) - தம்பலகாமம். த. ஜீவராஜ்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#362]
<strong> மின்னூல் பெயர்: </strong>திருஞானசம்பந்தரின் தமிழ் பக்தி இயக்கத்தில் திருக்கோணேச்சரம்.  (ஆய்வு)
<strong>ஆசிரியர் பெயர்: </strong>தம்பலகாமம். த. ஜீவராஜ்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>tjeevaraj78@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1GSukaB8G4hvu_qdkEuRcPK9rmJ5bs6po
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1nYph_UML3KvIUdZp9RoKGrUlFioFME3X

**Comment by Tamileservice290** [comment]
மின்புத்தகமாக மாற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
சரி

வெள்., 18 செப்., 2020, முற்பகல் 10:43க்கு, Tamileservice290 <
notifications@github.com> எழுதியது:

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/thirugnanasambanthar_thirukonacharam
