### ISSUE TITLE
கோவை ஞானி - நேர்காணல்கள் தொகுப்பு - இராமசாமி துரைப்பாண்டி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#366]
<strong> மின்னூல் பெயர்: </strong>கோவை ஞானி - நேர்காணல்கள் தொகுப்பு
<strong>ஆசிரியர் பெயர்: </strong>இராமசாமி துரைப்பாண்டி
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>ramsdurai@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1TdYcwDvf3s8SUM9QQn1UWG8F3VABVfPa

**Comment by Tamileservice290** [comment]
மின்புத்தகமாக மாற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
ஆம். அட்டைப்படம் சேர்த்து மின்னூலாக்குக.

**Comment by Tamileservice290** [comment]
சரி

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/kovai_gnani_interview
