### ISSUE TITLE
மனிதர்களும் அமைப்புகளும் - ஜேம்ஸ் ஆலன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#368]
<strong> மின்னூல் பெயர்: </strong>மனிதர்களும் அமைப்புகளும்
<strong>ஆசிரியர் பெயர்: </strong>ஜேம்ஸ் ஆலன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>arun2010g@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>சே.அருணாசலம்
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>arun2010g@gmail.com
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1mdggwKHQjejQq1u11XcwgrJKCJ5fwx9Y
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1WrEnO5C_uBMLT-yKGTpr-xN8B8Q-2OOL

**Comment by nithyadurai87** [comment]
![cover](https://user-images.githubusercontent.com/19593036/92007633-d340b580-ed63-11ea-89c5-c16904af9cff.jpg)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/Manithargalum_Amaipugalum
