### ISSUE TITLE
உறவாடும் எழுத்துக்கள் - பகுதி 5 - நவீன் ராஜ் தங்கவேல்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#369]
<strong> மின்னூல் பெயர்: </strong>உறவாடும் எழுத்துக்கள் - பகுதி 5
<strong>ஆசிரியர் பெயர்: </strong>நவீன் ராஜ் தங்கவேல்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>naveenrajthangavel@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1SOhSszWhljXE2CaVbiKOpn20HdPwmtxT
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=132k8vjKTsTR7RefE6CUo5L8RrSYLpztI

**Comment by Tamileservice290** [comment]
மின்புத்தகமாக மாற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/uravaadum_ezhuthukkal_5
