### ISSUE TITLE
மலை நாட்டு திவ்ய தேச யாத்திரை - கைலாஷி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#370]
<strong> மின்னூல் பெயர்: </strong>மலை நாட்டு திவ்ய தேச யாத்திரை
<strong>ஆசிரியர் பெயர்: </strong>கைலாஷி
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>muruganandams@rediffmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>udpm. Prasanna  (Cover design)
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1G6-41G5s7fLrdW_2phyruckrTak5hdqy
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1uNvACJgSUsnMmYBKDTgZbq1t6Db_nIbq

**Comment by Tamileservice290** [comment]
மின்புத்தகமாக மாற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/malai_naatu_dhivyadesa_yathirai
