### ISSUE TITLE
அச்சம் என்பது மடமையா - நிர்மலா ராகவன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#372]
<strong> மின்னூல் பெயர்: </strong>அச்சம் என்பது மடமையா
<strong>ஆசிரியர் பெயர்: </strong>நிர்மலா ராகவன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>nirurag@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1SPFmVwo2fFid-ZQbKLQRtYa_ys_-1gfd

**Comment by Tamileservice290** [comment]
மின்புத்தகமாக மாற்ற எடுத்து கொள்ளலாமா?

**Comment by tshrinivasan** [comment]
sure.

**Comment by gurulenin** [comment]
![acham-nirmala-ragavan](https://user-images.githubusercontent.com/15311390/100840048-4d83f180-349b-11eb-9885-065fcb7ac388.png)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/acham_enbathu_madamaiya
