### ISSUE TITLE
விநோதமான உயிரினங்கள் - ஏற்காடு இளங்கோ

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#373]
<strong> மின்னூல் பெயர்: </strong>விநோதமான உயிரினங்கள்
<strong>ஆசிரியர் பெயர்: </strong>ஏற்காடு இளங்கோ
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>yercaudelango@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1g_qfugKVsn0xSJxqyjyXUruF8v_xPDuC

**Comment by gurulenin** [comment]
![species](https://user-images.githubusercontent.com/15311390/99751986-6c809c00-2b09-11eb-842e-eb21cb714625.jpg)

**Comment by tshrinivasan** [comment]
If possible, please any image inside the book.

**Comment by gurulenin** [comment]
This cover image "green lizard", which is also available inside the book. (Index No. 6)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/weird_species
