### ISSUE TITLE
ஏர்டெல் வாடிக்கையாளர்களுக்கான பயனுள்ள எண்கள் - இரா.நவீன்குமார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#379]
<strong> மின்னூல் பெயர்: </strong>ஏர்டெல் வாடிக்கையாளர்களுக்கான பயனுள்ள எண்கள்
<strong>ஆசிரியர் பெயர்: </strong>இரா.நவீன்குமார்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>www.naveen0475@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1ETCHBkmRPuuF3d1k1EcGFqOOb-yxbB0f
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1MMlxYNLcrdNcL3RW06ag3qVqYTAcnsVl

**Comment by gurulenin** [comment]
எழுத்துருப் பிரச்சனை உள்ளது.
