### ISSUE TITLE
பாண்டிமாதேவி (சரித்திர நாவல் / 3 பாகங்கள்) - நா. பார்த்தசாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#38]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0503_01.html http://www.projectmadurai.org/pm_etexts/utf8/pmuni0503_02.html http://www.projectmadurai.org/pm_etexts/utf8/pmuni0503_03.html

**Comment by tshrinivasan** [comment]
![pandi-madevi](https://user-images.githubusercontent.com/1268536/39070015-5fa373f6-44ff-11e8-9c85-b125e5d844f5.jpg)

**Comment by rajiinperth** [comment]
Shrini, Are you the artist for this book ?

**Comment by tshrinivasan** [comment]
yes.

**Comment by rajiinperth** [comment]
okay

**Comment by rajiinperth** [comment]
https://archive.org/details/PandimaDevi6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/paandimaadevi/
