### ISSUE TITLE
நவதுவாரகை யாத்திரை - கைலாஷி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#382]
<strong> மின்னூல் பெயர்: </strong>நவதுவாரகை யாத்திரை
<strong>ஆசிரியர் பெயர்: </strong>கைலாஷி
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>muruganandams@rediffmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1bzwS2ZBM5-X1hYtv35xjG87gnU5WiDV-
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1TR6LLz_LWixvbwLG_LQFw5QGgUFCMu1y

**Comment by prasannaUDPM** [comment]
Kindly add cover image design : பிரசன்னா

**Comment by tshrinivasan** [comment]
![NavaDhuvaragai_Yaththirai_Cover_F1 (3)](https://user-images.githubusercontent.com/1268536/106375454-21f58880-63b2-11eb-9764-6ba5274a1fab.jpg)

அட்டைப்படம் - பிரசன்னா
udpmprasanna@gmail.com

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/navadhuvaaragai_yathirai
