### ISSUE TITLE
தகவல் பெறும் உரிமை சட்டம் ,2005 கையேடு வழிகாட்டி கையேடு

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Ebooks#383]
[TamilRTIAct.pdf](https://github.com/KaniyamFoundation/Ebooks/files/5684980/TamilRTIAct.pdf)

Licence CC-BY-SA

**Comment by gurulenin** [comment]
![rti](https://user-images.githubusercontent.com/15311390/103114376-4e680780-4684-11eb-99a6-4ce467b053e4.jpg)

**Comment by gurulenin** [comment]
![rti](https://user-images.githubusercontent.com/15311390/103114423-81120000-4684-11eb-9009-ef3ce4653cde.jpg)

**Comment by gurulenin** [comment]
@tshrinivasan please do ocr

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/rti_2005_guide
