### ISSUE TITLE
கற்பனையின் உணர்வுகள் - காவேரி நாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#387]
<strong> மின்னூல் பெயர்: </strong>கற்பனையின் உணர்வுகள்
<strong>ஆசிரியர் பெயர்: </strong>காவேரி நாதன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>nathan.kaveri@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>காவேரி நாதன்
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>nathan.kaveri@gmail.com
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=10MMKzGySv8vc-2vgDUpB740JTuWLrDYT
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1bQlC3rmpQNcCZfk7rPXguSVvVFlw5imu, https://drive.google.com/open?id=1xxU0_BEr6wrWi73GVHjpYde5gPe1Nr82

**Comment by gurulenin** [comment]
duplicate
