### ISSUE TITLE
தமிழ் இன்பம் - ரா.பி.சேதுப்பிள்ளை

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#39]
http://projectmadurai.org/pm_etexts/utf8/pmuni0485.html

**Comment by tshrinivasan** [comment]
![tamil-inbam](https://user-images.githubusercontent.com/1268536/38925335-ee0515f8-431c-11e8-8951-d1da7c1482b9.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/ThamizhInbam6Inch

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/tamil_inbam/
இங்கே வெளியிட்டுள்ளோம்
