### ISSUE TITLE
Siru kadhaigal - Raza mohamed

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#390]
<strong> மின்னூல் பெயர்: </strong>Siru kadhaigal
<strong>ஆசிரியர் பெயர்: </strong>Raza mohamed
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>razamohamed431@gmail.com 
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>Raza mohamed 
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>razamohamed431@gmail.com 
<strong>மின்னூலின் காப்புரிமை: </strong>Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=10xHa_dmib9VaAKclk3K4Xxnp_7MrcQbm
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1p2RllUyVqvuS7PntoJgLBJhiCCsEt-uK

**Comment by gurulenin** [comment]
spam/duplicate

இது ஏற்கனவே நம் தளத்தில் வெளியிடப்பட்ட மின்னூல்.
