### ISSUE TITLE
வீழ்வேன் என்று நினைத்தாயோ - ஜுலியா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#399]
<strong> மின்னூல் பெயர்: </strong>வீழ்வேன் என்று நினைத்தாயோ
<strong>ஆசிரியர் பெயர்: </strong>ஜுலியா
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>julia1975kptm@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>ஜூலியா
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>julia1975kptm@gmail.com
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=19Ff2nRy4oLyjC3-6-vXEv6U1Mekq6XDr
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=15r-8bjgzdYjIJTA-eS1GLI2usvlnnGL0

**Comment by tkdhanasekar** [comment]
this book with font size 28 came with 49 pages
but with FTE standards of font size 14 for A4 size
it came only 10 pages 
not enough 40 pages to process and release
