### ISSUE TITLE
கவியரசர் இரவீந்திரநாத் தாகூர் - என். வி. கலைமணி

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#402]
https://ta.wikisource.org/wiki/%E0%AE%95%E0%AE%B5%E0%AE%BF%E0%AE%AF%E0%AE%B0%E0%AE%9A%E0%AE%B0%E0%AF%8D_%E0%AE%87%E0%AE%B0%E0%AE%B5%E0%AF%80%E0%AE%A8%E0%AF%8D%E0%AE%A4%E0%AE%BF%E0%AE%B0%E0%AE%A8%E0%AE%BE%E0%AE%A4%E0%AF%8D_%E0%AE%A4%E0%AE%BE%E0%AE%95%E0%AF%82%E0%AE%B0%E0%AF%8D

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/poet_ravindranath_tagore
