### ISSUE TITLE
கம்பன் கண்ட ஆட்சியில் அரசியல் சமூகம்  (2005)  - குன்றக்குடி அடிகளார்

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#406]
https://ta.wikisource.org/s/9rjl

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/kamban_kanda_aatchiyil_arasiyal_samugam
