### ISSUE TITLE
ஆல்பர்ட் ஐன்ஸ்டைனின் நம்மை மேம்படுத்தும் எண்ணங்கள்  (1999)  ஆசிரியர் என். வி. கலைமணி

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#417]
https://ta.wikisource.org/s/97kh

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/thoughts_of_albert_einstein
