### ISSUE TITLE
தனித்தமிழ் மாட்சி - மறைமலை அடிகள்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#42]
http://projectmadurai.org/pm_etexts/utf8/pmuni0468.html

**Comment by gurulenin** [comment]
![tamil](https://user-images.githubusercontent.com/15311390/39084178-b0cf9072-458e-11e8-8e6b-c9adb183047e.jpg)

**Comment by tshrinivasan** [comment]
https://archive.org/details/thanithamizh_maatchi-2018-06-29-02-38-33

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/thanithamizh_maatchi/
