### ISSUE TITLE
லியோ டால்ஸ்டாயின் நம்மை மேம்படுத்தும் எண்ணங்கள்  (2001)  ஆசிரியர் என். வி. கலைமணி

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#424]
https://ta.wikisource.org/s/99wj

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/thoughts_of_leo_tolstoy
