### ISSUE TITLE
இரு அறிவியல் நண்பர்கள் - பொன் குலேந்திரன்

### ISSUE THREAD

**Issue by prasannaUDPM** [KaniyamFoundation/Ebooks#426]
மின்னூல் பெயர்   :    இரு அறிவியல் நண்பர்கள்
ஆசிரியர் பெயர்    : பொன் குலேந்திரன்
ஆசிரியர் மின்னஞ்சல் முகவரி : kulendiren2509@gmail.com 
அட்டைப்படம், மின்னூலாக்கம்     : பிரசன்னா, udpmprasanna@gmail.com 
எழுத்துப் பிழை திருத்தம் : வித்யா ஶீ, vidhyasreethirugnanam@gmail.com 
மின்னூலின் காப்புரிமை: Creative Commons Attribution -ShareAlike 
அட்டைப்படம், மின்னூலுக்கான கோப்பு : https://drive.google.com/drive/folders/1kly3Mw4pws-_oe0HtvbVAoKH8c0rakpk?usp=sharing

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/two_science_friends
