### ISSUE TITLE
சமுதாய வீதி (நாவல்) - தீபம் நா. பார்த்தசாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#43]
http://projectmadurai.org/pm_etexts/utf8/pmuni0458.html

**Comment by gurulenin** [comment]
![samuthayam](https://user-images.githubusercontent.com/15311390/38950693-f74bb26a-4363-11e8-82e4-4739fdc547ac.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Samuthaya_Veethi-2018-06-17-08-27-28

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/samuthaya_veethi/

released here
