### ISSUE TITLE
சொல் புதிது சுவை புதிது - எஸ் விஸ்வநாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#430]
<strong> மின்னூல் பெயர்: </strong>சொல் புதிது சுவை புதிது
<strong>ஆசிரியர் பெயர்: </strong>எஸ் விஸ்வநாதன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>vishwanathan71@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1JZo79Go4yOPZ0TI0elEpTRF-zN4isfnB

**Comment by gurulenin** [comment]
Duplicate
