### ISSUE TITLE
வாழ்க்கை  (1961)  - ஆசிரியர் லியோ டால்ஸ்டாய், மொழிபெயர்த்தவர் தியாகி ப. ராமசாமி

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#434]
https://ta.wikisource.org/s/9ai9

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/vaazhkai_leo_tolstoy
