### ISSUE TITLE
முதல் முத்துக்கள் - தஞ்சை கிருஷ்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#435]
<strong> மின்னூல் பெயர்: </strong>முதல் முத்துக்கள்
<strong>ஆசிரியர் பெயர்: </strong>தஞ்சை கிருஷ்ணா
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>thanjaikrishnapoet@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1oMmTdb34gaJ7mg5dEiiQH5UzIV8344vO
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1CHfm8-cfYPlsZyMlpoOXNSie8SEnhhj-

**Comment by gurulenin** [comment]
duplicate
