### ISSUE TITLE
முதல் முத்துக்கள் - தஞ்சை கிருஷ்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#437]
<strong> மின்னூல் பெயர்: </strong>முதல் முத்துக்கள்
<strong>ஆசிரியர் பெயர்: </strong>தஞ்சை கிருஷ்ணா
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>thanjaikrishnapoet@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1bj-mM0BrEZEzlVJyh9iXAtG_q51cdcR8
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1OWJi-2b8iNBpT7QzECyuPw4j3nVE5ywR

**Comment by rajjack** [comment]
வணக்கம்,
எனது நூலில் இருந்த எழுத்துப் பிழைகள் திருத்தி அனுப்பி உள்ளேன்.

மின்னூலாக்க ஆவன செய்யவும்.

நன்றி 

தஞ்சை கிருஷ்ணா
9790921049
நூல் : முதல் முத்துக்கள்
ஆசிரியர் : தஞ்சை கிருஷ்ணா

மின்னஞ்சல் : thanjaikrishnapoet@gmail.com

**Comment by rajjack** [comment]
வணக்கம்,
எனது நூலில் இருந்த எழுத்துப் பிழைகள் திருத்தி அனுப்பி உள்ளேன்.

மின்னூலாக்க ஆவன செய்யவும்.

நன்றி

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/muthal_muthukugal
