### ISSUE TITLE
வேர் விட்ட பூ - சங்கத் தமிழன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#439]
<strong> மின்னூல் பெயர்: </strong>வேர் விட்ட பூ
<strong>ஆசிரியர் பெயர்: </strong>சங்கத் தமிழன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>sangathamilan40@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>I no
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>I no
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1-VUirTNg5JjI11Nt_y6nzlwPW4MPln57

**Comment by gurulenin** [comment]
duplicate
