### ISSUE TITLE
கபாடபுரம் (சரித்திர நாவல்) - நா. பார்த்தசாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#44]
http://projectmadurai.org/pm_etexts/utf8/pmuni0454.html

**Comment by tshrinivasan** [comment]
![kabadapuram](https://user-images.githubusercontent.com/1268536/38923468-3e1ccb26-4318-11e8-82c5-ac4339121113.jpg)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/kabadapuram

**Comment by tshrinivasan** [comment]
add lines between paras for a4, 6 inch pdf

**Comment by tshrinivasan** [comment]
https://archive.org/details/kabadapuram_201806

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/kabadapuram/
