### ISSUE TITLE
ஏதேன் நகரம் - அ.இம்ரான்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#445]
<strong> மின்னூல் பெயர்: </strong>ஏதேன் நகரம்
<strong>ஆசிரியர் பெயர்: </strong>அ.இம்ரான்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>imranhak78@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1b4ibRTp2MGuNWDI-I6Y8LHPp3OiLMzPJ
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1nbkbMG4zAw7XTBEB_y3GaQnFUa_HvUMq

**Comment by gurulenin** [comment]
https://archive.org/details/athen_nagaram
