### ISSUE TITLE
தமிழ்மொழியின் வரலாறு - வி.கோ. சூரியநாராயண சாஸ்திரியார் (பரிதிமாற் கலைஞர்)

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#45]
http://projectmadurai.org/pm_etexts/utf8/pmuni0452.html

**Comment by gurulenin** [comment]
![tamil-lan-history](https://user-images.githubusercontent.com/15311390/38919303-da3f2310-430d-11e8-8238-ef959186cfb9.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Tamil_Mozhiyin_Varalaru-2018-09-29-08-19-18

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Tamil_Mozhiyin_Varalaru
