### ISSUE TITLE
சிந்தனைத் துளிகள் தவத்திரு குன்றக்குடி அடிகளார்

### ISSUE THREAD

**Issue by shivshankar31** [KaniyamFoundation/Ebooks#454]
[tamilebook.odt](https://github.com/KaniyamFoundation/Ebooks/files/7111147/tamilebook.odt)

Ebook creation : Shivshankar

s_shankar12@hotmail.com

Source : https://www.projectmadurai.org/pmworks.html

Thankyou!

**Comment by gurulenin** [comment]
https://freetamilebooks.com/ebooks/sinthanai_thuligal/


இங்கே ஏற்கனவே உள்ளது.

**Comment by tkdhanasekar** [comment]
புத்தகம் வெளியிடப்பட்டது 
இந்த issue முடித்துவைக்கப்படுகிறது
