### ISSUE TITLE
விதியை நிர்ணயிக்கும் ஆற்றல் - ஜேம்ஸ் ஆலன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#464]
<strong> மின்னூல் பெயர்: </strong>விதியை நிர்ணயிக்கும் ஆற்றல்
<strong>ஆசிரியர் பெயர்: </strong>ஜேம்ஸ் ஆலன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>arun2010g@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>சே.அருணாசலம்
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>arun2010g@gmail.com
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1OqOkE5UQrpx4hJLrpP4Q_D31K6qGuCyC
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=108J4m8kIf9m2VhhimNKDHav-1a28ly3p

**Comment by arun8939478** [comment]
[விதியை நிர்ணயிக்கும் ஆற்றல்--For FTE.docx](https://github.com/KaniyamFoundation/Ebooks/files/7198049/--For.FTE.docx)

**Comment by arun8939478** [comment]
இன்று 20.09.21---21.09.21  பிழைதிருத்தம் செய்யப்பட்ட நூலை மீண்டும் இணைத்திருக்கிறேன். மின்னூலாக்கத்திற்கு இந்த பிரதியை பயன்படுத்த வேண்டுகிறேன்.

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/the_mastery_of_destiny
