### ISSUE TITLE
உயிரின் உறவே - லாவண்யா ஶ்ரீராம் - நாவல்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#467]
மின்னூல் பெயர்: உயிரின் உறவே
ஆசிரியர் பெயர்: லாவண்யா ஶ்ரீராம்
ஆசிரியர் மின்னஞ்சல் முகவரி: lavanya.sriramprabhu@gmail.com
மின்னூலின் காப்புரிமை: Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
அட்டைப்படம்: - 
மின்னூலுக்கான கோப்பு: https://drive.google.com/file/d/1ct1qAd98vwJ72twkat6tm7g5W60tpoX8/view

**Comment by gurulenin** [comment]
![cover](https://user-images.githubusercontent.com/15311390/141668256-1b1898c3-d431-4741-a561-a7e9a5c32f2a.jpg)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/uyirin_uravae
