### ISSUE TITLE
குமரியின் மூக்குத்தி (சிறுகதைகள்) - கி. வா. ஜகந்நாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#47]
http://projectmadurai.org/pm_etexts/utf8/pmuni0424.html

**Comment by tshrinivasan** [comment]
![mukuthi](https://user-images.githubusercontent.com/1268536/39069089-4356d416-44fc-11e8-87ef-9907a24ee52e.jpg)

**Comment by manimaran96** [comment]
https://archive.org/details/Kumariyin_mukkutti_short_stories-2018-04-22-16-08-22

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/kumariyin_mukkutti_short_stories/
