### ISSUE TITLE
அற்புத மஹான் சாய்பாபா - B L ஷங்கர் - ஆன்மீகம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#471]
B L ஷங்கர் | blshankar77@gmail.com | 

 Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்) | 

அட்டை - https://drive.google.com/open?id=1TdeiRLD_jStkIhdrQLkgALg3nyWJYfGI | 
நூல் - https://drive.google.com/open?id=1llHPJpbUV7QSjq9mBPSEckL9ylOxoTJG |

**Comment by tkdhanasekar** [comment]
Not enough pages to make ebook , around 25 pages only there with vijaya font with 14 points
mail sent to author

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/arputha_mahaan_shirdi_saibaba
