### ISSUE TITLE
சேரன் செங்குட்டுவன் - மு. இராகவ ஐயங்கார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#48]
http://projectmadurai.org/pm_etexts/utf8/pmuni0404.html

**Comment by gurulenin** [comment]
![chera](https://user-images.githubusercontent.com/15311390/39093085-2afc8974-4637-11e8-9d51-f8cbb8269f3e.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/CheranSenguttuvan6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/cheran_senguttuvan
