### ISSUE TITLE
சுற்றம் சூழ  - லாவண்யா ஸ்ரீராம் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#480]
<strong> மின்னூல் பெயர்: </strong>சுற்றம் சூழ 
<strong>ஆசிரியர் பெயர்: </strong>லாவண்யா ஸ்ரீராம் 
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>lavanya.sriramprabhu@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1zVfp9xhFz8N3iWc5HOgaoTv6WrH93jsl

**Comment by lavanyasriram7** [comment]
@tshrinivasan - May I know why is my story not published yet. Could you please expedite this? I am eagerly looking forward to see this getting published.

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/sutram_soozha
