### ISSUE TITLE
நாலம்பல யாத்திரை - கைலாஷி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#481]
<strong> மின்னூல் பெயர்: </strong>நாலம்பல யாத்திரை
<strong>ஆசிரியர் பெயர்: </strong>கைலாஷி
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>muruganandams@rediffmail.com 
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1uqSxoJSQI3xf0YYl0L33bZVI7XWayQWG
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1GyePRkRulLpp2Ay32Dq4sk8nyyTMPpn9

**Comment by Jayasri03** [comment]
is this issue still open? can I do the ebook making of நாலம்பல யாத்திரை?

**Comment by tshrinivasan** [comment]
It is still open for making.

Please work on this.

Thanks.

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/nalambala_yathirai
