### ISSUE TITLE
லெனின் நான்கு கட்டுரைகள் - ஆர். பட்டாபிராமன்

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#484]
![Uploading cover.jpg…]()

**Comment by gurulenin** [comment]
![cover](https://user-images.githubusercontent.com/15311390/144960461-58ee270d-bbdc-433b-8397-664f16555376.jpg)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/lenin_four_essays
