### ISSUE TITLE
அருள் பொழியும் நிழல் பாதைகள்  - ஜேம்ஸ் ஆலன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#487]
<strong> மின்னூல் பெயர்: </strong>அருள் பொழியும் நிழல் பாதைகள் 
<strong>ஆசிரியர் பெயர்: </strong>ஜேம்ஸ் ஆலன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>arun2010g@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>சே.அருணாசலம்
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>arun2010g@gmail.com
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1EBhtjnt6Br-y_TLZPXxAKIijMALJ4OrG

**Comment by gurulenin** [comment]
updated
