### ISSUE TITLE
ஆத்மாவின் ராகங்கள் - தீபம் நா. பார்த்தசாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#49]
http://projectmadurai.org/pm_etexts/utf8/pmuni0402.html

**Comment by tshrinivasan** [comment]
![aathmavin-ragangal](https://user-images.githubusercontent.com/1268536/38923433-264799e0-4318-11e8-996b-6ab9938a2b59.jpg)

**Comment by tshrinivasan** [comment]
artist : த.சீனிவாசன் 
artist_email : tshrinivasan@gmail.com 
license : Public Domain - CCO
category : நாவல்

**Comment by rajiinperth** [comment]
https://archive.org/details/AthmavinRagangal6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/aathmaavin_ragangal
