### ISSUE TITLE
RAJAYOGAVASTU BOOK TAMIL - V.RAVI

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#492]
<strong> மின்னூல் பெயர்: </strong>RAJAYOGAVASTU BOOK TAMIL
<strong>ஆசிரியர் பெயர்: </strong>V.RAVI
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>rajayogavaastu1@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=10NL-X_wu_54Kz2kUhdoMj1HYDbZiatbQ
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1jOymfp0QDtukjOvdpVY6SAdjQuvV7v7P

**Comment by bsridev** [comment]
@tshrinivasan when we could expect this book published?

**Comment by tshrinivasan** [comment]
We need the books in Word document format with unicode font in Tamil.  Not in PDF format.

This books is uploaded as a PDF file. We can not convert the provided pdf file to epub, mobi .
Hence, we can not publish it.

Please share as Word document in Unicode Tamil font.

Thanks.
