### ISSUE TITLE
Kuberayoga Vastu Manaiyadi Sasthra kulikanakku  - Raja Guru V.Ravi

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#493]
<strong> மின்னூல் பெயர்: </strong>Kuberayoga Vastu Manaiyadi Sasthra kulikanakku 
<strong>ஆசிரியர் பெயர்: </strong>Raja Guru V.Ravi
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>rajayogavaastu1@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1d7D4KeMiDE9DZeos5pC_5HgTWP85OC6b
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=17S4aCqO9TIbPTCwgvNYwJkpnqZEhfOJB

**Comment by bsridev** [comment]
@tshrinivasan when we could expect this book published?

**Comment by tshrinivasan** [comment]
We need the books in Word document format with unicode font in Tamil.  Not in PDF format.

This books is uploaded as a PDF file. We can not convert the provided pdf file to epub, mobi .
Hence, we can not publish it.

Please share as Word document in Unicode Tamil font.

Thanks.
