### ISSUE TITLE
ஜனனி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#5]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0537.html

**Comment by tshrinivasan** [comment]
![janani](https://user-images.githubusercontent.com/1268536/38522508-74c5d8d8-3c66-11e8-9835-4d6024b6afdc.jpg)

**Comment by manimaran96** [comment]
https://archive.org/details/janani_short_stories-2018-06-24-16-30-17

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/janani_short_stories/
