### ISSUE TITLE
குறிஞ்சி மலர் - தீபம் நா. பார்த்தசாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#50]
http://projectmadurai.org/pm_etexts/utf8/pmuni0401_01.html  http://projectmadurai.org/pm_etexts/utf8/pmuni0401_02.html  http://projectmadurai.org/pm_etexts/utf8/pmuni0401_03.html

**Comment by tshrinivasan** [comment]
![kurinji-malar](https://user-images.githubusercontent.com/1268536/38921048-660d223a-4312-11e8-85ea-9e8c49c45267.jpg)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : த.சீனிவாசன்

tshrinivasan@gmail.com

உரிமை : Public Domain – CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/kurinjimalar_6_inch

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம்
http://freetamilebooks.com/ebooks/kurinji_malar
