### ISSUE TITLE
துருவங்கள் - நக்கீரன்.ந

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#500]
<strong> மின்னூல் பெயர்: </strong>துருவங்கள்
<strong>ஆசிரியர் பெயர்: </strong>நக்கீரன்.ந
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>n.keeran.kpm@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1gz--lA_Gyy0lOfZCxA1WYMjpO_mrj2Ju
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1SFSzbEtCsSLW3Nd8hg-qTTZ3SHniWWoQ

**Comment by n-keeran-kpm** [comment]
வணக்கம், என் சிறுகதையை நான் முன்பே தேவையான கோப்புகளாக உருவாக்கி உள்ளேன். இந்த கோப்புகளை பயன்படுத்த முடியுமா என்று பார்க்கவும்.

[dhuruvangal.zip](https://github.com/KaniyamFoundation/Ebooks/files/8583925/dhuruvangal.zip)

மேலும் இக்கதையின் மூலம் இங்கு உள்ளது

https://gitlab.com/n.keeran.kpm/dhuruvangal

ஏதேனும் மாற்றங்கள் இருப்பின் கூறுக.

**Comment by n-keeran-kpm** [comment]
இக்கதை கணியம் இதழின் தொடக்கத்தில் நான் இதே தலைப்பில் எழுதிய தொடரின் தொடர்ச்சியாகும். பாதியில் விட்ட அத்தொடரை முழுமையாக முடித்துள்ளேன்.

**Comment by mohan43u** [comment]
வணக்கம்

துருவங்கள் கதையை [freetamilebooks.com](http://freetamilebooks.com/) தளத்தில் வெளியிட ஏதேனும் முன்னேற்றம் இருந்தால் பகிரவும். புத்தகம் வெளியீட்டுக்காக ஆவலுடன் காத்திருக்கிறேன்.

இக்கதையின் மேன்படுத்தப்பட்ட கோப்புகள் இங்கே இருக்கின்றன

https://gitlab.com/n.keeran.kpm/dhuruvangal/-/jobs/2483969819/artifacts/download

ஏதேனும் மாற்றம் தேவைப்பட்டால் தெரியப்படுத்தவும்.

**Comment by tshrinivasan** [comment]
@gurulenin அட்டைப்படம் தருக.

@mohan43u @n-keeran-kpm எழுத்துப் பிழைகளைத் திருத்திக் கொண்டிருக்கிறேன்.

இந்த வாரத்தில் வெளியிடுவோம்.

**Comment by mohan43u** [comment]
@gurulenin அட்டைப்படத்தில் மறக்காமல் 11 = 10 | 01 என்று வருவதுபோல் வைக்கவும். ஏனென்றால் அதை வைத்து கதையின் இறுதியில் ஒரு காட்சி வருகின்றது.

@tshrinivasan தாங்கள் செய்யும் மாற்றங்களை என் ரெப்போவிலும் போடுங்கள். நானும் பயன்பெருவேன்.

**Comment by n-keeran-kpm** [comment]
@gurulenin மறக்காமல் 11 = 10 | 01 என்பதை அட்டைப்படத்தில் வருமாறு வைக்கவும். இதை வைத்து ஒரு காட்சி கதையில் வருகின்றது

@tshrinivasan தங்கள் மாற்றங்களை என் ரெப்போவில் உள்ள மேம்படுத்தப்பட்ட கோப்புகளில் இருந்து எடுத்து செய்யுமாறு கேட்டுக்கொள்கின்றேன். மேலும் தங்கள் மாற்றங்களை எனக்கும் அனுப்பி வைக்கவும். நானும் பயன் அடைவேன். என் மேம்படுத்தப்பட்ட கோப்புகள் இங்கே உள்ளன.

https://gitlab.com/n.keeran.kpm/dhuruvangal

**Comment by parameshwar-A** [comment]
Fonts used :
Catamaran
Fira Sans
Kavivanar
(All are open source fonts. Kindly double check)

Kindly take a look at my book cover design for dhuruvangal.
Let me know if any corrections needed.

![Dhuruvangal_cover](https://user-images.githubusercontent.com/63645998/176992472-f9a1dd28-e3da-4f00-8dfa-69450d1710a5.jpg)


Thanks and Regards,
Parameshwar Arunachalam
stark20236@gmail.com

**Comment by n-keeran-kpm** [comment]
@parameshwar-A நன்றி நன்பரே. அழகாக உள்ளது. தலைப்பின் பாண்ட் மட்டும் சற்று சிரியதாகவும், நேரே உள்ளவாரும் இருந்தால் நன்றாக இருக்கும். மேலும் எழுத்தாளர் பெயரும் சிரியதாக இருந்தால் நன்றாக இருக்கும். 

`man man` மற்றும் `man ls` மிகவும் நெருக்கமாக உள்ளது போன்று உள்ளது. அதை எடுத்துவிட்டாலே நன்றாகத்தான் இருக்கும். வெரும் கருப்பு வெள்ளை டெர்மினல் வைத்தாலே நன்றாக இருக்கும்.

`btw` சேர்த்து இருப்பது அம்சமாக உள்ளது.

**Comment by n-keeran-kpm** [comment]
@tshrinivasan தாங்கள் பகிர்ந்த பிழை திருத்தம் செய்யப்பட்ட கோப்புகளை என் கிட் ரெப்போவில் சேர்த்துவிட்டேன். அதன் பதிப்பு இங்கே உள்ளன.

https://gitlab.com/n.keeran.kpm/dhuruvangal/-/releases/v0.5.9

**Comment by parameshwar-A** [comment]
![Dhuruvangal_cover](https://user-images.githubusercontent.com/63645998/177022218-02fecdd4-9d12-444f-a64f-991f0e110e97.jpg)

I have made the changes suggested.
The tamil fonts is plain(I know only few tamil font types). If you have any specific font in mind. Let me know I can change
I made a small color corrections.

Hope you like the design 
If you want any corrections, feel free to let me know

Thanks and Regards,
Parameshwar Arunachalam
[stark20236@gmail.com](mailto:stark20236@gmail.com)

**Comment by n-keeran-kpm** [comment]
@parameshwar-A துருவங்கள் திட்டத்தில் உருவாக்கப்பட்டும் A4 pdf கோப்பில் பயன்படுத்தப்படும் மாற்றியமைக்கப்பட்ட Marutham தமிழ் உருவை பயன்படுத்த முடியுமா என்று பார்க்கவும்.

https://gitlab.com/n.keeran.kpm/dhuruvangal/-/tree/master/docs/fonts/Marutham

மேலும்  இங்கே வட்டமிடப்பட்டுள்ள இடத்தை மட்டும் நீக்கவிடவும். பின்புறம் (Background) மிகவும் பிளெய்னாக உள்ளது. அதில் முன்புறத்திற்று (Foreground) எந்த பாதிப்பும் இல்லாமல் ஏதேனும் பேட்டர்ன் (Pattern) வைக்க முடியுமா என்று பார்க்கவும்.

![correction](https://user-images.githubusercontent.com/104580168/177029769-c1004e4c-0d73-403a-8412-a25b14c699e9.jpg)

**Comment by parameshwar-A** [comment]
![Dhuruvangal_cover](https://user-images.githubusercontent.com/63645998/177183025-919ed719-73f6-49df-91cd-a4da5bb43500.jpg)

**Comment by mohan43u** [comment]
@tshrinivasan துருவங்கள் இதழுக்கு வந்த அணிந்துரைகளை இணை்த்து புதிய பதிப்பு வெளியிட்டுள்ளேன். அணிந்துரைகள் கதையை பற்றி படிக்க பெரும் ஆவலை தூண்டும் விதமாக அமைந்துள்ளது.

https://gitlab.com/n.keeran.kpm/dhuruvangal/-/jobs/2731365975/artifacts/download

**Comment by n-keeran-kpm** [comment]
துருவங்கள் கதைக்கு வந்த அணிந்துரைகள் சேர்க்கப்பட்டு புதிய பதிப்பு வெளியிடப்பட்டுள்ளது. அணிந்துரைகள் அணைத்தும் கதையை படிக்கும் ஆர்வத்தை மிகவும் தூண்டுவதாக அமைந்துள்ளது. அணிந்துரையை வழங்கிய @tshrinivasan , @parameshwar-A மற்றும் @muthu1809 மூவருக்கும் மிக்க நன்றி.

https://gitlab.com/n.keeran.kpm/dhuruvangal/-/releases/v0.6.0

**Comment by n-keeran-kpm** [comment]
அணிந்துரையில் இருந்த எழுத்துப்பிழைகள் திருத்தப்பட்டு புதிய பதிப்பு வெளியிடப்பட்டுள்ளது. மீண்டும் @muthu1809 அவர்களுக்கு நன்றி.

https://gitlab.com/n.keeran.kpm/dhuruvangal/-/releases/v0.6.1

**Comment by gurulenin** [comment]
![dhuruvangal](https://user-images.githubusercontent.com/15311390/179453486-daee829d-4d60-4ade-bda6-0ee1e5ba5f20.png)

**Comment by n-keeran-kpm** [comment]
அட்டைப்படம் உருவாக்க உருதுனையாக இருக்கும் @parameshwar-A மற்றும் @gurulenin இருவருக்கும் மிக்க நன்றி.

இறுதியாக உள்ள அட்டைப்படம் அட்டகாசமாக வந்துள்ளது. ஒரே ஒரு வேண்டுகோள், இரு கணினிகளுக்கு கொடுக்கப்பட்டுள்ள நிரமும் இசை பிரதிபளிக்கும் வடிவத்தின் நிரமும் ஒன்றாக உள்ளது. எனவே, கணினிகளின் நிரத்தை மட்டும் வேறு நிரத்திற்கு மாற்றிவிட்டால் அட்டைப்படம் அருமையாக இருக்கும்.

இருவருக்கும் மிக்க நன்றி.

**Comment by n-keeran-kpm** [comment]
@gurulenin எனக்கு தெரிந்த கிம்ப் உபயோகித்து மேற்கூறிய மாறுதல்களை செய்துள்ளேன். என்னால் சில இடங்களை அழிக்க முடியவில்லை. தங்களிடம் உள்ள நிழற்படத்தில் சரியாக மாற்றம் செய்து கொடுத்தால் அட்டைப்படம் இறுதி வடிவம் பெற்று விடும்.

![cover-image](https://user-images.githubusercontent.com/104580168/179507430-2f2c0aac-15f4-4a5f-ac4d-e0676d295260.png)

**Comment by gurulenin** [comment]
![dhuruvangal](https://user-images.githubusercontent.com/15311390/179512030-b207e422-1f46-4b7e-ad73-239c9db1b968.png)
![image4223-5](https://user-images.githubusercontent.com/15311390/179512039-4e786bb6-ca80-47eb-aac9-7022f98a6651.png)

**Comment by n-keeran-kpm** [comment]
@gurulenin கேபின் கோடுகள் அதிகமாக சேர்த்தால் மிகவும் சிக்கலாக இருந்தது. சற்றே மாற்றியுள்ளேன்.

![cover-image](https://user-images.githubusercontent.com/104580168/179512673-9c5a3844-45d8-47b4-9bc0-a64477f5a4ae.png)

**Comment by n-keeran-kpm** [comment]
@gurulenin இறுதி வடிவம் வந்துவிட்டது. இதுவே போதும். தங்களுக்கும் இந்த அட்டைப்படத்திற்கான யோசனையை கொடுத்து முதல் பதிப்புகளை கொடுத்து உதவிய @parameshwar-A அவர்களுக்கும் மிக்க நன்றி.
 
![cover-image](https://user-images.githubusercontent.com/104580168/179515249-025f1153-22a4-4ace-849e-c6a4cc9a925d.png)

**Comment by n-keeran-kpm** [comment]
அட்டைப்படம் சேர்க்கப்பட்ட புதிய பதிப்பு வெளியாகி உள்ளது. துருவங்கள் மின் புத்தக வடிவில் வெளியிட தயாராக இருக்கின்றது என்று நம்புகிறேன். இதற்காக துணைநின்ற @muthu1809 , @parameshwar-A , @gurulenin , @tshrinivasan அனைவருக்கும் என் மனமார்ந்த நன்றிகள்.

https://gitlab.com/n.keeran.kpm/dhuruvangal/-/releases/v0.6.2

விரைவில் இக்கதை புத்தக வடிவில் வெளிவர ஆவலாக உள்ளேன்.

**Comment by n-keeran-kpm** [comment]
@tshrinivasan , தாங்கள் கேட்டுக்கொண்டது போல் முகப்புப் பக்கத்தில் மாற்றங்கள் செய்து புதிய பதிப்பு வெளியாகி உள்ளது. இப்புத்தகம் வடிவம் பெற துணைநின்ற @muthu1809, @parameshwar-A , @gurulenin , @tshrinivasan அனைவருக்கும் மீண்டும் ஒருமுறை என் மனமார்ந்த நன்றி

https://gitlab.com/n.keeran.kpm/dhuruvangal/-/releases/v0.6.3

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/dhuruvangal

**Comment by muthu1809** [comment]
மகிழ்ச்சி. முதலில் தரவிறக்கியாச்சு. இன்னும் கொஞ்சம் பிழைகளைத் திருத்திக்
கொண்டிருக்கிறேன். அவற்றையும் கிட்டில் சேர்க்கிறேன். கொஞ்சம் மாற்றி வெளியிட
வேண்டுகிறேன்.

சனி, 23 ஜூலை, 2022, முற்பகல் 8:14க்கு, Shrinivasan T <
***@***.***> எழுதியது:

**Comment by tshrinivasan** [comment]
removed the published item.

waiting for @muthu1809 to complete fixing spell errors.

we can release again once fixed.

**Comment by n-keeran-kpm** [comment]
இப்புத்தகம் உருவாக துணையாக நின்ற @tshrinivasan , @gurulenin , @parameshwar-A அணைவருக்கும் என் நன்றிகள். @muthu1809 அவர்களுக்கு எவ்வாறு நன்றி கூறுவது என்று தெரியவில்லை, அவருக்கு நான் என்றும் கடமைப்பட்டுள்ளேன். பிழைகள் திருத்தப்பட்ட புதிய பதிப்பு இதோ.

https://gitlab.com/n.keeran.kpm/dhuruvangal/-/releases/v0.6.4

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/dhuru_vangal
