### ISSUE TITLE
இந்திய மாநிலப் பறவைகள் - ஏற்காடு இளங்கோ

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#502]
<strong> மின்னூல் பெயர்: </strong>இந்திய மாநிலப் பறவைகள்
<strong>ஆசிரியர் பெயர்: </strong>ஏற்காடு இளங்கோ
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>yercaudelango@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு:  [India Manila Paravaikal(1).docx](https://github.com/KaniyamFoundation/Ebooks/files/8687866/India.Manila.Paravaikal.1.docx)

**Comment by gurulenin** [comment]
![indian-birds](https://user-images.githubusercontent.com/15311390/180451837-98e3dc43-d67e-4229-a292-38b1241f568c.png)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/indian_state_birds
