### ISSUE TITLE
Arputha mahaan shirdi saibaba  - B L Shankar

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#504]
<strong> மின்னூல் பெயர்: </strong>Arputha mahaan shirdi saibaba 
<strong>ஆசிரியர் பெயர்: </strong>B L Shankar
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>blshankar77@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1N3CIKv0cK-pFaRHJg7x-1UrgnX6ojR64
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1uT55h_nFqrWkZF6JWKBeFiU5YOznKVST

**Comment by tkdhanasekar** [comment]
srini the author is wrong , he sent the latest version in pdf and old version in .odt 
then how could we process it 
plz donot process it wait

**Comment by tkdhanasekar** [comment]
i will assign this book to me , i m working on this book

**Comment by tkdhanasekar** [comment]
plz kindly any of the team members work on this

**Comment by tshrinivasan** [comment]
@tkdhanasekar is the book content here is updated one?

@gurulenin can you work on this and republish?

**Comment by tkdhanasekar** [comment]
@tshrinivasan yes the book content here is the updated one , i m sure and cross check with the author

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/arputha_mahaan_shirdi_saibaba
