### ISSUE TITLE
எல்லாரும் முட்டாள்கள் -- என்னைத்தவிர - நிர்மலா ராகவன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#507]
<strong> மின்னூல் பெயர்: </strong>எல்லாரும் முட்டாள்கள் -- என்னைத்தவிர
<strong>ஆசிரியர் பெயர்: </strong>நிர்மலா ராகவன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>nirurag@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=19rlBDiVoSo9r8UEgKfgGhayEfv5K0wfX

**Comment by gurulenin** [comment]
![muttalgal](https://user-images.githubusercontent.com/15311390/180440929-0cededee-1915-4b97-a539-70280adfb754.png)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/ellarum_muttalgal_ennai_thavira
