### ISSUE TITLE
முகநூலும் முத்துலட்சுமியும் - நிர்மலா ராகவன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#508]
<strong> மின்னூல் பெயர்: </strong>முகநூலும் முத்துலட்சுமியும்
<strong>ஆசிரியர் பெயர்: </strong>நிர்மலா ராகவன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>nirurag@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1uX02tX4ull_155ZOh91stV_7IFJdoUEP

**Comment by gurulenin** [comment]
![fb](https://user-images.githubusercontent.com/15311390/187034361-3726caff-bc2c-46f6-9c13-a91cf61c3701.jpg)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/fb_and_muthulakshmi
