### ISSUE TITLE
சமூகப் பெண் போராளிகள் - ஏற்காடு இளங்கோ

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#510]
<strong> மின்னூல் பெயர்: </strong>சமூகப் பெண் போராளிகள்
<strong>ஆசிரியர் பெயர்: </strong>ஏற்காடு இளங்கோ
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>yercaudelango@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1wHShYgqVotSqC0ZZmiSJ_rg8p8bcWxSl

**Comment by gurulenin** [comment]
![women](https://user-images.githubusercontent.com/15311390/187035918-c2370116-eb13-4b47-a30c-5f45029a55c1.jpg)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/social_woman_activists
