### ISSUE TITLE
  சடையப்ப வள்ளல் - கம்பர் காவலர் - கோவி. ஜெயராமன்

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Ebooks#511]
[jaya.pdf](https://github.com/KaniyamFoundation/Ebooks/files/9141177/jaya.pdf)

**Comment by gurulenin** [comment]
![sadaiyappan-low](https://user-images.githubusercontent.com/15311390/179755903-da77ac71-0630-4929-8414-ec63c642035c.jpg)

**Comment by gurulenin** [comment]
[sadai.txt](https://github.com/KaniyamFoundation/Ebooks/files/9287313/sadai.txt)

**Comment by gurulenin** [comment]
[images.zip](https://github.com/KaniyamFoundation/Ebooks/files/9335123/images.zip)

**Comment by gurulenin** [comment]
[sadai.docx](https://github.com/KaniyamFoundation/Ebooks/files/9400379/sadai.docx)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/sadaiyappa_vallal_kambar_kavalar
