### ISSUE TITLE
புதுமைப்பித்தன் படைப்புகள் - சிறுகதைகள்; தொகுப்பு - 1 & 2 - புதுமைப்பித்தன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#52]
http://projectmadurai.org/pm_etexts/utf8/pmuni0389_01.html http://projectmadurai.org/pm_etexts/utf8/pmuni0389_02.html

**Comment by gurulenin** [comment]
![puthumaipithan](https://user-images.githubusercontent.com/15311390/39033793-688b7f22-4491-11e8-87c4-718f50174499.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Puthumaipithan_Padaipugal-2018-10-02-07-27-36

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Puthumaipithan_Padaipugal_part_1_and_2
