### ISSUE TITLE
பொய்மான் கரடு - கல்கி கிருஷ்ணமூர்த்தி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#53]
http://projectmadurai.org/pm_etexts/utf8/pmuni0384.html

**Comment by prasannaUDPM** [comment]
I take this...

**Comment by prasannaUDPM** [comment]
Link : https://archive.org/details/poimaan_karadu 
thank you

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/poiman_karadu/
