### ISSUE TITLE
மாந்தருக்குள் ஒரு தெய்வம் (1; 2) - கல்கி கிருஷ்ணமூர்த்தி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#54]
http://projectmadurai.org/pm_etexts/utf8/pmuni0385_01.html http://projectmadurai.org/pm_etexts/utf8/pmuni0385_02.html

**Comment by gurulenin** [comment]
![human](https://user-images.githubusercontent.com/15311390/39037261-903b27aa-449d-11e8-9d62-40b0e175efb2.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Mantharukkul_Oru_Theivam-2019-01-16-07-57-02

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/Mantharukkul_Oru_Theivam

இங்கே வெளியிட்டுள்ளோம்
