### ISSUE TITLE
தியாக பூமி - கல்கி கிருஷ்ணமூர்த்தி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#55]
http://projectmadurai.org/pm_etexts/utf8/pmuni0376.html

**Comment by gurulenin** [comment]
![boomi](https://user-images.githubusercontent.com/15311390/39034466-1c2053f8-4494-11e8-85ed-231e806edc95.jpg)

**Comment by tshrinivasan** [comment]
cover image = லெனின் குருசாமி guruleninn@gmail.com
license - Public Domain -CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/ThiyagaBoomi6Inch

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம்.
http://freetamilebooks.com/ebooks/Thiyaga_Boomi
