### ISSUE TITLE
புது மெருகு (சிறுகதைத் தொகுப்பு) - கி. வா. ஜகந்நாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#56]
http://projectmadurai.org/pm_etexts/utf8/pmuni0341.html

**Comment by tshrinivasan** [comment]
![puthu-merugu](https://user-images.githubusercontent.com/1268536/39068727-e879f074-44fa-11e8-9b8a-908ffd3ff499.jpg)

**Comment by arun8939478** [comment]
https://archive.org/details/putu_meruku-2018-04-22-16-11-28

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/putu_meruku/

இங்கே வெளியிட்டுள்ளோம்
