### ISSUE TITLE
சோலைமலை இளவரசி - கல்கி கிருஷ்ணமூர்த்தி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#57]
http://projectmadurai.org/pm_etexts/utf8/pmuni0228.html

**Comment by gurulenin** [comment]
![solai](https://user-images.githubusercontent.com/15311390/39092253-6a83af4c-4627-11e8-9462-8b5b4d1a7f07.jpg)

**Comment by tshrinivasan** [comment]
Uploaded to https://archive.org/details/solaimalai_ilavarasi-2018-04-22-18-29-15

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/solaimalai_ilavarasi/

released here
