### ISSUE TITLE
சந்திரிகையின் கதை - சி. சுப்ரமணிய பாரதியார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#58]
http://projectmadurai.org/pm_etexts/utf8/pmuni0095.html

**Comment by balaaagi** [comment]
![selection_057](https://user-images.githubusercontent.com/2221784/39085530-76e716ba-45a1-11e8-839c-69e32ed310f2.png)

**Comment by tshrinivasan** [comment]
Thanks @balaaagi 
The above image is low resolution and copyrighted.
We can not use it.

We have to make a new one ourself.

**Comment by gurulenin** [comment]
![santhirigai](https://user-images.githubusercontent.com/15311390/39093431-71eebce8-463d-11e8-9308-71e2c8ce180a.jpg)

**Comment by rajarethinam0** [comment]
[சந்திரிகையின் கதை - பாரதியார்.txt](https://github.com/KaniyamFoundation/Ebooks/files/1935666/-.txt)

**Comment by rajarethinam0** [comment]
someone make as ebooks formats

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : லெனின் குருசாமி

guruleninn@gmail.com

**Comment by rajiinperth** [comment]
https://archive.org/details/chandrikaiyinkathai_6_inch

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/chandrikaiyin_kathai
இங்கு வெளியிட்டுள்ளோம்
