### ISSUE TITLE
சில திரைப்படங்களும் சில கோட்பாடுகளும் - லூத்விக் ஆலன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#583]
<strong> மின்னூல் பெயர்: </strong>சில திரைப்படங்களும் சில கோட்பாடுகளும்
<strong>ஆசிரியர் பெயர்: </strong>லூத்விக் ஆலன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>Lotsofcinema@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>லூத்விக்
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1ZsuN8vTxGKrNf5YLLBP2TFguuF4s8fyx
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1t09lDmRAf-Ldi-ZakNE3-stgepfj71sx

**Comment by gurulenin** [comment]
[some-theories-in-movies.txt](https://github.com/KaniyamFoundation/Ebooks/files/10751930/some-theories-in-movies.txt)

**Comment by vigsrox** [comment]
can i work on this ? or is some one else working on it?

**Comment by tshrinivasan** [comment]
Please work on this.

Thanks.

**Comment by vigsrox** [comment]
I have finished creating this book. There are some pictures in the book,  the author needs to be contacted about license for the pictures before releasing book. I sent the completed books to freetamilebooksteam@gmail.com  and recieved email stating that i should send the email to freetamilebooks forum.  But  I dont see the a topic with the author or book name. should i create a new topic?

How to proceed here?

**Comment by tshrinivasan** [comment]
I got the email.

Will check the files and share any feedback.

Thanks for the contributions.

**Comment by gurulenin** [comment]
https://freetamilebooks.com/ebooks/some_theories_in_the_movies_tamil/
