### ISSUE TITLE
விண்மீன் பூக்கள் - தி.வேதரெத்தினம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#589]
<strong> மின்னூல் பெயர்: </strong>விண்மீன் பூக்கள்
<strong>ஆசிரியர் பெயர்: </strong>தி.வேதரெத்தினம்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>kabilanvedharethinam96@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1V3_OeVibi31KvwPIsSOOkCpbExLQ7lM4

**Comment by gurulenin** [comment]
duplicate
