### ISSUE TITLE
சோழர் வரலாறு - மா. இராசமாணிக்கனார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#60]
https://ta.wikisource.org/s/8v1c

**Comment by gurulenin** [comment]
![chola](https://user-images.githubusercontent.com/15311390/38918624-e8de3d18-430b-11e8-88f9-502c8cbd5c9d.jpg)

**Comment by tshrinivasan** [comment]
cover image = லெனின் குருசாமி guruleninn@gmail.com
license - Public Domain -CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/CholarVaralaru6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Cholar_Varalaru

**Comment by tkdhanasekar** [comment]
http://freetamilebooks.com/ebooks/Cholar_Varalaru

above link redirecting to spam pages


regards,

T.Dhanasekar

**Comment by tshrinivasan** [comment]
@dna80

try in different browser and private mode.

if still redirects to spam page,
attach a screenshot here.

**Comment by tkdhanasekar** [comment]
tried firefox redirects to spam page
attached screenshot


regards,

T.Dhanasekar

**Comment by gurulenin** [comment]
For me too...

Whole site redirects to spam page..

In mobile site works fine.

**Comment by tkdhanasekar** [comment]
tried in chromium incognito mode and normal mode redirect to spam page
tried in firefox incognito mode and normal mode redirect to spam page
![screenshot from 2018-10-10 14-08-15](https://user-images.githubusercontent.com/38269533/46724019-c8c03300-cc96-11e8-9f2c-2f645f84bd2b.png)
![screenshot from 2018-10-10 14-07-59](https://user-images.githubusercontent.com/38269533/46724020-c8c03300-cc96-11e8-9892-e9236093e0fe.png)
![chromium- private mode](https://user-images.githubusercontent.com/38269533/46724023-c958c980-cc96-11e8-9c00-82b39b69b796.png)
![chromium normal mode](https://user-images.githubusercontent.com/38269533/46724025-c958c980-cc96-11e8-9845-721e24b4cd36.png)

**Comment by tkdhanasekar** [comment]
by morning 7.30 AM 11-10-2018  fte site works correctly
but as of now redirects to spam page
set nameserver to 8.8.8.8 still redirects to spam page
net connection using jio and bsnl BB

**Comment by srikanthlogic** [comment]
Can you check in Inspect element  for any third party javascript that loads on the site? Also try Brave browser / use https://www.ublock.org/ and try the same?

**Comment by gnuanwar** [comment]
Tried chrome bsnl mobile data at 11/10/18 7.40 am working fine no spam
