### ISSUE TITLE
காலம் மறைத்த மக்கள் - சு.சோமு

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#601]
<strong> மின்னூல் பெயர்: </strong>காலம் மறைத்த மக்கள்
<strong>ஆசிரியர் பெயர்: </strong>சு.சோமு
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>sundaram.somu@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1GAkFgJixJXmE1gCP1-sY79roydsPDDbv

**Comment by gurulenin** [comment]
![1](https://user-images.githubusercontent.com/15311390/214593220-2f290a31-29d4-46f5-a8c6-b23107a0864a.png)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/kaalam_maraitha_makkal
