### ISSUE TITLE
சாத்தானின் பாதச் சுவடுகள் - சு.சோமு

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#602]
<strong> மின்னூல் பெயர்: </strong>சாத்தானின் பாதச் சுவடுகள்
<strong>ஆசிரியர் பெயர்: </strong>சு.சோமு
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>sundaram.somu@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1EOInHJnK10_fQorkpSsrJDgFpIStLbGC

**Comment by gurulenin** [comment]
![2](https://user-images.githubusercontent.com/15311390/214593177-a791aad8-e1db-46a0-87c7-262017f02123.png)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/saathanin_patha_suvadugal
