### ISSUE TITLE
சிகப்பு வட்ட மர்மம் - சு.சோமு

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#603]
<strong> மின்னூல் பெயர்: </strong>சிகப்பு வட்ட மர்மம்
<strong>ஆசிரியர் பெயர்: </strong>சு.சோமு
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>sundaram.somu@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1F_hFCC7b9yrcgFZ7OwjLcpIvo9s8mI21

**Comment by gurulenin** [comment]
![3](https://user-images.githubusercontent.com/15311390/214592229-f021165d-787e-4508-8a71-369b2061de4c.png)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/secret_of_red_circle
