### ISSUE TITLE
பாஸ்கோம் பள்ளத்தாக்கு மர்மம் - சு.சோமு

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#605]
<strong> மின்னூல் பெயர்: </strong>பாஸ்கோம் பள்ளத்தாக்கு மர்மம்
<strong>ஆசிரியர் பெயர்: </strong>சு.சோமு
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>sundaram.somu@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=12pjDYmiNqeR9KA4ZHBIXLK1LNOFyLwIX

**Comment by gurulenin** [comment]
![5](https://user-images.githubusercontent.com/15311390/214592294-6a0365d3-1bc8-4172-8ad6-46c3169ece99.png)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/secrets_of_paskom_valley
