### ISSUE TITLE
இதர ஜப்பானியக் கதைகள் - சு.சோமு

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#607]
<strong> மின்னூல் பெயர்: </strong>இதர ஜப்பானியக் கதைகள்
<strong>ஆசிரியர் பெயர்: </strong>சு.சோமு
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>sundaram.somu@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1tBKy3UoQKQ9Y5ocUGLDkqQyylZHag3UL

**Comment by gurulenin** [comment]
![4](https://user-images.githubusercontent.com/15311390/214593279-fb1684b3-2934-4fd6-bf85-077a22ef8974.png)

**Comment by gurulenin** [comment]
https://freetamilebooks.com/ebooks/other_japanese_stories/
