### ISSUE TITLE
அழகின் சிரிப்பு - பாவேந்தர் பாரதிதாசன் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#61]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0037.html

**Comment by tshrinivasan** [comment]
![alagin-sirippu](https://user-images.githubusercontent.com/1268536/39064791-503337b0-44ed-11e8-8842-26ddfe21805d.jpg)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : த.சீனிவாசன் - tshrinivasan@gmail.com
உரிமை: Public Domain-CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/AzhaginSirippu6inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/azhagin_sirippu/
