### ISSUE TITLE
எழுத்துநடையின் செந்தரம் - செயபாண்டியன் கோட்டாளம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#610]
<strong> மின்னூல் பெயர்: </strong>எழுத்துநடையின் செந்தரம்
<strong>ஆசிரியர் பெயர்: </strong>செயபாண்டியன் கோட்டாளம்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>jkottalam@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1XGdEB9FJoF_s6Gf5ktLkc9f5BflaXodt
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=174vZEm_xzot9GqxoZFPNImQ-otb1ZJvj

**Comment by gurulenin** [comment]
https://freetamilebooks.com/ebooks/ezhuthunadaiyin_sentharam/
