### ISSUE TITLE
சம் தியரீஸ் இன் திமூவிஸ்

### ISSUE THREAD

**Issue by sakthizxc** [KaniyamFoundation/Ebooks#619]
மின்னூல் பெயர்:  சம் தியரீஸ் இன் திமூவிஸ்
ஆசிரியர் பெயர்:  லூத்விக் ஆலன்
ஆசிரியர் மின்னஞ்சல் முகவரி: -
மொழிபெயர்ப்பாளர் பெயர்:  
மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி:  
மின்னூலின் காப்புரிமை: Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
அட்டைப்படம்:
மின்னூலுக்கான கோப்பு: https://drive.google.com/drive/my-drive

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/some_theories_in_the_movies_tamil
