### ISSUE TITLE
சிகப்பு வட்ட மர்மம்

### ISSUE THREAD

**Issue by mdzr7** [KaniyamFoundation/Ebooks#620]
மின்னூல் பெயர்: சிகப்பு வட்ட மர்மம்
ஆசிரியர் பெயர்: சு.சோமு
மொழிபெயர்ப்பாளர் பெயர்: முஹம்மது ஜீஹைர்
மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: smszuhair@gmail.com
மின்னூலின் காப்புரிமை: Public Domain ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
அட்டைப்படம்: லெனின் குருசாமி
லெனின் குருசாமி மின்னஞ்சல் : guruleninn@gmail.com
மின்னூலுக்கான கோப்பு: https://drive.google.com/drive/folders/1NcSTJH0jWmYjyMbNkkpr9xi8s7GM_xUQ?usp=share_link

**Comment by gurulenin** [comment]
https://freetamilebooks.com/ebooks/secret_of_red_circle/
