### ISSUE TITLE
எழு  - காமேஷ் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#622]
<strong> மின்னூல் பெயர்: </strong>எழு 
<strong>ஆசிரியர் பெயர்: </strong>காமேஷ் 
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>kameshvimala14@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=19wDC62egKf7O2tJ27cHBdVvZTYqvlggN
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1TapYt73yn-tZCtj-5PNW5RaRu-U69_Zy

**Comment by gurulenin** [comment]
published
