### ISSUE TITLE
விழிகளில் தெரிகிறது வெளிச்சம் - வேதரெத்தினம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#636]
<strong> மின்னூல் பெயர்: </strong>விழிகளில் தெரிகிறது வெளிச்சம்
<strong>ஆசிரியர் பெயர்: </strong>வேதரெத்தினம்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>Kabilanvedharethinam96@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1blJarJUmKqk5n7_5ojsNeaHWZHW8u0pY
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1XoZQVjoz7kuySJQ46H-negZEim9Vya2p

**Comment by gurulenin** [comment]
duplicate
