### ISSUE TITLE
அனைத்திற்குமான கோட்பாடு - ஸ்டீபன் ஹாக்கிங்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#641]
<strong> மின்னூல் பெயர்: </strong>அனைத்திற்குமான கோட்பாடு
<strong>ஆசிரியர் பெயர்: </strong>ஸ்டீபன் ஹாக்கிங்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>Kabilanvedharethinam96@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>கபிலன் வேதரெத்தினம்
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -ShareAlike ( யாரும் பகிரலாம், விற்பனை செய்யலாம்)
<strong>அட்டைப்படம்: </strong>https://drive.google.com/open?id=1Epv5eIW7BcgsSgBgmug-AjmaLQRDg1HO
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=14Lz3Gg43HK7CVAWT6Qfo3lzygSgNndGe

**Comment by gurulenin** [comment]
https://freetamilebooks.com/ebooks/theory_of_everything/
