### ISSUE TITLE
காதல் நினைவுகள் - பாவேந்தர் பாரதிதாசன் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#65]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0090.html

**Comment by gurulenin** [comment]
![love](https://user-images.githubusercontent.com/15311390/39034950-e781f352-4495-11e8-8d0f-bee1111733c8.jpg)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : லெனின் குருசாமி - guruleninn@gmail.com
உரிமை: Public Domain-CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/KadhalNinaivugal6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/kadhal_ninaivugal/
