### ISSUE TITLE
பாண்டியன் பரிசு - பாவேந்தர் பாரதிதாசன் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#66]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0104.html

**Comment by tshrinivasan** [comment]
![pandiyan-parisu](https://user-images.githubusercontent.com/1268536/39065495-95c5eac8-44ef-11e8-93b0-e1eb88df886e.jpg)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : த.சீனிவாசன் - tshrinivasan@gmail.com
உரிமை: Public Domain-CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/PandiyanParisuA4

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/pandiyan_parisu/
