### ISSUE TITLE
இதயச் சுவடுகள் - ஹேமா தனசேகர்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#663]
<strong> மின்னூல் பெயர்: </strong>இதயச் சுவடுகள்
<strong>ஆசிரியர் பெயர்: </strong>ஹேமா தனசேகர்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>hemadhanasek@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1_ecogKRp8-5dJHLLyhC2INSySC_pjSG7tsVvW18c46I

**Comment by gurulenin** [comment]
https://freetamilebooks.com/ebooks/idhayasuvadugal/
