### ISSUE TITLE
வெற்றிகரமான வாழ்வு - ஜேம்ஸ் ஆலன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#665]
<strong> மின்னூல் பெயர்: </strong>வெற்றிகரமான வாழ்வு
<strong>ஆசிரியர் பெயர்: </strong>ஜேம்ஸ் ஆலன்
<strong>ஆசிரியர் மின்னஞ்சல் முகவரி: </strong>arun2010g@gmail.com
<strong>மொழிபெயர்ப்பாளர் பெயர்: </strong>சே. அருணாசலம்
<strong>மொழிபெயர்ப்பாளர் மின்னஞ்சல் முகவரி: </strong>arun2010g@gmail.com
<strong>மின்னூலின் காப்புரிமை: </strong>Creative Commons Attribution -NonCommercial-ShareAlike ( யாரும் பகிரலாம், விற்பனை கூடாது)
<strong>அட்டைப்படம்: </strong>
<strong>மின்னூலுக்கான கோப்பு: </strong>https://drive.google.com/open?id=1IJoeWaxHDJK4hjt0Tht6sXlScFvKyTLt

**Comment by gurulenin** [comment]
![Uploading vetrikaramana-vaaqzhvu-arunachalam.png…]()

**Comment by gurulenin** [comment]
![vetrikaramana-vaaqzhvu-arunachalam](https://github.com/KaniyamFoundation/Ebooks/assets/15311390/61a97f5a-df47-4148-aa4a-100a17b5033f)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/life_triumphant
