### ISSUE TITLE
 எளிய தமிழில் 3D Printing

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#666]
https://kaniyam.com/category/3d-printing-in-tamil/

ஆசிரியர் : இரா. அசோகன்

மின்னஞ்சல் : ashokramach@gmail.com

உரிமை : CC-BY-SA

**Comment by gurulenin** [comment]
![3d-print-tamil](https://github.com/KaniyamFoundation/Ebooks/assets/15311390/f67eb31c-166e-47db-a6d0-ff9e7d32e542)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/3D_printing_in_tamil
