### ISSUE TITLE
 பேராலயமும் சந்தையும்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#667]
https://kaniyam.com/category/the-cathedral-and-the-bazaar/

ஆசிரியர் : இரா. அசோகன்

மின்னஞ்சல் : ashokramach@gmail.com

உரிமை : CC-BY-SA

**Comment by gurulenin** [comment]
![cathedral-and-market-ashokan](https://github.com/KaniyamFoundation/Ebooks/assets/15311390/1de7e7ec-2d0c-4020-b3f9-4e01d9b4d330)

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/the_cathedral_and_the_bazaar
