### ISSUE TITLE
சமணமும் தமிழும் (முதல் பாகம்) - மயிலை சீனி. வேங்கடசாமி 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#67]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0598.html

**Comment by gurulenin** [comment]
![samanam](https://user-images.githubusercontent.com/15311390/38992592-d0f90fd6-43fe-11e8-9706-99f82b163fe0.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/SamanamumTamilum6Inch

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/samanamum_tamilum

வெளியிடப்பட்டது.
