### ISSUE TITLE
வீரர் உலகம் - கி. வா. ஜகந்நாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#68]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0577.html

**Comment by gurulenin** [comment]
![veerar-ulagam](https://user-images.githubusercontent.com/15311390/38998511-52c6d490-440d-11e8-81ed-2e51c92d178e.jpg)

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/veerar-ulagam/
