### ISSUE TITLE
அருள் நெறி முழக்கம் (சொற்பொழிவுகள்) - தவத்திரு குன்றக்குடி அடிகளார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#684]
https://www.projectmadurai.org/pm_etexts/utf8/pmuni1000.html

copyright - public domain

**Comment by leela37** [comment]
im working on this

**Comment by tshrinivasan** [comment]
![arul-neri](https://github.com/user-attachments/assets/a501ddca-2451-4317-b9de-a59ed832f132)

**Comment by leela37** [comment]
completed the book. uploaded here. 

https://drive.google.com/drive/folders/1728Zz604FATS7dz_TFW_Y_ZclZVKZemK?usp=sharing

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம் - https://freetamilebooks.com/ebooks/arul_neri_muzhakkam
