### ISSUE TITLE
புதுக்கவிதையின் தோற்றமும் வளர்ச்சியும் - வல்லிக்கண்ணன் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#69]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0570.html

**Comment by tshrinivasan** [comment]
![new-poem](https://user-images.githubusercontent.com/1268536/39084061-b04e4f6e-458c-11e8-94f5-469f2b41bfa4.jpg)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : த.சீனிவாசன் - tshrinivasan@gmail.com
உரிமை: Public Domain-CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/PuthuKavithai6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Birth_and_growth_of_modern_tamil_poems

**Comment by rajiinperth** [comment]
Hi...Sorry...it's okay...

No need to notify me...

Rarely i login to this id
