### ISSUE TITLE
சிரிக்கும் பூக்கள் - சிறுவர்களுக்கான பாடல்கள் தொகுப்பு  - குழந்தைக் கவிஞர் அழ.வள்ளியப்பா 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#72]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0535.html

**Comment by gurulenin** [comment]
![sirikum-pookkal](https://user-images.githubusercontent.com/15311390/39080993-b35e0090-4556-11e8-992f-8142a95a75ae.jpg)

**Comment by rajiinperth** [comment]
artist name  ?

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : லெனின் குருசாமி

guruleninn@gmail.com

book license : Public Domain - CC0

**Comment by rajiinperth** [comment]
okay

**Comment by rajiinperth** [comment]
https://archive.org/details/SirikumPookal6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/sirikkum_pookkal_rhymes
