### ISSUE TITLE
வேருக்கு நீர் - ராஜம் கிருஷ்ணன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#74]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0519.html

**Comment by tshrinivasan** [comment]
![verukku-neer](https://user-images.githubusercontent.com/1268536/39083831-f23332e0-4588-11e8-9b3b-999c3c40a12f.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Vaeruku_Neer-2018-04-22-22-32-24

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/vaeruku_neer/

released here
