### ISSUE TITLE
தனி வீடு (சொற்பொழிவுகள்)  - கி. வா. ஜகந்நாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#75]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0438.html

**Comment by gurulenin** [comment]
![alone-home](https://user-images.githubusercontent.com/15311390/38996085-06bae8c0-4408-11e8-9e26-b2314601e613.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Thani_Veedu-2018-04-22-22-27-47

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/thani_veedu/

released here
