### ISSUE TITLE
கரிகால் வளவன் - கி. வா. ஜகந்நாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#77]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0418.html

**Comment by tshrinivasan** [comment]
![karikal-valavan](https://user-images.githubusercontent.com/1268536/39068525-362b22ee-44fa-11e8-9fe9-4b657bd697e8.jpg)

**Comment by manimaran96** [comment]
https://archive.org/details/karikal_valavan-2018-04-22-19-27-19

**Comment by manimaran96** [comment]
https://archive.org/details/karikal_valavan-2018-04-22-19-27-19

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/karikal_valavan/

இங்கே வெளியிட்டுள்ளோம்
