### ISSUE TITLE
கன்னித்தமிழ் (கட்டுரைகள்) - கி. வா. ஜகந்நாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#78]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0412.html

**Comment by gurulenin** [comment]
![kannitamil](https://user-images.githubusercontent.com/15311390/38997646-92b1896c-440b-11e8-820d-e9c551a60849.jpg)

**Comment by gurulenin** [comment]
https://archive.org/details/Kannit_Tamiz-2018-04-22-22-08-31

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/kannit_tamizh/

released here
