### ISSUE TITLE
கடற்கரையிலே  (இலக்கியக் கட்டுரைகள்) - ரா.பி. சேதுப்பிள்ளை

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#79]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0373.html

**Comment by gurulenin** [comment]
![seashore](https://user-images.githubusercontent.com/15311390/38996725-71d42e4a-4409-11e8-9502-0c7ff7a81881.jpg)

**Comment by saranraj48** [comment]
[content.txt](https://github.com/KaniyamFoundation/Ebooks/files/1935670/content.txt)

**Comment by tshrinivasan** [comment]
cover image = லெனின் குருசாமி guruleninn@gmail.com
license - Public Domain -CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/kadarkarai_6_inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/kadarkaraiyile
