### ISSUE TITLE
காவியமும் ஓவியமும் (கட்டுரைகள்) - கி. வா. ஜகந்நாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#81]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0350.html

**Comment by gurulenin** [comment]
![kaviyam](https://user-images.githubusercontent.com/15311390/38981046-06ef48ee-43dc-11e8-8a43-da672c292bf4.jpg)

**Comment by nifey** [comment]
https://archive.org/details/kaaviyamumoviyamum-2018-04-22-18-32-47

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/kaaviyamumoviyamum/

இங்கே வெளியிட்டுள்ளோம்
