### ISSUE TITLE
இலக்கியத்தின் எதிரிகள் - ம.பொ. சிவஞானம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#83]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0327.html

**Comment by tshrinivasan** [comment]
![ilakkiyathin-ethirigal](https://user-images.githubusercontent.com/1268536/39067479-68d0f1a0-44f6-11e8-8004-29eb5a3e2c21.jpg)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : த.சீனிவாசன் - tshrinivasan@gmail.com
உரிமை: Public Domain-CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/IlakiyathinEthirigalA4

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/Ilakiyathin_Ethirigal
