### ISSUE TITLE
எதிர்பாராத முத்தம் - பாவேந்தர் பாரதிதாசன் 

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#84]
http://www.projectmadurai.org/pm_etexts/utf8/pmuni0159.html

**Comment by gurulenin** [comment]
![kiss](https://user-images.githubusercontent.com/15311390/38993059-2b15ac8a-4400-11e8-92a2-38fa5b7253b5.jpg)

**Comment by manimaran96** [comment]
[content.txt](https://github.com/KaniyamFoundation/Ebooks/files/1935635/content.txt)

**Comment by tshrinivasan** [comment]
அட்டைப்படம் : லெனின் குருசாமி - guruleninn@gmail.com
உரிமை: Public Domain-CC0

**Comment by rajiinperth** [comment]
https://archive.org/details/Ethirparamutham6Inch

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/ethirparatha-mutham/
