### ISSUE TITLE
ஒரு பூர்வ பௌத்தனின் சாட்சியம் - ப. மருத நாயகம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#85]
https://ta.wikisource.org/s/8vwn

**Comment by tshrinivasan** [comment]
![image](https://user-images.githubusercontent.com/1268536/38977702-bd5d081e-43d2-11e8-81ef-9a40e524efde.png)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/oru_poorva_bavthanin_satchiyam

**Comment by tshrinivasan** [comment]
released here http://freetamilebooks.com/ebooks/oru_poorva_bavthanin_satchiyam/
