### ISSUE TITLE
﻿முவரை வென்றான் - நா. பார்த்தசாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#86]
https://ta.wikisource.org/s/8vw2

**Comment by tshrinivasan** [comment]
![image](https://user-images.githubusercontent.com/1268536/38977843-2db56d4a-43d3-11e8-8c30-2f353a859cdc.png)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/moovarai_vendran

**Comment by tshrinivasan** [comment]
add line breaks for paras and rework on this book.

**Comment by tshrinivasan** [comment]
https://archive.org/details/moovarai_vendran_201806

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/moovarai_vendran/

released here.
