### ISSUE TITLE
எழு பெரு வள்ளல்கள் - கி. வா. ஜகந்நாதன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#87]
https://ta.wikisource.org/s/8vp0

**Comment by tshrinivasan** [comment]
![image](https://user-images.githubusercontent.com/1268536/38977900-5a4d72b2-43d3-11e8-998c-8acddf05531c.png)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/ezhu_vallalgal

**Comment by tshrinivasan** [comment]
give linebreaks for paragraphs for both pdfs

**Comment by tshrinivasan** [comment]
https://archive.org/details/ezhu_peru_vallalgal

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/ezhu_peru_vallalgal/
