### ISSUE TITLE
தசாவதாரம் - அறிஞர் அண்ணா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#88]

**Comment by tshrinivasan** [comment]
https://ia801502.us.archive.org/31/items/dasavatharam-2018-03-27-20-11-46/dasavatharam.jpg

**Comment by tkdhanasekar** [comment]
https://archive.org/details/dasavatharam-2018-03-27-20-11-46

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/dasavatharam/

இங்கே வெளியிட்டுள்ளோம்
