### ISSUE TITLE
ஏட்டில் இல்லாத மகாபாரதக் கதைகள் - புலவர் த. கோவேந்தன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#89]
https://ta.wikisource.org/s/8vbv

**Comment by tshrinivasan** [comment]
![image](https://user-images.githubusercontent.com/1268536/38978057-d8d2527e-43d3-11e8-9364-3678423b2db7.png)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/eatil_illatha_mahabaratha_kadhaigal

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/eatil_illatha_mahabaratha_kadhaigal/

இங்கே வெளியிட்டுள்ளோம்.
