### ISSUE TITLE
மாணவர்களுக்கு புறநானூற்றுச் சிறுகதைகள்  - முல்லை முத்தையா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#90]
https://ta.wikisource.org/s/8viw

**Comment by tshrinivasan** [comment]
![image](https://user-images.githubusercontent.com/1268536/38978084-f831629a-43d3-11e8-952a-cee55e27eb7c.png)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/manavarkaluku_purananutru_kadhaigal

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/manavarkaluku_purananutru_kadhaigal/
