### ISSUE TITLE
ஏலக்காய் - பூவை. எஸ். ஆறுமுகம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#91]
https://ta.wikisource.org/wiki/%E0%AE%8F%E0%AE%B2%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%BE%E0%AE%AF%E0%AF%8D

**Comment by tshrinivasan** [comment]
![image](https://user-images.githubusercontent.com/1268536/38978165-30a6269c-43d4-11e8-9aa8-891171c65d2a.png)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/elakai

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/elakai/
