### ISSUE TITLE
சேக்கிழார் - டாக்டர். மா. இராசமாணிக்கனார்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#92]
https://ta.wikisource.org/s/8uy0

**Comment by tshrinivasan** [comment]
![image](https://user-images.githubusercontent.com/1268536/38978236-65e274a0-43d4-11e8-81a8-c3c8e0fdb412.png)

**Comment by tkdhanasekar** [comment]
https://archive.org/details/sekkizhar_201803

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/sekkizhar/

இங்கே வெளியிட்டுள்ளோம்.
