### ISSUE TITLE
திருப்புமுனை - மணவை முஸ்தபா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#93]
https://ta.wikisource.org/s/8uvo

**Comment by tshrinivasan** [comment]
cover iamge = 
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/%E0%AE%A4%E0%AE%BF%E0%AE%B0%E0%AF%81%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81%E0%AE%AE%E0%AF%81%E0%AE%A9%E0%AF%88.pdf/page1-1240px-%E0%AE%A4%E0%AE%BF%E0%AE%B0%E0%AF%81%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81%E0%AE%AE%E0%AF%81%E0%AE%A9%E0%AF%88.pdf.jpg

**Comment by tkdhanasekar** [comment]
https://archive.org/details/thirupumunai

**Comment by tkdhanasekar** [comment]
https://archive.org/details/thirupumunai

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/thirupumunai/

இங்கே வெளியிட்டுள்ளோம்
