### ISSUE TITLE
அசோகர் கதைகள் - நாரா. நாச்சியப்பன்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#94]
https://ta.wikisource.org/s/2udy

**Comment by tshrinivasan** [comment]
![asokar-stories](https://user-images.githubusercontent.com/1268536/39063855-f62586b8-44e9-11e8-95fd-4cbcb01d02b6.jpg)

**Comment by nifey** [comment]
https://archive.org/details/ashokarkadhaigal-2018-04-22-16-25-26

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/ashokarkadhaigal/

இங்கே வெளியிட்டுள்ளோம்.
