### ISSUE TITLE
எனது நாடக வாழ்க்கை  - அவ்வை தி. க. சண்முகம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#95]
https://ta.wikisource.org/s/8wu8

**Comment by balaaagi** [comment]
![selection_056](https://user-images.githubusercontent.com/2221784/39085510-0ba744a6-45a1-11e8-84e2-96c27c0eded1.png)

**Comment by tshrinivasan** [comment]
Thanks @balaaagi
The above image is low resolution and copyrighted.
We can not use it.

We have to make a new one ourself.

**Comment by balaaagi** [comment]
ok @tshrinivasan . Can we tag that also in issues? which one need our own creation?

**Comment by tshrinivasan** [comment]
We need to create all the cover images ourself.

We can not use the same cover image available in internet, sites like amazon, or other book selling sites, as the cover images have their own copyrights.

Thats why we create all the cover images ourself using the public domain images available at http://pxhere.com/ and http://pixabay.com/ kind of sites.

Check the other issues that dont have tag "அட்டைப்படம் தருக" to see how the cover images are.

Thanks for your contributions and suggestions.

**Comment by tshrinivasan** [comment]
அட்டைப்படம் -
பெயர் - எம்.ரிஷான் ஷெரீப்
மின்னஞ்சல் முகவரி - mrishansha@gmail.com

![default](https://user-images.githubusercontent.com/1268536/50397962-06166600-079a-11e9-99c6-2233dbcc5019.jpg)

**Comment by rajiinperth** [comment]
https://archive.org/details/EnadhuNadakaValkai6Inch

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/Enadhu_Nadaka_Valkai

இங்கே வெளியி்ட்டுள்ளோம்.
