### ISSUE TITLE
எழிலரசி கிளியோபாத்ரா நாடகம்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#96]
cover = https://archive.org/download/ezhilarasi_cleopatra/ezhilarasi_cleopatra.jpg

**Comment by tkdhanasekar** [comment]
https://archive.org/details/ezhilarasi_cleopatra

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/ezhilarasi_cleopatra/

இங்கே வெளியிட்டுள்ளோம்
