### ISSUE TITLE
திராவிடர் இயக்க பார்வையில் பாரதி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#97]
ஆசிரியர்  வாலாசா வல்லவன்

**Comment by tshrinivasan** [comment]
cover = https://archive.org/download/dravidar_iyka_parvaiyil_bharathiyar/bharathi.jpg

**Comment by tkdhanasekar** [comment]
https://archive.org/download/dravidar_iyka_parvaiyil_bharathiyar

**Comment by tshrinivasan** [comment]
@dna80 please add line break between paragraphs for both pdf and reupload again.

**Comment by tshrinivasan** [comment]
https://archive.org/details/dravidar_iyaka_parvaiyil_bharathiyar

**Comment by tshrinivasan** [comment]
released here
http://freetamilebooks.com/ebooks/dravidar_iyaka_parvaiyil_bharathiyar/
