### ISSUE TITLE
ஜோசப் ஸ்டாலின் வாழ்க்கை வரலாறு - நன்மாறன் என்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#98]
![stalin](https://user-images.githubusercontent.com/1268536/39083629-fadec93a-4584-11e8-8b55-05e9df0bfc5d.jpg)

**Comment by khaleeljageer** [comment]
https://archive.org/details/JosephStalin-2018-04-22-17-13-27

**Comment by tshrinivasan** [comment]
இங்கே வெளியிட்டுள்ளோம்.
http://freetamilebooks.com/ebooks/josephstalin/
