### ISSUE TITLE
கற்பனாவாத சோஷலிசமும் விஞ்ஞான சோஷலிசமும்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Ebooks#99]
![socialism](https://user-images.githubusercontent.com/1268536/39083641-22ffcd6a-4585-11e8-9fa9-0760730c8f49.jpg)

**Comment by khaleeljageer** [comment]
https://archive.org/details/karpanavathasocialism-2018-04-22-16-30-03

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/ebooks/karpanavathasocialism/

இங்கே வெளியிட்டுள்ளோம்
